### PR TITLE
[Android] Fix Einstein@home attach

### PR DESCRIPTION
**Pull request by AenBleidd**
For now Einstein@home is the only project that could return an error in error message instead of error code.
Attach behavior fixed to include this situation in flow and react accordingly

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Should fix #3765 and #4196 also

**Review by talregev — APPROVED** [review]
I test it on oneplus one device.
Add 3 projects together: WCG, rosseta, and Einstein.
all 3 projects was added after I press continue without errors.

**Comment by brevilo** [comment]
> For now Einstein@home is the only project that could return an error in error message instead of error code.

Which RPC are we talking about exactly?

Thanks

**Comment by AenBleidd** [comment]
@brevilo, not 100% sure, but looks like this: `<create_account/>`

**Comment by brevilo** [comment]
Do you have an example for your claim? We're following the [official RPC spec](https://boinc.berkeley.edu/trac/wiki/WebRpc), including the returned XML document in case of errors (with number and message). Please note that the wiki entry on the return XML is wrong: the error message is found in a `[error_msg](https://github.com/BOINC/boinc/blob/master/html/inc/web_rpc_api.inc#L87)` tag, not `error_string`, but that's unrelated to the issue discussed here.

**Comment by AenBleidd** [comment]
When this RPC is sent with the credentials of existing account, 
`error_num` is `0`,
`error_string` is `-208`
This is what returned by Einstein@home.
Definitely, it should be next:
`error_num` is `-208`
`error_string` is some meaningful message.
But other projects (e.g. Rosetta) in case of existing account just return authenticator (this is a desired behavior, IIRC).

**Comment by brevilo** [comment]
> When this RPC is sent with the credentials of existing account,
> `error_num` is `0`,
> `error_string` is `-208`

I doubt that. When I send a `create_account` RPC I get this:
```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<error>
    <error_num>-208</error_num>
    <error_msg>Account creation is done through our Web site. Please register at https://einsteinathome.org/user/registration</error_msg>
</error>
```
That is perfectly valid in terms of the RPC response formatting, isn't it?

Also, as I just noted: if you're really parsing `error_string` then you're parsing the XML response wrong. The tag is called `error_msg`.

**Comment by AenBleidd** [comment]
@brevilo, excuse me, you're completely right, it's an issue on our side. I'll fix that. Sorry for any inconveniences

**Comment by brevilo** [comment]
No problem. Just wanted to make sure I don't miss a potential issue on our side 👍

**Pull request merged**
