### PR TITLE
LIB: Fix UB when printf-like format specifiers don't match argument types

### PR DESCRIPTION
**Pull request by dimhotepus**
**Description of the Change**
Using format specifier that doesn't match argument type in `printf` functions family is undefined behavior (UB). 
* Change format specifiers to the correct ones for passed into `printf` family arguments.
* Extend printed 64 bit values to 16 hex digits width with leading zeros.
* Print correct, not truncated to 4 bytes values of crash info params and process dumps on x86-64.

**Release Notes**
* Windows crash info's now contain correct values of cpu registries, stack params and addresses involved for x86-64.
* Windows process information dumps now contain correct values of I/O and memory usage counters for x86-64.

### CODE REVIEW

**Comment by dimhotepus** [comment]
May be we should update appveyor build scripts to use vs 2010 image and tools?

Now build is performed with vs 2013 image.

**Comment by AenBleidd** [comment]
This PR is failed to build with VS2010:
https://ci.appveyor.com/project/BOINC/boinc/builds/33474716/job/h72l18pvylw2w4c6

**Comment by davidpanderson** [comment]
Let's not do this.

**Comment by dimhotepus** [comment]
Sorry, was too busy last month. 

What i'm going to do is to define portable `size_t` `printf` format specifier between main compilers (looking at you, MinGW) this weekend. 

It's kind of not so easy job to do, so if you against this pull request, please, tell me, ok?
@AenBleidd, @davidpanderson

**Comment by AenBleidd** [comment]
Personally I'm not against it. But there is a way to use more common format specifiers for almost every type

**Comment by davidpanderson** [comment]
Would this fix any bugs?  If not, let's not do it.

**Comment by dimhotepus** [comment]
> Personally I'm not against it. But there is a way to use more common format specifiers for almost every type

Cast values to 64 bit upper equivalent (`size_t` => `unsigned long long` | `%llu`) and use related format specifiers?
Unfortunately, MinGW is still a problem here, need either to define `__USE_MINGW_ANSI_STDIO 1` (intrusive, can't ensure smth isn't broke) or still define portable format specifier for 64 bit upper equivalent type.

**Comment by dimhotepus** [comment]
> Would this fix any bugs? If not, let's not do it.

Windows crash info contains stripped values of cpu registries, stack params and addresses involved for x86-64, also process information dumps can contain incorrect values of I/O and memory usage counters for x86-64. 

Not a critical bugs, if we can live with them.

**Comment by AenBleidd** [comment]
The same changes were done in a different way in another PR. Closing this.

**Pull request closed without merging**
