### PR TITLE
[Android] Replace PNGs with vector drawables.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
**Description of the Change**
Replace the PNGs currently used for icons with similar vector drawables and SVGs. This eliminates the need for separate resource sets with each resolution type.

**Release Notes**
Replace the icons used in the app with Material icons.

### CODE REVIEW

**Comment by adamradocz** [comment]
Shouldn't the file type be SVG instead of XML?

**Comment by Isira-Seneviratne** [comment]
On Sun, Apr 26, 2020, 8:06 PM Adam Radocz <notifications@github.com> wrote:

> Shouldn't the file type be SVG instead of XML?
>

Android Studio requires SVGs to be imported as vector drawables.

**Comment by adamradocz** [comment]
I see Android Studio uses XML file to define the vector drawable.

**Comment by AenBleidd** [comment]
@Isira-Seneviratne, please fix merge conflict

**Pull request merged**
