### PR TITLE
Manager: 'Add Project Wizard': enable 'Cancel' but for non-final step…

### LINKED ISSUE #1044: When adding a project or account manager, the final step should not allow Cancel.
**Reported by JacobKlein on 27 Aug 41245708 06:40 UTC**
When adding a project, the final dialog says:[added[[BR]([BR]]Project)]This project has been successfully added.[Finish to close[[BR]([BR]]Click)]... yet Cancel is shown as an option, and when clicked, appears to be functionally identical to the Finish button.

When adding an account manager, the final dialog says:[using account manager[[BR]([BR]]Now)]You are now using this account manager.[Finish to close.[[BR]([BR]]Click)]... yet Cancel is shown as an option, and when clicked, appears to be functionally identical to the Finish button.

In both of these cases (where project is successfully added, or account manager is successfully set up), the final step should not allow Cancel.

It should either be greyed out, or better yet, the Cancel button should not be shown.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1068

### PR DESCRIPTION
**Pull request by AenBleidd**
…s only

Fixes #1044.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
FIx for #1044

**Comment by AenBleidd** [comment]
@Ageless93, @ChristianBeer, could you please review this? Thanks

**Comment by CharlieFenton** [comment]
Rom wrote all the wizard code, and it is very complex and challenging to understand.

**Comment by Ageless93** [comment]
Including the buttons?

On Friday, November 3, 2017, CharlieFenton <notifications@github.com> wrote:
> Rom wrote all the wizard code, and it is very complex and challenging to
understand.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/XJPDhdrj2TuSnDjAVJI0FORe-79MOCbdhpH_4XJ0uV3g_By_fm7gIKO1TGxGAH6LIVNM0j6xqtl4ZBxQWz77dELwUJeaNPkRDrIl123NlRU4WLInT_FkDuNtpk1mexfEKfpWpZtc92bNzIrRCH3dM3JpzZwCXQ=s0-d-e1-ft#https://github.com/notifications/beacon/AKXbU00O6Jbe4FE5fI6fkEJYECEoXrL8ks5sylSIgaJpZM4QKKVv.gif
>

-- 
Jord.

**Comment by CharlieFenton** [comment]
It would be more consistent with other code in the Attach Project Wizard to call the method `CBOINCBaseWizard::EnableCancelButton()` which is found in BOINCaseWizard.cpp / BOINCaseWizard.h instead of disabling it directly in wizardex.cpp. Otherwise it looks fine to me.

**Comment by AenBleidd** [comment]
@CharlieFenton, 
I think that disabling this button directly in wizardex constructor is better because all buttons logic is located here. BOINCBaseWizard is just a wrapper of wizardex so I think it is better to keep logic in one place in wizardex constructor.
Actually CBOINCBaseWizard::EnableCancelButton() make the same call without additional logic so I see no reason to use it in-place instead of general solution.

**Comment by CharlieFenton** [comment]
I looked deeper and see that BOINCBaseWizard.cpp includes wizardex.h, not the other way around, so you are correct. CBOINCBaseWizard::EnableCancelButton() can not be called from wizardex.cpp.

**Pull request merged**
