### PR TITLE
scheduler: when sending a job, decrement work request time by the correct amount.

### LINKED ISSUE #4151: Server: Bug: Runtime of MT tasks underestimated in sched_send
**Describe the bug**
When a client requests work, the request is expressed in core-seconds. The server doesn't factor in the core usage.

**Expected behavior**
The server needs to estimate the real cpu usage, across all applicable cores, for MT tasks.

**Log entries**
```
14/01/2021 19:30:21 |  | [work_fetch] Request work fetch: project work fetch resumed by user
14/01/2021 19:30:22 |  | [work_fetch] target work buffer: 8640.00 + 864.00 sec
14/01/2021 19:30:22 |  | [work_fetch] shortfall 38016.00 nidle 4.00 saturated 0.00 busy 0.00
14/01/2021 19:30:22 | Milkyway@Home | [sched_op] CPU work request: 38016.00 seconds; 4.00 devices
14/01/2021 19:30:24 | Milkyway@Home | Scheduler request completed: got 23 new tasks
14/01/2021 19:30:24 | Milkyway@Home | [sched_op] estimated total CPU task duration: 39233 seconds
```
```
11/01/2021 12:00:39 | PrimeGrid | CPU needs work - buffer low
11/01/2021 12:00:39 | PrimeGrid | [work_fetch] request: CPU (38016.00 sec, 4.00 inst) Intel GPU (0.00 sec, 0.00 inst)
11/01/2021 12:00:39 | PrimeGrid | [sched_op] CPU work request: 38016.00 seconds; 4.00 devices
11/01/2021 12:00:40 | PrimeGrid | Scheduler request completed: got 48 new tasks
11/01/2021 12:00:40 | PrimeGrid | [sched_op] estimated total CPU task duration: 56610 seconds
```
In both cases, the 'target work buffer' is expressed in wall time - 9,504 seconds, or about 2 hours 40 minutes.
But the 'request' is for four times that much - over 10 hours of core-time.
In both these cases, the scheduler went on adding MT tasks to the reply **as if single threaded** until the work request was fulfilled. Work for **over ten hours of wall-time** was delivered (more for PrimeGrid, which still uses DCF).

The server estimates task duration at
https://github.com/BOINC/boinc/blob/master/sched/sched_send.cpp#L429 (estimate_duration_unscaled) and
https://github.com/BOINC/boinc/blob/master/sched/sched_send.cpp#L477 (estimate_duration)
Neither routine considers the core loading of the MT tasks allocated.

avg_ncpus is available in the HOST_USAGE structure, and should be considered in either `estimate_duration_unscaled` or `estimate_duration`.

### PR DESCRIPTION
**Pull request by davidpanderson**
We were decrementing by predicted job duration.
Need to multiply this by the # of instances used.
This resulted in too many MT jobs being sent, for example.

Fixes #4151

### CODE REVIEW

**Comment by AenBleidd** [comment]
@RichardHaselgrove, any chance to get this tested together with CPDN?

**Comment by RichardHaselgrove** [comment]
It's not the ideal project. They have a new, experienced, parallel programming developer (Glenn Carter), but he has no prior experience of BOINC. And they have a reasonably experienced BOINC team, but they haven't tackled MT deployment before. Both sides are learning as they go along, with the assistance of the volunteer community, but they're not there yet. I'm trying to remove one of the problems before they reach it.

I see that LHC have a long_native_mt plan class defined. I'll ask @lfield what the status of that is (no tasks currently), since he will be responsible for the deployment anyway.

**Comment by Vulpine05** [comment]
Milkyway@home has a MT application they are running.

**Comment by RichardHaselgrove** [comment]
> Milkyway@home has a MT application they are running.

So does PrimeGrid, as shown in the original issue #4151, but I'm not sure if either of them would be willing to deploy an untested patch on their production server. CPDN does at least have a dev server, which they will be using to text the new app before it goes fully live. I've been trying to set up a client test on LHC, but so far I've been unable to deploy the prerequisite cvmfs service.

**Comment by RichardHaselgrove** [comment]
I now have a working cvmfs installation (installs on Mint 20.3, not on Mint 21), so I can run tests against an LHC server if it helps.

**Comment by lfield** [comment]
LGTM Will merge and fully test on the LHC@home dev project before releasing.

**Comment by RichardHaselgrove** [comment]
With help from @lfield, I've been testing this against provisional server release 1.4.0 at the LHC development site. I don't think it's working. Can anyone spot a flaw in the following analysis?

```
Thu 10 Nov 2022 12:37:30 GMT | lhcathome-dev | work fetch resumed by user
Thu 10 Nov 2022 12:37:32 GMT | lhcathome-dev | [sched_op] Starting scheduler request
Thu 10 Nov 2022 12:37:32 GMT | lhcathome-dev | Sending scheduler request: To fetch work.
Thu 10 Nov 2022 12:37:32 GMT | lhcathome-dev | Requesting new tasks for CPU
Thu 10 Nov 2022 12:37:32 GMT | lhcathome-dev | [sched_op] CPU work request: 5184.00 seconds; 6.00 devices
Thu 10 Nov 2022 12:37:32 GMT | lhcathome-dev | [sched_op] NVIDIA GPU work request: 0.00 seconds; 0.00 devices
Thu 10 Nov 2022 12:37:33 GMT | lhcathome-dev | Scheduler request completed: got 9 new tasks
Thu 10 Nov 2022 12:37:33 GMT | lhcathome-dev | [sched_op] Server version 721
Thu 10 Nov 2022 12:37:33 GMT | lhcathome-dev | Project requested delay of 61 seconds
Thu 10 Nov 2022 12:37:33 GMT | lhcathome-dev | [sched_op] estimated total CPU task duration: 5644 seconds
```

My test settings are 0.01 days plus 0.00 additional. Those are wall time, and I make that 864 seconds total.

I have six cores, all idle, so I need six times that in core-time - that's where the 5184 comes from.

Each task has been estimated at 10:26 minutes, or 626 seconds. On the face of it, 8 tasks would take 5008 seconds, and 9 tasks 5634: ignoring rounding errors, that means the server has terminated the allocation at the right point.

But each task is going to occupy **6 cores for 626 seconds**, or 3756 core-seconds. Just two tasks should have been sufficient to fill my request.

**Comment by davidpanderson** [comment]
They should turn on the debug_send and debug_send_job flags and look at the scheduler log.

**Comment by RichardHaselgrove** [comment]
In the meantime, I preserved the full job specification (app_version, workunit, result) for one of the tasks I received this morning. Looks like a full-formed MT specification to me, but you may be able to spot a flaw.

[LHC-dev task.txt](https://github.com/BOINC/boinc/files/9983367/LHC-dev.task.txt)

**Pull request merged**
