### PR TITLE
Fix typos in Akismet spelling (Slovak translation)

### PR DESCRIPTION
**Pull request by hristog**
**Note:** No associated GitHub issue exists.

**Description of the Change**
A cosmetic fix for typos in the Slovak translation file.
- Incorrect spelling (`master` branch): _Aksimet_ (apparently, there's a malicious Wordpress plug-in with this name, piggybacking on the not so uncommon misspelling that "Aksimet" is);
- Correct spelling (`fix-typos-in-sk-translation` branch): _Akismet_.

**Alternate Designs**
N/A

**Release Notes**
N/A

### CODE REVIEW

**Comment by AenBleidd** [comment]
We're using Transifex to handle translations. If that's possible, please, fix it there: https://www.transifex.com/boinc/boinc/

**Comment by hristog** [comment]
Thanks for letting me know, @AenBleidd!

I've now added these fixes as suggestions to https://www.transifex.com/boinc/boinc/viewstrings/#sk/project-generic/40474616 (reference string IDs are: 694, 694, 995, 1009).

Since I am new to the Transifex system:
 - Could you confirm if this has been a correct action on my part?
 - Is there anything else I need to do, Transifex-wise?
 - Should I close this PR (as rejected, effectively)?

**Comment by AenBleidd** [comment]
> * Could you confirm if this has been a correct action on my part?

Yes

> * Is there anything else I need to do, Transifex-wise?

This should be enough. But you can also check other strings (maybe some other languages too if you know some?)

> * Should I close this PR (as rejected, effectively)?

Yes, please

**Comment by hristog** [comment]
Thanks once again for your responses, @AenBleidd!

Yes, I'll keep an eye out for other translation typos/issues that I might spot along the way.

**Pull request closed without merging**
