### PR TITLE
[Manager][Windows] Prevent close request on minimized window exiting the app

### LINKED ISSUE #5164: BOINC Manager exits completely  when closing minimised window.
**Describe the bug**

**Steps To Reproduce**
1. Open boinc manager window.
2. Minimize it.
3. Hover over it.
4. Close window with middle mouse button.

**Expected behavior**
Boinc window closes without  killing boincmgr.exe
**Screenshots**
image
image
**System Information**
 - OS: Microsoft Windows [Version 10.0.22621.1413]
 - BOINC Version: 7.22.0

**Additional context**
This issue was seen even on 6.10.48
https://boinc.berkeley.edu/forum_thread.php?id=11667&postid=79148

### PR DESCRIPTION
**Pull request by BrianNixon**
Fixes #5164

### CODE REVIEW

**Comment by AenBleidd** [comment]
@RichardHaselgrove, could you please test this?

**Review by AenBleidd — APPROVED** [review]

**Comment by RichardHaselgrove** [comment]
Will do, a little later this morning.

**Comment by RichardHaselgrove** [comment]
I'm sorry - I'm getting nowhere with this. Github is playing up - keeps failing to follow links: CI hasn't created any artifacts - I could build my own, but it would take longer: and I can't reproduce the original problem.

Tested under Windows 7 and Windows 11. Clicking the mouse wheel has no effect (I don't have a three-button mouse), and right-clicking on a minimised icon doesn't have the reported effect. 'Close window' (or 'Close all windows', if the event log is also visible), does close the windows: but I have my machines set up to display the notification area icon at all times, and that shows that the Manager is still running in 'hidden' mode - it can be re-launched from the icon.

I think we may need to request further information from the author of #5164, as to exactly what curtomisations he has applied to his system.

**Comment by AenBleidd** [comment]
Tested on Windows. Works as expected.

**Pull request merged**
