### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by TheAspens**
Update the project README to add a statement that describes how to submit a security issue.  

Also change the link for how to contribute so that it points to the pages that describe how to make a code contribution.

### CODE REVIEW

**Comment by adamradocz** [comment]
There's a [How to contribute guide](https://github.com/BOINC/boinc/blob/master/CONTRIBUTING.md) in the repo. Shouldn't it be merged with yours?

**Comment by TheAspens** [comment]
The one that I point to was discussed extensively and approved by a vote of the committers (including your vote).  See its pull request  https://github.com/BOINC/boinc-policy/pull/13

The CONTRIBUTING.md shouldn't have been approved since it should simply contain links to the official docs.  I do agree that having two guides is not appropriate.

I would suggest that CONTRIBUTING.md be updated to refer to the other documents.  I can submit that pull request if you like.

**Comment by adamradocz** [comment]
Thanks, that'd be great.

**Comment by adamradocz** [comment]
I just noticed, there's a new security tab in GitHub. Shouldn't we take advantage of that?

**Comment by lfield** [comment]
We should probably discuss the tab in the next phone call.

**Comment by TheAspens** [comment]
Yes - lets discuss.  This looks like a much better way of handling things.

**Pull request merged**
