### PR TITLE
[Windows][Installer] Clean-up installer project

### PR DESCRIPTION
**Pull request by AenBleidd**
- Replace icons
- Remove unused dialog
- Remove SetAllUsers.dll
- Remove Print LA action (I don't believe anybody still uses it). If required - it could be always implemented.
- Replace ISSetupAllUsers 3rd-party function
- Remove unused icons
- Convert custom build target to custom build step to fix build of MSI file when only *.json file was changed.
- Remove SFHelper.dll

### CODE REVIEW

**Comment by talregev** [comment]
When you change UI specially on installer, that is the frontier of boinc for new users. You should add pictures to show how it look like, and wait for other people in community to review it.

**Comment by AenBleidd** [comment]
Not every change done my maintainers must be reviewed by the community.

**Comment by talregev** [comment]
Thank you for the video. 
I am still think that UI changes should come with pictures / videos on the PR. with the updated changes.

**Comment by AenBleidd** [comment]
@talregev, I will not argue with you. Again. Read my previous message.
If you don't like the answer - I can do nothing with that.
I will not change anything to make you feel better and/or happier.

**Pull request merged**
