### PR TITLE
[AppVeyor] Add VS2010 and VS2019 to CI

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by adamradocz** [comment]
Isn't that 2020? :)

**Comment by AenBleidd** [comment]
We're still building BOINC for Windows with VS2010

**Comment by AenBleidd** [comment]
Ready for review

**Comment by TheAspens** [comment]
Looks good - thanks for getting 2019 working and adding it to CI!

**Pull request merged**
