### PR TITLE
Tests: add unit testing framework using googletest

### PR DESCRIPTION
**Pull request by ChristianBeer**
**Description of the Change**
* enable coverage reports from gcc and disable optimizations via option to configure
* install googletest library into buildcache
* script to compile and run unit tests using cmake
* first set of unit tests originally contributed by Keith Uplinger

There are several hardcoded paths and assumptions made in order to get this working on Travis CI. New tooling is using cmake for cross platform builds and as such is not easy to use with an autotools based system.
It's not ideal but better than nothing.

**Alternate Designs**
There are other unit testing frameworks out there that could have been used. Googletest satisfies the current needs and should be for the future since it is xUnit compatible.

**Release Notes**
Added unit-testing capability to BOINC to improve source code quality and find bugs earlier.

### CODE REVIEW

**Comment by ChristianBeer** [comment]
@lfield @Uplinger This is it. Everything that is needed for proper unit testing. I'm not sure why the codecov bot report appears twice but that might change once there is a baseline to diff against. If not then I'm going to send an email to them.

**Comment by Uplinger** [comment]
Closing to restart code checks.

**Comment by Uplinger** [comment]
@ChristianBeer I thought maybe there was an issue with travis failing, and attempted to retrigger the build.  However it failed at the same spot.  I'm not sure why this would be the case, because it does not appear that your code changes actually touch this.  The file it apparently failed on hasn't been changed in master in 8 months.

**Comment by Uplinger** [comment]
I have discusses this with @ChristianBeer and others on the Contributors Call.  Since the code that is being updated doesn't involve the failure, we are merging it.  Thanks

**Pull request merged**
