### PR TITLE
plan classes:  add workunit-related filters

### PR DESCRIPTION
**Pull request by bema-ligo**
filters `<min_wu_id>`, `<max_wu_id>`, `<min_batch>`, `<max_batch>` and `<disabled>`

- WU information is passed from `check_homogeneous_app_version()` down to `PLAN_CLASS::check()`

- `wu_is_infeasible_custom()` is extended such that additional tasks also follow the plan class restrictions.

### CODE REVIEW

**Comment by RichardHaselgrove** [comment]
Test

**Comment by davidpanderson** [comment]
Thanks.  Please update https://boinc.berkeley.edu/trac/wiki/AppPlanSpec

**Comment by davidpanderson** [comment]
There may be a problem with this, because the app version selection mechanism caches the selection.  It might see an old WU, choose an app version, and then use the same version for a later WU.
Can you please describe the use case in detail?

**Comment by brevilo** [comment]
Since this PR got merged prematurely please open a new one to have this discussion in the right place.

Thanks

**Comment by bema-ligo** [comment]
@brevilo I don't know what change I should open a PR with, shall I open an issue?

**Comment by bema-ligo** [comment]
@davidpanderson 
> There may be a problem with this, because the app version selection mechanism caches the selection. It might see an old WU, choose an app version, and then use the same version for a later WU. Can you please describe the use case in detail?

The modification of `PLAN_CLASS::check()` selects an application that matches the WU criteria (max/min WU id, max/min batch). The addition to `wu_is_infeasible_custom()` ensures that subsequent tasks that selected for this app version also conform to the WU criteria for the app version's plan class (`wu_is_infeasible_custom()` calls `plan_class_specs.wu_is_infeasible(plan_class, wu)`, which looks up the WU criteria for this plan class and checks whether teh WU conforms).

**Comment by brevilo** [comment]
You need to open a new PR anyway to get your changes integrated. Just use your original branch for it, again.

**Pull request merged**
