### PR TITLE
add grcpool to account manager list

### PR DESCRIPTION
**Pull request by Holger-Will**
please consider adding grcpool.com to the account manager list. Currently this is done with a manual process using an APK Editor: https://youtu.be/dB-Hmg94E6s

### CODE REVIEW

**Comment by AenBleidd** [comment]
Guys, could you please take a look at this pr and decide whether it should be merged or not. As soon as we will have Android BOINC application released soon it will be good decide it nowl. Thanks
CC: @TheAspens, @davidpanderson, @RichardHaselgrove

**Comment by RichardHaselgrove** [comment]
Science United will have to make their own decision as to whether they wish to attract Android users to their platform. At the moment, their website is silent on the subject.

**Comment by JuhaSointusalo** [comment]
When we were discussing about adding Science United to the project / account manager list it was realised that it was something for PMC to decide. I think it's the same here too.

**Comment by davidpanderson** [comment]
The Android client should get the list of projects and account managers from
win_build/installerv2/redist/all_projects_list.xml
rather than from its own config file

**Comment by AenBleidd** [comment]
Then. I believe, this should be converted into a different task for Android client to move AM settings from configuration.xml file and use general approach.
But, as far as I can see, all_projects_ list.xml doesn't contain this AM either

**Comment by Pretenderr** [comment]
When release ?

**Comment by truboxl** [comment]
I think this should be given green light to attract more people to test the app.

But in the long run, please look back #1582

It is redundant to have people request to add new account manager officially to the AM list per issue/pr if reworking the app to use

https://github.com/BOINC/boinc/blob/master/win_build/installerv2/redist/all_projects_list.xml

takes a long time...

**Comment by adamradocz** [comment]
I think this should be merged and a new PR should be made for the new config.
BTW is https://www.grcpool.com/ and http://pool.gridcoin.co/ are different?

**Comment by JuhaSointusalo** [comment]
@adamradocz

Since you are poking the Android GUI you should remove the hard coded list and get the account managers from `all_projects_list.xml` the same way as desktop Manager does.

I took a quick peek at the source and it looks like Android GUI already gets projects that way so you can use the add project wizard as an example.

**Comment by adamradocz** [comment]
@JuhaSointusalo that was my plan, I looked around, but at the moment I'm not sure I can do it.

**Comment by brevilo** [comment]
@AenBleidd are you able to help @adamradocz with integrating `all_projects_list.xml`?

**Comment by AenBleidd** [comment]
Yes. I can

**Comment by brevilo** [comment]
Nice one!

**Comment by AenBleidd** [comment]
@adamradocz, don't hesitate to contact me via email (lestat.de.lionkur@gmail.com) or via skype (aenvampire).

**Comment by adamradocz** [comment]
#3003 fixed this issue. Sort of... :)

**Comment by lfield** [comment]
What is the status of this PR? I have just resolved the conflicts for you. Should this account manager be added? Is this done in the correct place?

**Comment by AenBleidd** [comment]
@lfield, this PR should be closed because it was decided that all client should you AMs from all_projects_list,xml instead as it is used now by all clients except Android

**Pull request closed without merging**
