### PR TITLE
client: fix bug in set_app_config GUI RPC

### PR DESCRIPTION
**Pull request by davidpanderson**
forgot to fclose().
Also have get_app_config() return error if no file.
Probably should do this for other get-file RPCs as well.

### CODE REVIEW

**Comment by CharlieFenton** [comment]
Neither my Mac nor my Windows 7 PC has an app_config.xml file in any of the project directories (for example, .../projects/setiathome.berkeley.edu/), or anywhere in the BOINC Data directory. Under what circumstances would this RPC ever find such a file? Or am I looking in the wrong place?

**Comment by JuhaSointusalo** [comment]
@CharlieFenton `app_config.xml` allows users to configure apps beyond what BOINC does automatically. The files are not created by an installer or client (except with `boinccmd --set_app_config`) but by user. [Application configuration](http://boinc.berkeley.edu/wiki/Client_configuration#Application_configuration)

@davidpanderson This PR presumably supersedes PR #2152?

**Comment by davidpanderson** [comment]
Yes, it supersedes #2152

**Comment by TheAspens** [comment]
With no app_config.xml:
```
[knreed@oc7811586721 data]$ ../BOINC/boinccmd --get_app_config http://www.worldcommunitygrid.org
get_app_config error: app_config.xml not found
Operation failed: Error -1
```

With the following as projects/www.worldcommunitygrid.org/app_config.xml

```
<app_config>
   <app>
      <name>mip1</name>
      <max_concurrent>1</max_concurrent>
   </app>
</app_config>
```

Then it returns
```
[knreed@oc7811586721 data]$ ../BOINC/boinccmd --get_app_config http://www.worldcommunitygrid.org
   <app_config>
       <app>
           <name>mip1</name>
           <max_concurrent>1</max_concurrent>
           <gpu_gpu_usage>0.000000</gpu_gpu_usage>
           <gpu_cpu_usage>0.000000</gpu_cpu_usage>
           <fraction_done_exact>0</fraction_done_exact>
           <report_results_immediately>0</report_results_immediately>
       </app>
       <project_max_concurrent>0</project_max_concurrent>
       <report_results_immediately>0</report_results_immediately>
   </app_config>

```

**Comment by TheAspens** [comment]
Looks good to me approving and merging.

**Pull request merged**
