### PR TITLE
vboxwrapper: if control op fails, exit for 5 min instead of 1 day

### LINKED ISSUE #3173: Add ability to restart unmanageable VM jobs.
**Describe the problem**
When the VM has not enough memory to run, the BOINC will stop it, but not restarting it for a very long time, or until I restart the BOINC.

**Describe the solution you'd like**
I want a button, which restarts the VM job, so when I manually release some memory, it can run as soon as possible.

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #3173

### CODE REVIEW

**Comment by TheAspens** [comment]
@adamradocz - can one of you review and merge this since it would address your issue?  thanks.

**Comment by hucker75** [comment]
This is not working.
Task camb_boinc2docker_2471226_1671884768.683208_0 postponed for 86400 seconds: VM job unmanageable, restarting later.	
I make 86400 seconds precisely 1 day, as it used to be.

**Comment by RichardHaselgrove** [comment]
Again, this is a project matter. BOINC can update the source code, but it can't force any project to deploy an updated version. Unless you can provide evidence that whichever project it is is using a wrapper dated November 2019 or later, the issue remains with them.

**Comment by hucker75** [comment]
Ah ok, I thought the wrapper was on my client, my mistake.  Knowing cosmology it will be well out of date.

**Pull request merged**
