### PR TITLE
client: fixes for launching GPU detection

### LINKED ISSUE #2657: (Windows) GPU detection fails when started from command line (take 2)
Previous references: issue #2029 , PR #2036.

A year ago we tackled an issue where GPU detection failed if the client was started from the command line with "boinc", rather than "boinc.exe"

The problem has been re-reported for BOINC v7.10.2 and v7.12.1, but this time when the invocation is from a batch file or from BoincTasks, if the correct working directory is not used. Compare these screenshots (from Process Explorer)

boinc client 2 - v7 8 3
boinc client 2 - v7 12 1

After all the multiple restarts to detach from the command window and do the GPU detection, the final running client instance was still started with the full path on the command line (D:\BOINC\... on my machine). By contrast, v7.12.1 starts with the now hard-wired "boinc.exe", but no path.

I think commit 7930686128709433b29741a034dd890c27a616f1 just moved the problem around a bit, without fully fixing it. We need both the path and the .exe

### PR DESCRIPTION
**Pull request by JuhaSointusalo**
Launching GPU detection has a few issues.
- doesn't work reliably with `--detach_console`
- doesn't work if client is run from `$PATH`
- if it fails the user is presented with hard to understand error code
- the code throws compiler warnings

This PR fixes those issues. To support the fixes `get_real_executable_path()` is implemented for several more operating systems and `run_program()` is changed to use `$PATH`. See individual commit messages for details.

Fixes #2657.

### CODE REVIEW

**Comment by JuhaSointusalo** [comment]
@CharlieFenton Please test.

`get_real_executable_path()` is implemented on OSX using `_NSGetExecutablePath()`. Since GPU detection falls back to `argv[0]` if `get_real_executable_path()` fails you'll need to add some test code. I used something like this at the top of client's `main()`:
```c
char path[MAXPATHLEN] = "";
int ret = get_real_executable_path(path, sizeof(path));
fprintf(stderr, "ret %d path %s\n", ret, path);
exit(0);
```
If `_NSGetExecutablePath()` doesn't work or you think it's not appropriate for the job an alternative I found is sysctl `{CTL_KERN, KERN_KERN_PROCNAME}` (`kern.procname`), though that one looks like not exactly well documented.

**Comment by RichardHaselgrove** [comment]
Built and tested under Windows 7 / VS2013.

Checked both problems reported in #2657 and #2029: successful GPU detection in both cases.

**Comment by CharlieFenton** [comment]
@JuhaSointusalo: `_NSGetExecutablePath()` works correctly and is appropriate. However, I disagree in part with your commit 1296c86. I agree that the command `chdir(client_dir)` is redundant, since that is also done inside `run_program()`. However, I believe that without `chdir(data_dir)` after `run_program()` to restore the working directory, the original instance of the client will no longer properly access the BOINC Data directory. Am I missing something here?

**Comment by JuhaSointusalo** [comment]
> However, I believe that without `chdir(data_dir)` after `run_program()` to restore the working directory, the original instance of the client will no longer properly access the BOINC Data directory.

On Windows, the directory that is passed to `run_program()` is only used in a call to `CreateProcess()`. `CreateProcess()` shouldn't modify the parent process in any way.

On others, the directory is used in a call to `chdir()` but that happens after `fork()`, that is, it's changing the current working directory of the child process.

https://github.com/BOINC/boinc/blob/460a6dba1477e222621c2f0b2fc1288d992a8466/lib/util.cpp#L471-L476

Maybe it's the `return` after failed `chdir()` that's confusing here. That's actually a bug in `run_program()` and the code should call `_exit()` instead. If the code returns we'll have two processes running, the parent and a crippled copy of it.

I intend to review all child process launching code in BOINC to see if these bugs are made elsewhere but that's another day another PR.

**Comment by davidpanderson** [comment]
Has anyone tested this on Mac?
I was hoping to make the 7.14 branch today.

**Comment by JuhaSointusalo** [comment]
@CharlieFenton 

I logged current working directory before and after `run_program()` and in both log entries it was the data directory.

**Comment by RichardHaselgrove** [comment]
Although Windows isn't the primary concern of recent comments, the private build I made yesterday has been running since

23-Sep-2018 14:07:24 [---] Starting BOINC client version 7.13.0 for windows_x86_64

The report I made earlier on tests for the original reported problems was with a secondary instance: the primary client has been running constantly and updating files in the data directory as normal. The list of files updated since I started typing this report is

client_state.xml
daily_xfer_history.xml
stdoutdae.txt
client_state_prev.xml
job_log_setiathome.berkeley.edu.txt
statistics_setiathome.berkeley.edu.xml
sched_reply_setiathome.berkeley.edu.xml
sched_request_setiathome.berkeley.edu.xml
job_log_einstein.phys.uwm.edu.txt

**Comment by CharlieFenton** [comment]
@JuhaSointusalo: You are correct. I misread the run_program code. I now see that `chdir(dir)` is in the forked process, not the parent. Since the arguments passed to the child include `-dir quoted_data_dir`, the _client_dir_ argument to `run_program` is not needed and NULL could be passed instead. If you do that, **all** references to _client_dir_ should be removed, including the entire `COPROCS::set_path_to_client()` method and the call to it  in `main()`.

This _log_flags_ message should also be removed, as it is no longer correct since you have modified the code to use an absolute path:
```
       msg_printf(0, MSG_INFO,
            "[coproc] relative to directory %s",
            client_dir
        );

```

**Comment by CharlieFenton** [comment]
> Has anyone tested this on Mac?
I was hoping to make the 7.14 branch today.

@davidpanderson: I tested it and further changes are needed, as I wrote in my last comment. At the very least, the incorrect _log_flags_ message must be removed. All references to the now unnecessary static variable _client_dir_ should also be removed, including  the entire `COPROCS::set_path_to_client()` method and the call to it in `main()`.

**Comment by davidpanderson** [comment]
Juha, can you please address Charlie's suggestions?
Thanks -- D

**Comment by JuhaSointusalo** [comment]
> since you have modified the code to use an absolute path

Well, the code _tries_ to use absolute path but that doesn't work everywhere. I know it doesn't work on OpenBSD at all because OpenBSD provides no way to find out the filename and path of the current program. It also doesn't work on NetBSD 7 if `/proc` is not mounted (the sysctl is NetBSD 8 thing). I don't know for sure it won't ever fail on other systems.

One could argue that OpenBSD doesn't support GPU crunching and never will and we don't need to care about it but I still would like to keep `argv[0]` as a backup. `argv[0]` could be something like `./boinc` and then we need to know what directory the client was started in. Calling the variable `client_dir` is a bit misleading but I'm not sure what to call it then. `dir_that_was_cwd_at_startup`?

Sidenote: I suppose implementing `get_real_executable_path()` on BSDs and Solaris was kinda unnecessary. I was searching for something and came across info on how to find out executable path on those. So I figured why not use the info, if we ever decide to have good support for BSDs then there won't be need to find that information again.

**Comment by CharlieFenton** [comment]
>  I still would like to keep argv[0] as a backup

Fair enough. Perhaps this is getting too fussy, but it would be nice if this log_flags message would appear **only** when `get_real_executable_path()` failed:
```
        msg_printf(0, MSG_INFO,
            "[coproc] relative to directory %s",
            client_dir
        );

```

**Comment by JuhaSointusalo** [comment]
@CharlieFenton Ready for re-review.

**Comment by CharlieFenton** [comment]
@JuhaSointusalo I tested this and it works as intended. Thank you. I approve this PR for merging into master.

**Pull request merged**
