### PR TITLE
remote job submission: add an API function for setting RPC timeout

### PR DESCRIPTION
**Pull request by AenBleidd**
boinc_set_timeout($x): set timeout for job submission RPCs to x seconds

### CODE REVIEW

**Comment by AenBleidd** [comment]
Just a clean copy of #3315 with no unrelated commit

**Comment by TheAspens** [comment]
@lfield - are you able to review this PR?  I believe that you use the remote submission API and would be in a good position to review.  Let me know - thanks!

**Comment by lfield** [comment]
A question and a comment before I test tomorrow. Is this also needed for the C++ code? I think the Python global should also be rpc_timeout.

**Comment by davidpanderson** [comment]
I changed the variable name.  If anyone asks for this feature in the C++ API I'll add it.

**Comment by lfield** [comment]
I testing both the python and php. Python returns:
`ssl.SSLError: ('The read operation timed out',)`
PH returns:
`Error: HTTP error`
As far as I understand both are behaving as designed.

**Pull request merged**
