### PR TITLE
[Linux][Manager] Updating wxwidgets to v3.2.0

### PR DESCRIPTION
**Pull request by talregev**
[Linux][Manager] Updating wxwidgets to v3.2.0.

### CODE REVIEW

**Comment by talregev** [comment]
@LocutusOfBorg FYI.
Can you update wxwidgets Debian package to 3.2.0?

**Comment by talregev** [comment]
without webview:
image

**Review by AenBleidd — APPROVED** [review]

**Comment by LocutusOfBorg** [comment]
Hello, tracked here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=919903

**Comment by talregev** [comment]
Thank you.
Can you update upstream (not daily) to boinc 7.20.2?

**Comment by LocutusOfBorg** [comment]
boinc - 7.22.0+dfsg+git20220715+r25160~r118~ubuntu21.10.1 | on 2022-07-15                                                buildlog                 (969.0 KiB)
-- | --


[FULLYBUILT] [boinc - 7.22.0+dfsg+git20220715+r25160~r118~ubuntu21.10.1](https://code.launchpad.net/~costamagnagianfranco/+archive/ubuntu/firefox/+build/24173627) 	on 2022-07-15 [buildlog](https://code.launchpad.net/~costamagnagianfranco/+archive/ubuntu/firefox/+build/24173627/+files/buildlog_ubuntu-impish-amd64.boinc_7.22.0+dfsg+git20220715+r25160~r118~ubuntu21.10.1_BUILDING.txt.gz) (969.0 KiB)

**Comment by talregev** [comment]
Also you can check on discord my msgs.

**Comment by talregev** [comment]
@LocutusOfBorg Can you connect discord once a day?

**Comment by AenBleidd** [comment]
@talregev, some people just prefer old good email ;)

**Comment by RichardHaselgrove** [comment]
> Can you update upstream (not daily) to boinc 7.20.2?

boinc (7.20.2+dfsg+202207181724~ubuntu20.04.1) focal; urgency=low
* Auto build.

has appeared in my update manager for Linux Mint. I'll install it when I get a break (about an hour) - will report any problems then.

**Comment by Vulpine05** [comment]
> has appeared in my update manager for Linux Mint. I'll install it when I get a break (about an hour) - will report any problems then.

I updated my machines with Ubuntu 18.04 last night to 7.20.2, and they had wxWidgets 3.0.4.

**Comment by talregev** [comment]
wxwidgets 3.2.0 didn't build yet on Linux. The official Linux boinc is build against the most top update version per ubuntu version. for ubuntu 18.04 version is 3.0.4. Later versions they have 3.0.5.1.
I hope next version of ubuntu 22.10 will be with wxwidgets 3.2.0.

**Comment by RichardHaselgrove** [comment]
Linux Mint 20.3 'Una' (latest public release - per https://linuxmint.com/) has 3.0.4 too from PPA:

image

Simple view has the default skin working, but still drops out when returning to Advanced view - I don't think that's a blocker. More as it comes to light.

Screenshot at 2022-07-19 15-50-36

**Comment by talregev** [comment]
Thank you for report and the screen shot!
Can you switch a skin when you don't connect to the client.

> Simple view has the default skin working, but still drops out when returning to Advanced view

I think it similar the know issue that we have.
and if that it will solve when ubuntu/mint have wxwidgets 3.2.0.

**Comment by talregev** [comment]
Nice! Thank you for your check.

**Comment by AenBleidd** [comment]
> [Are we right to still have the IBM logo on those two?]

Actually, since they put their graphics into our repo, we're willing to use it as we want.
But it's a good question to Krembil folks. Maybe they would like to have it changed (if they ever decide to release their own build of BOINC Manager)

**Comment by RichardHaselgrove** [comment]
I've added a description of the problem and its causes to their website support thread: https://www.worldcommunitygrid.org/forums/wcg/viewthread_thread,44157

**Comment by LocutusOfBorg** [comment]
Hello, boinc is now using webview 3.2 since this version
<BTS> boinc 7.20.2+dfsg-3 uploaded by Gianfranco Costamagna (locutusofborg) https://tracker.debian.org/boinc

**Pull request merged**
