### PR TITLE
Fix gcc compile warnings, and fix code formatting

### PR DESCRIPTION
**Pull request by davidpanderson**

### CODE REVIEW

**Comment by AenBleidd** [comment]
I'll fix issues for Android and Mac build. I already know what is the reason of that and will provide a fix soon. All other changes looks good to me, so I'll merge it right after I have a fix

**Comment by davidpanderson** [comment]
I may have just fixed it

**Comment by AenBleidd** [comment]
Ok, let's wait for the build results

**Comment by AenBleidd** [comment]
But I believe the issue (also for Mac) is because we need to enable c++11 build by default

**Review by AenBleidd — APPROVED** [review]

**Comment by CharlieFenton** [comment]
> But I believe the issue (also for Mac) is because we need to enable c++11 build by default

I believe  c++11 is already the default on current versions of the Mac compiler

**Pull request merged**
