### PR TITLE
Fix cross-compile from ubuntu with mingw

### PR DESCRIPTION
**Pull request by renyidong**
I was cross compiling from ubuntu xenial with mingw for windows.
A few error occurred because current code failed to recognize mingw.
There might be better ways(that I don't know) to fix it.

### CODE REVIEW

**Comment by ChristianBeer** [comment]
Could you post which mingw packages (and versions) you have installed on Xenial? I would like to add a testcase to travis-ci which uses Precise (12.04LTS) to make sure mingw build changes don't break older versions of mingw.

**Comment by CharlieFenton** [comment]
The suggested change to lib/str_replace.h will cause major problems to Macintosh builds.

**Comment by CharlieFenton** [comment]
Sorry, I was mistaken. I ran some tests and found that the suggested changes do not cause any problems for Macintosh builds of BOINC.

**Comment by renyidong** [comment]
@ChristianBeer I'm not quite sure. Here is what grep found. Seems 4.0.0
```
_mingw_mac.h:#define __MINGW64_VERSION_MAJOR 4
_mingw_mac.h:#define __MINGW64_VERSION_MINOR 0
_mingw_mac.h:#define __MINGW64_VERSION_RC 0
_mingw_mac.h:#define __MINGW32_MAJOR_VERSION 3
_mingw_mac.h:#define __MINGW32_MINOR_VERSION 11
```

**Comment by renyidong** [comment]
@ChristianBeer Is this what you need? If testing for 16.04 is difficult for you, I'm very glad to use 12.04 instead. I'm using docker, so just a few lines to change.
```
dpkg -l | grep mingw
ii  binutils-mingw-w64-i686     2.26-3ubuntu1+6.6               amd64        Cross-binutils for Win32 (x86) using MinGW-w64
ii  binutils-mingw-w64-x86-64   2.26-3ubuntu1+6.6               amd64        Cross-binutils for Win64 (x64) using MinGW-w64
ii  g++-mingw-w64               5.3.1-8ubuntu3+17               all          GNU C++ compiler for MinGW-w64
ii  g++-mingw-w64-i686          5.3.1-8ubuntu3+17               amd64        GNU C++ compiler for MinGW-w64 targeting Win32
ii  g++-mingw-w64-x86-64        5.3.1-8ubuntu3+17               amd64        GNU C++ compiler for MinGW-w64 targeting Win64
ii  gcc-mingw-w64               5.3.1-8ubuntu3+17               all          GNU C compiler for MinGW-w64
ii  gcc-mingw-w64-base          5.3.1-8ubuntu3+17               amd64        GNU Compiler Collection for MinGW-w64 (base package)
ii  gcc-mingw-w64-i686          5.3.1-8ubuntu3+17               amd64        GNU C compiler for MinGW-w64 targeting Win32
ii  gcc-mingw-w64-x86-64        5.3.1-8ubuntu3+17               amd64        GNU C compiler for MinGW-w64 targeting Win64
ii  gfortran-mingw-w64          5.3.1-8ubuntu3+17               all          GNU Fortran compiler for MinGW-w64
ii  gfortran-mingw-w64-i686     5.3.1-8ubuntu3+17               amd64        GNU Fortran compiler for MinGW-w64 targeting Win32
ii  gfortran-mingw-w64-x86-64   5.3.1-8ubuntu3+17               amd64        GNU Fortran compiler for MinGW-w64 targeting Win64
ii  gnat-mingw-w64              5.3.1-3ubuntu1+16               all          GNU Ada compiler for MinGW-w64
ii  gnat-mingw-w64-base         5.3.1-3ubuntu1+16               amd64        GNU Ada compiler for MinGW-w64 (base package)
ii  gnat-mingw-w64-i686         5.3.1-3ubuntu1+16               amd64        GNU Ada compiler for MinGW-w64 targeting Win32
ii  gnat-mingw-w64-x86-64       5.3.1-3ubuntu1+16               amd64        GNU Ada compiler for MinGW-w64 targeting Win64
ii  mingw-w64                   4.0.4-2                         all          Development environment targeting 32- and 64-bit Windows
ii  mingw-w64-common            4.0.4-2                         all          Common files for Mingw-w64
ii  mingw-w64-i686-dev          4.0.4-2                         all          Development files for MinGW-w64 targeting Win32
ii  mingw-w64-x86-64-dev        4.0.4-2                         all          Development files for MinGW-w64 targeting Win64
```

**Comment by ChristianBeer** [comment]
I added a libs-mingw testcase to travis-ci and already verified your changes locally. Thanks for the list of packages that was what I was looking for. After #1793 gets merged I can restart the travis check for this PR and this time the check should pass.

**Comment by ChristianBeer** [comment]
Closing PR and reopening it to trigger a new Travis CI build with the new config from master.

**Comment by ChristianBeer** [comment]
Thanks for your contribution.

**Pull request merged**
