### PR TITLE
Add flatpack cross build

### PR DESCRIPTION
**Pull request by talregev**
Add flatpack cross build.

### CODE REVIEW

**Comment by AenBleidd** [comment]
BOINC is already listed on FlatHub, thus there is no need to add the same functionality here.
Please check these links:
- https://github.com/flathub/edu.berkeley.BOINC
- https://flathub.org/apps/details/edu.berkeley.BOINC

**Comment by talregev** [comment]
They use system lib not with vcpkg.

**Comment by AenBleidd** [comment]
> They use system libs not with vcpkg.

We're not supporting vcpkg exclusively, and integrators are willing to build it the way they want.
Also, there is no need to have two separate builds of the same product on FlatHub.

> Also, when we change stuff here, we don't know how it effect the flatpak build.

The build on Flatpak is very simple and clear. Please check the links I provided.

**Comment by AenBleidd** [comment]
@talregev,
Please before starting doing smth, check that this was not already resolved.
For example, ticket about flatpak was closed September 25 2022: https://github.com/BOINC/boinc/issues/2485
That means that there is no need to work on this topic further (at least without discussion with project maintainers first), because this will be just a waste of time.
If you think that Flatpak should be built with vcpkg instead of system libraries, you should contact Flatpak package maintainer directly and discuss this with them.
As I already wrote above, integrators could use any of the supported ways of building our product. Also, since vcpkg doesn't provide any valuable profit for end users of BOINC in this case, I see no reason to force its usage anywhere.
We are exclusively using vcpkg for Windows only, because otherwise it's almost impossible to build all dependencies manually.

So I have to ask you one more time: before working on any topic that has no open ticket - ask maintainers first. This way you'll save not only your time, but the time of maintainers as well.
And that fact that you already made this implementation doesn't give you any additional credits trying to convince me to accept smth that is not needed.

Thank you in advance.

**Pull request closed without merging**
