### PR TITLE
[Android] Fix android boinc crash on android 8.1 and above.

### LINKED ISSUE #3495: [Android] 7.16.5: BOINC instantly crashing on startup
**Describe the bug**
Just updated to the new version of BOINC on the Play Store. As soon as I open it, it crashes instantly. If I attempt to ignore the prompt and go to the Event Log, it will be empty. After a few seconds, the app will close itself.

**Steps To Reproduce**
1. Download the new BOINC update from the Play Store.
2. Open it, and wait about 5 seconds.

**Screenshots**
BOINC

**System Information**
 - OS: Android 9
 - BOINC Version: 7.16.5

**Additional context**
Restarted my phone, didn't fix the issue. Moto G6 Play running on Android 9 Pie. Didn't have this issue with the previous version of BOINC.

### PR DESCRIPTION
**Pull request by talregev**
Create an always on notification as it needed for foreground service.

Fixes #3495

**Description of the Change**

Create an always on notification as it needed for foreground service.

Take code from here:
https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1?noredirect=1&lq=1

### CODE REVIEW

**Comment by adamradocz** [comment]
Commit into master please.

**Comment by talregev** [comment]
I cannot do this. In master there is another issue that cover this fix and I cannot verify it like this.
@adamradocz Can you help in the other issue?

**Comment by AenBleidd** [comment]
This was done by intention. I asked to make this PR to release branch

**Comment by adamradocz** [comment]
Ohk, ok. I didn't know that.

**Comment by talregev** [comment]
@AenBleidd after the merge #3710 We can close this PR.

**Pull request closed without merging**
