### PR TITLE
Client, Win: Fix WSL-related crash

### PR DESCRIPTION
**Pull request by davidpanderson**
The client was crashing in cs_benchmark.cpp on the line
    bdp->host_info = host_info;
... in something involving copying WSL info.

I don't know why this was happening, but I fixed it by moving WSLS out of HOST_INFO.
It's probably better this way in any case.

### CODE REVIEW

**Comment by AenBleidd** [comment]
Linux client is failed to built with next error:
```
  CXX      boinc_client-acct_mgr.o
In file included from acct_mgr.cpp:41:0:
client_state.h:112:5: error: ‘WSLS’ does not name a type
     WSLS wsls;
     ^
```

**Comment by AenBleidd** [comment]
Also on Windows x86 client can't be built too because WSLS type is not defined, in `wslinfo.h` this struct is surrounded with `#ifdef _WIN64`

**Comment by AenBleidd** [comment]
Now it builds ok but due to unnecessary merge this PR contains a lot of unrelated commits.

**Comment by JuhaSointusalo** [comment]
@davidpanderson

Could you share the complete crash log? Oh, and please also upload debugging symbols to symbol store.

Since you don't know why the client crashed and you fixed it by shuffling some code around, you probably didn't really fix the crash, rather you moved it somewhere else.

> moving WSLS out of HOST_INFO.
> It's probably better this way in any case.

Why is it better to have WSL info in `CLIENT_STATE` instead of `HOST_INFO`? `HOST_INFO` stores information about host's capabilities so to me the logical place for info about WSL is indeed  in `HOST_INFO`.

**Pull request closed without merging**
