### PR TITLE
client: parse and store user and team name from account manager.

### PR DESCRIPTION
**Pull request by davidpanderson**
If the AM is "dynamic", show those for projects attached via AM,
rather than e.g. "Science United user 123456"

### CODE REVIEW

**Comment by JuhaSointusalo** [comment]
@davidpanderson

I think you opened the PR from wrong branch. The description of this PR and the changes in it don't seem to be related at all.

**Comment by TheAspens** [comment]
I've tested code as is and it works and they seem like reasonable changes.  However as per @JuhaSointusalo's  comment, the commit and pull request name and description don't match the code changes so I want to understand the mismatch.

**Comment by ChristianBeer** [comment]
I fixed Scrutinizer but I had to reset the CodeSniffer and selected some arbitrary tests I think are resembling our coding style.

**Comment by davidpanderson** [comment]
D'oh!  My bad.  Will do new PR

**Pull request closed without merging**
