### PR TITLE
Add an opportunity to check if docker/docker compose is installed on …

### PR DESCRIPTION
**Pull request by Tanya1515**
Pull request for [issue 5617](https://github.com/BOINC/boinc/issues/5617)

### CODE REVIEW

**Comment by AenBleidd** [comment]
@Tanya1515, thank you for your PR.
Before we can start review, test and discuss this approach, please fix the falling CI flows.
Thank you in advance.

**Comment by Tanya1515** [comment]
@AenBleidd I have improved my code (all misprints and whitespaces are fixed). However, CI flows are failed on test covering. All files, that i have modified, don't have test covering at all. What should i do with the error? 

Thank you in advance.

**Comment by AenBleidd** [comment]
@Tanya1515, code coverage is not important and can be ignored.
I'll take a look at the code at the beginning of the next week.
Thank you for your PR!

**Comment by Tanya1515** [comment]
@AenBleidd, have you  taken  look at the code/my issue[https://github.com/BOINC/boinc/issues/5617]?

Thank you in advance.

**Comment by AenBleidd** [comment]
Hello @Tanya1515, sorry for the delay. We were busy releasing a new version of BOINC. I plan to review and test your PR during next couple of weeks.

**Comment by AenBleidd** [comment]
Closing this in favor of #5757 that contains a better approach of docker detection.

**Pull request closed without merging**
