### PR TITLE
[WIP] Mac: Changes to allow building under Xcode 10

### PR DESCRIPTION
**Pull request by CharlieFenton**
BOINC built with Xcode 10 requires at least OS 10.7 (earlier versions worked under OS 10.6.)

### CODE REVIEW

**Comment by CharlieFenton** [comment]
With these changes, BOINC can still be built with earlier versions of Xcode, but will still require OS 10.7 to run because it links with libc++ instead of libstdc++.

**Comment by AenBleidd** [comment]
@CharlieFenton, currently CI build is failed with next error:

```
▸ Compiling cs_statefile.cpp
❌  /Users/travis/build/BOINC/boinc/client/cs_statefile.cpp:28:10: 'mac_spawn.h' file not found
#include "mac_spawn.h"
         ^~~~~~~~~~~~~
▸ Compiling cs_trickle.cpp
** BUILD FAILED **
```

Is this is issue with out-of-date MacOS image used on Travis CI?

**Comment by CharlieFenton** [comment]
` ❌  /Users/travis/build/BOINC/boinc/client/cs_statefile.cpp:28:10: 'mac_spawn.h' file not found`

This error makes no sense; the file is in the search path and the build works on my Mac. I made a couple of changes to see if they solve this, and now there is a new error:
`/Users/travis/build/BOINC/boinc/client/main.cpp:63:10: 'idlemon.h' file not found`

@ChristianBeer can you help with this?
(Please note my comment at https://github.com/BOINC/boinc/pull/2720#issuecomment-429280224. I was expecting link errors with wxWidgets, but these file not found errors make no sense to me.)

**Comment by CharlieFenton** [comment]
I have finally succeeded in eliminating the _File not found_ errors from Travis CI. As explained in https://github.com/BOINC/boinc/pull/2720#issuecomment-429280224, I expected the linker errors. Travis-CI will need to rebuild the wxWidgets library for the Mac using the buildWxMac.sh script in this PR. Note that the builds of wxWidgets will need to be different for this branch (or for master after this is merged) than for the 7.14 branch and earlier.

Please **DO NOT MERGE** this PR. I will create a new cleaner branch and a new PR for merging into master.

**Comment by ChristianBeer** [comment]
You can force a rebuild of the PR cache by adding `--clean` to the call to `3rdParty/buildMacDependencies.sh` in `.travis.yml`. Before the PR is merged you just need to reverse this commit. I'm going to clean the cache for the master branch myself once the PR is merged.

**Pull request closed without merging**
