### PR TITLE
Initial commit of rpc documentation

### PR DESCRIPTION
**Pull request by nikolasgianna**
This is an attempt at documenting the RPC interface. Both requests and expected replies.

### CODE REVIEW

**Comment by AenBleidd** [comment]
@nikolasgianna, I can create unit tests (with Google Test Framework) according to this documentation.
This can help us to find issues both in documentation and in current implementation of XML parser.
Also I had plans to move all XML related operations to libxml++ (or smth similar) so these unit tests can be also a very useful tool to check new parsing mechanism.
@ChristianBeer, @davidpanderson, @JuhaSointusalo, @CharlieFenton, @TheAspens:
What do you think?
Thanks

**Comment by JuhaSointusalo** [comment]
@nikolasgianna

Thanks for writing the documentation. We have other documentation in [Trac wiki](http://boinc.berkeley.edu/trac/wiki). I think this should go there so that everything is in one place.

@AenBleidd

BOINC certainly needs automated testing. Rather than hijacking this PR I think it would be better to open a new issue to discuss the subject. What tools we would use and how the testing would be implemented. There is a million different testing frameworks so having some kind of comparison of some number of popular frameworks would be nice.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, of course, I'l create new ticket. I'm just curious whether unit testing is needed

**Comment by JuhaSointusalo** [comment]
@AenBleidd Well, in my opinion, yes, BOINC needs unit tests as well as higher level tests. I think there has been some mentions now and then about wanting to plug testing into CI process.

**Comment by lfield** [comment]
@JuhaSointusalo I would recommend that this documentation resides in git and not Trac. Any changes to the RPC should also include updates to the documentation.

@AenBleidd I think that tests would be very welcome. If we can document and automatically test the main interfaces of BOINC, it would help everyone. 

As this is new documentation, I see no reason not to merge it. Any mistakes can easily be updated.

**Comment by lfield** [comment]
Any reason why this new documentation hasn't been merged?

**Comment by TheAspens** [comment]
First of all - thank you for the detailed documentation.  It will be useful.

The technical documentation  for BOINC has up to this point always been on the trac wiki.  For an example similar to what you have documented are this page: https://boinc.berkeley.edu/trac/wiki/WebRpc

Maintaining the documentation in two places is inconsistent and makes it more difficult to maintain and find information or to know where to add things.  If you are interested in changing the standard existing standard for where the documentation is maintained, I would suggest starting a discussion on the boinc-dev mailing list and getting a consensus of the committers to agree with the change in direction.  

Also - moving all of the technical documentation into top level md files might not be sufficient to contain all of the documentation without it becoming quite disorganized.  I would suggest that a more expansive proposal of how we should maintain the technical documentation within git would be better.

In the meantime, would you object to me adding your content to to the trac wiki?

**Comment by lfield** [comment]
No, I don't mind you adding the content to the trac wiki. My recommendation would be to have such specifications in git so that they can be maintained in sync with the code. It ensures that the specification agrees with the code historically and on branches.

**Comment by lfield** [comment]
@TheAspens are you going to add this to the wiki?

**Comment by lfield** [comment]
The trac wiki has been updated. 

https://boinc.berkeley.edu/trac/wiki/GuiRpcProtocol

**Pull request closed without merging**
