### PR TITLE
server: add script for purging retired batches

### PR DESCRIPTION
**Pull request by davidpanderson**

### CODE REVIEW

**Comment by lfield** [comment]
I was expecting this to be fixed in the `db_purge `script. How come it is separated?

**Comment by davidpanderson** [comment]
Easier to do it in PHP

**Comment by lfield** [comment]
Even if it is a bit harder, I think this should be done in the `db_purge` script. I will provide an alternative PR.

**Comment by TheAspens** [comment]
This was implemented by pull request #3148.  I recommend that we close this pull request since it has been implemented there.

**Pull request closed without merging**
