### PR TITLE
[Client] [WSL] Extend detection.

### PR DESCRIPTION
**Pull request by AenBleidd**
Move WSL detection to get_host_info().
Enumerate available WSLs from registry.
Add wslapi library loading.
Add support of multiple installed wsl distros detection.
Detect only installed and configured distros.
Add extra information parse.
Add wslinfo files to save and parse wsl info.
Add dont_use_wsl param to cc_config.
Add missed hostinfo_wsl.cpp when building win client using gcc.
Fix small issues.
Small refactoring.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@davidpanderson, @ChristianBeer, @RichardHaselgrove, @JuhaSointusalo, @TheAspens 
Guys, I encourage you to review this. I understand, that this is quite a big piece of code. But there was no way for me to make it less without losing some functionality :)

**Comment by JuhaSointusalo** [comment]
It seems that you are setting XML tag name from distro name. That's interesting idea but possibly bad one if you ever want to process the XML with something other than BOINC's XML parser. I would have the distro name in it's own element, say `distro_name`, and a constant name for the enclosing element, like `distro` or something.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, ok, I'll fix this

**Comment by AenBleidd** [comment]
Fixed

**Comment by davidpanderson** [comment]
This all looks fine to me, though I'm unable to test it.

**Comment by AenBleidd** [comment]
wslconfig output:
image
boinc output:
image
client_state.xml:
image

**Comment by davidpanderson** [comment]
Looks good.  I'll merge.  Thanks for doing this.

**Comment by RichardHaselgrove** [comment]
@AenBleidd: small bug

Running the WSL-enabled client under Windows 7, so no WSL available and none detected - all good.

Client writes extra line into cc_config.xml
`        <dont_use_wsl>0</dont_use_wsl>`
but on reading config files after setting Event Log options or from menu, Event Log reports
`29/06/2018 15:59:47 |  | Unrecognized tag in cc_config.xml: <dont_use_wsl>`

**Pull request merged**
