### PR TITLE
Android studio support

### PR DESCRIPTION
**Pull request by denravonska**
I have imported the project into Android Studio, upped the target SDK and fixed the problems that arose. The ARM asset client doesn't compile due to #1702. Adding the fix proposed by the compiler allows you to compile, but I have limited ways of testing it which is why I didn't include it here.

The app starts and behaves correctly in Swedish.

### CODE REVIEW

**Comment by ChristianBeer** [comment]
Thanks for looking into this. What else does the increased SDK version imply? Do we exclude older devices that way?

I just did a cursory inspection of your commits. The ones that stand out are related to the translation system. The way the BOINC translation system is set up is that you shouldn't edit the translations directly but update them on [transifex](https://www.transifex.com/boinc/boinc/dashboard/). Whenever a resource is 100% translated into a non-english language the file gets transfered into the github repository automatically, overwriting your changes in f2c3963a91. If you don't want to create an account there just tell me so I can manually copy the translations over.

The string you are adding in 3de9867aa was deliberately removed in 79aca0feb71 so if there is a reference to it this must be updated to use the new string.

**Comment by denravonska** [comment]
We still target API 16 (Jelly Bean) but in order to build with newer features I had to bump the compile SDK to 23. Actually, I just did a quick search and the TV features requires API level 21, not 23, so it should've worked for me without changing this. I'll double check it tomorrow.

Regarding the automatic translation merge it will be a problem since the translations have been moved from `res/` to `app/src/main/res/` so I guess there will be a conflict there, right?

I wasn't aware about transifex. I'll add my translation modifications there instead. Thanks :)

**Comment by ChristianBeer** [comment]
> Regarding the automatic translation merge it will be a problem since the translations have been moved from res/ to app/src/main/res/ so I guess there will be a conflict there, right?

Yes, that change needs to be coordinated with a corresponding change to the transifex-github bridge that we have running on a separate server.

**Comment by brierjon** [comment]
This commit will allow us to close #1570

**Comment by davidpanderson** [comment]
Should I go ahead and merge this?

**Comment by denravonska** [comment]
I have been playing around with it when fiddling with TCP support and it seems to work both for building and debugging. I haven't tested signing a release but I guess the CI server can test that from this branch, right? The only issue will be the translations and the path change.

Also, someone should have a look at #1702 since it blocks the BOINC ARM build for Android.

**Comment by ChristianBeer** [comment]
We should make sure this really works and built a Client ourselves before merging into master. We should also make a documented review of the code changes. I mean no offense to @denravonska but it's easy to sneak in a malicious change with this many changes and I would like to avoid that with code coming from a new contributor.

We should also discuss on how to proceed with the required changes to the translation system and what our options are to get it working again.

**Comment by denravonska** [comment]
@brierjon True, fixed.

**Comment by AenBleidd** [comment]
@denravonska Is this pull request finished and can be merged?
@brierjon, @ChristianBeer Could you please review this pull request? There was no commits during the last month related to this PR. 
Thanks

**Comment by davidpanderson** [comment]
I merged this just to keep things moving.  Has the  Neon/VFP benchmark issue been fixed?

**Comment by denravonska** [comment]
@davidpandersson I have tried the suggested fix and it does build, but I am unable to verify due to lack of hardware.

**Pull request merged**
