### PR TITLE
[CI] Simplify vcpkg custom triplets

### PR DESCRIPTION
**Pull request by AenBleidd**

### CODE REVIEW

**Comment by AenBleidd** [comment]
@talregev, would be nice if you could review this PR.
Thank you in advance.

**Comment by AenBleidd** [comment]
Linux integration test is expected to fail, so please ignore it

**Comment by talregev** [comment]
It would be nice if you can test osx PR I did.

**Comment by AenBleidd** [comment]
> It would be nice if you can test osx PR I did. 

Please read carefully my response to that PR: https://github.com/BOINC/boinc/pull/5103#issuecomment-1469048300

**Comment by talregev** [comment]
I will not reach you on Discord. You are not here for cooperation. You are here for block things, and if I insist, you will falsify me for  everything for that. 
You should change your attitude to me. other wise you will maintain boinc alone.

**Pull request merged**
