### PR TITLE
[Android] test openssl 3.0.3 android client

### PR DESCRIPTION
**Pull request by talregev**
test openssl 3.0.3 android client.

### CODE REVIEW

**Comment by talregev** [comment]
openssl 3.0.3 doesn't work for android. We will wait for official fix.

**Comment by AenBleidd** [comment]
It is required to fix the port by providing an additional configure parameter. I'll fix it in two weeks

**Comment by talregev** [comment]
Will you fix it on vcpkg?

**Comment by AenBleidd** [comment]
Yes

**Comment by talregev** [comment]
> Yes

Thank you

**Comment by AenBleidd** [comment]
@talregev, I believe you mentioned several times that I never do any vcpkg port changes that are never pushed to upstream (only in case this is needed for testing or while waiting for approval on upstream).

**Pull request closed without merging**
