### PR TITLE
Add test class for md5 library using Google test suite.

### PR DESCRIPTION
**Pull request by hectorespert**
Fixes #

**Description of the Change**

Add test class for md5 library.

Copy md5 filte test program code from `lib/md5_test.cpp` to `tests/unit-tests/lib/test_md5_file.cpp` and run it as a unit test.

**Alternate Designs**

**Release Notes**

### CODE REVIEW

**Comment by AenBleidd** [comment]
@hectorespert, there are failed unit tests on Windows, please take a look

**Comment by hectorespert** [comment]
> @hectorespert, there are failed unit tests on Windows, please take a look

I configured test `md5_file` to run only in Linux. I can't run it on windows to find the issue.

**Comment by AenBleidd** [comment]
I'll take a look and add these tests to Windows then. Will keep it open for now

**Comment by AenBleidd** [comment]
Unit-tests for WIndows are fixed in #4277. Closing this as a duplicate

**Pull request closed without merging**
