### PR TITLE
[CI] Linux: checkout two commits for codecov to work

### PR DESCRIPTION
**Pull request by ChristianBeer**
**Description of the Change**
checkout two commits for codecov to work

**Alternate Designs**
None

**Release Notes**
N/A

### CODE REVIEW

**Comment by AenBleidd** [comment]
Fix for Windows build is published: https://github.com/microsoft/vcpkg/pull/16154

**Comment by ChristianBeer** [comment]
I'm not sure how the Windows wxWidgets fix is relevant for this change? Did you mean to post this to another PR or issue?

As for this PR it seems that the changes fix the codecov script so that it now can determine the merge SHA and correctly merge the reports on the website. That's something I want to check before removing the WIP.

**Comment by AenBleidd** [comment]
I wrote this to tell that build error is because of wxWidgets, and not relevant to this PR

**Comment by ChristianBeer** [comment]
This reminds me that we need to upload the coverage info from windows too. It might be best to use the [action](https://github.com/codecov/codecov-action) for this. But the coverage files need to be generated by the compiler. I'm note sure how to do this with Visual Studio. But this should go into a separate PR.

**Comment by AenBleidd** [comment]
> I'm note sure how to do this with Visual Studio. But this should go into a separate PR.

I'll handle this

**Review by AenBleidd — APPROVED** [review]

**Pull request merged**
