### PR TITLE
[osx][vcpkg] Bugfix osx vcpkg dependencies

### PR DESCRIPTION
**Pull request by talregev**
Bugfix osx vcpkg dependencies.

### CODE REVIEW

**Comment by AenBleidd** [comment]
This issue will be fixed in https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230219.1
so we can just wait for the deployment and do not add a temporary solution since we have no urgency

**Comment by talregev** [comment]
> This issue will be fixed in https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230219.1 so we can just wait for the deployment and do not add a temporary solution since we have no urgency

I think if the image will be with this dependency, we should put it in our ci for knowledge. images can change many times.

**Comment by AenBleidd** [comment]
This was a defect in their image release. No need to put this into our ci scripts even for our knowledge because this adds redundant complexity

**Comment by talregev** [comment]
> This was a defect in their image release. No need to put this into our ci scripts even for our knowledge because this adds redundant complexity

I don't agree.

**Pull request closed without merging**
