### PR TITLE
[OSX] Move get command exit code from eval string.

### LINKED ISSUE #4612: OSX CI build failed but shown as 'passed'
CI build Is failed with the next error:

```
Linking boinc
ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:

	Ld /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/BOINC_Client.build/Objects-normal/x86_64/Binary/boinc normal x86_64

(1 failure)
```

https://github.com/BOINC/boinc/runs/4912711265?check_suite_focus=true

But build script ignores this.

@CharlieFenton, could you please take a look and fix both script and build?

Thanks in advance.

### PR DESCRIPTION
**Pull request by AenBleidd**
This fixes #4612.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by CharlieFenton** [comment]
@AenBleidd Why are you changing this? This script is not  used by CI; CI uses buildMacBOINC-CI.sh, so this file is not the reason the CI builds are not showing build failures.

**Comment by CharlieFenton** [comment]
My mistake; I now see that buildMacBOINC-CI.sh calls buildMacBOINC.sh. I will test it.

**Comment by AenBleidd** [comment]
@CharlieFenton, this script is called from the `buildMacBOINC-CI.sh` script.
And I checked, that this doesn't work on CI because we do 
```
source BuildMacBOINC.sh ${config} -noclean -target ${target} | tee xcodebuild_${target}.log | $beautifier; retval=${PIPESTATUS[0]}
```
And when in this script there is `eval` with `result=$?` **inside** this `eval`, `result` value is never reported as non-zero.

**Comment by AenBleidd** [comment]
> My mistake; I now see that buildMacBOINC-CI.sh calls buildMacBOINC.sh. I will test it.

No problem :)

**Review by CharlieFenton — APPROVED** [review]
Works correctly on my Mac under zsh. Please remember to update the copyright year in line 5. Also, I would appreciate it if you would add a description of your change to the edit history after line 37.

**Pull request merged**
