### PR TITLE
[WIP] Mac: Update Xcode project to build everything 64-bit, in preparation …

### PR DESCRIPTION
**Pull request by CharlieFenton**
Apple has announced that they will remove full support for 32-bit applications in OS 10.14. The changes in this PR modify the Xcode project to build everything as 64-bit executables, and update Mac-specific source code to fix any problems which result from building as 64-bit. 

For now, the BOINC libraries will still be built as Universal (32-bit and 64-bit) binaries, to allow projects to continue building either 32-bit or 64-bit executables until they have finished converting to all 64-bit code.

### CODE REVIEW

**Comment by CharlieFenton** [comment]
GitHub keeps insisting that my commit for mac_build/BuildMacBOINC.sh has 2 conflicts, but the file as i committed it is correct; i added one comment line, added one line of code and removed several consecutive obsolete lines of code. I've tried resolving the conflict by editing it back to my original commit via GITHub's web editor and clicking on "Mark as resolved" but it keeps claiming the same 2 changes are conflicts. How do I fix this?

**Comment by CharlieFenton** [comment]
Note that the dependent static libraries wxWidgets 3.0.0 (libwx_osx_cocoa_static.a) and sqlite-3.11.0 (libsqlite3.a) must be rebuilt as 64-bit libraries. I have modified the build scripts buildWxMac.sh and buildsqlite3.sh in this feature branch to build these two libraries as "universal binaries" containing both 32-bit and 64-bit versions in the same library file. This will allow both the old and the new Xcode projects to build BOINC Manager. But the CI builds will fail until the dependent libraries have been updated.

**Comment by ChristianBeer** [comment]
The best way to resolve this kind of conflict is to rebase this feature branch which tries to apply all commits to the new head of the master branch. The conflicting commit will fail and you can manually adjust the changes and make a new commit.

The conflicting commit is d20c33830b2f28adbd7bc2c1e4ca12592b5944a2 which contains the same changes (among others) as done in 1dabbb7a654eac5d5921a133b99b955361eea372 which is already in master. Since both commits change the same lines this is seen as  a conflict, as both commits can not be merged automatically.

**Comment by AenBleidd** [comment]
@CharlieFenton, Travis fails trying to build for Mac. Is this an issue with Travis? Can this be fixed? Thanks

**Comment by CharlieFenton** [comment]
@AenBleidd: As I wrote in an earlier comment above, the Travis CI builds will fail until 2 dependent libraries have been rebuilt as 64-bit libraries. But updating the libraries requires the build scripts that are part of this PR. Normally, this PR won't be approved for merging until the Travis CI build succeeds. So we have something of an infinite loop here.

**Comment by AenBleidd** [comment]
@CharlieFenton, sorry for disturbing you. I missed your comment for some reason. Thank you

**Comment by ChristianBeer** [comment]
@CharlieFenton now you seem to have merged master into this branch which duplicated a lot of commits. The conflict (which is real not erroneously) can not be resolved by adding more commits, only by changing the conflicting commit in the feature branch.

The CI builds will work once the conflict is properly resolved and I can clean the cache so that the libraries are rebuilt from scratch so there is no infinite loop once the PR is clean again.

**Comment by ChristianBeer** [comment]
@CharlieFenton Do you still have the list of commits that were originally in this PR? I can help you to recreate the original feature branch based on current master which will also eliminate the conflict.

**Comment by JuhaSointusalo** [comment]
@ChristianBeer From email:

Mac: Update Xcode project to build everything 64-bit, in preparation for future removal of 32-bit support in OS 10.14.
b04aa18 Manager: Fixes to allow building 64-bit application on Macintosh.
b0088e0 Mac installer: Fixes to allow building 64-bit application on Macintosh.
7b31b10 Manager: Fixes to allow building 64-bit application on Macintosh.
77b9a6b Mac: Update build scripts to build Manager dependencies wxWidgets and SQLite as 64-bit libraries (temporarily build both 32-bit and 64-bit libraries for backward compatibility)
182d22f Manager: Fixes to allow building 64-bit application on Macintosh.
d20c338 Mac: Update installer build script to eliminate unnecessary special handling of screensaver build which is no longer needed
2fdab25 Mac: Update installer build script to get boinc_logo_black.jpg from a different path because it is no long in the doc directory.
c00f960 Manager: Fixes to allow building 64-bit application on Macintosh.

The first email didn't include commit id. I left out the commit that tried to work around the conflict and the commit that reverted the workaround.

**Comment by tristanolive** [comment]
In case it's helpful to visualize what is happening, have a look at the [branch graph](https://github.com/BOINC/boinc/network) (click and drag to view). The mac_all_64-bit branch was originally created from commit d0367d7, but then was merged into a new branch based on f0c38d5, which itself had already duplicated all of the mac_all_64-bit commits. 

It's a bit confusing... I'm wondering what exactly went wrong. Was it a "git merge master" from the mac branch, or a rebase? I'd guess the latter, due to the duplicate commits. I actually thought github did not allow rebasing, i.e. once a pull request is made, a rebase is no longer possible.

**Comment by ChristianBeer** [comment]
The graph looks indeed different from what I would expect from a merge but also from a rebase. Maybe a rebase in the wrong direction?

Since the mac branch is not protected a rebase is possible and needed in this case were there was a conflict with the target branch of the pull request. A proper rebase would move the branch-off point from d0367d7 to  f0c38d5 and not create a second branch-off point.

**Comment by ChristianBeer** [comment]
It was easier than I expected. The graph helped me finding the correct point where the rebase was needed. Here is what I did:
```
git checkout master
git pull
git checkout c00f960ca5ed077be9c7026acfdf7d923fc056d6
git checkout -b mac_all_64-bit_fixed
git rebase master
# a conflict was found and I had to manually edit mac_build/BuildMacBOINC.sh
git add mac_build/BuildMacBOINC.sh
git rebase --continue
git push --set-upstream origin mac_all_64-bit_fixed
```
This branch now only contains Charlies 9 commits and is branched off from current master. The previously conflicting commit d20c338 is now 0d4b868. All other commits also changed the SHA1 because it was a proper rebase.

**Comment by ChristianBeer** [comment]
I also just checked the Travis build Log for Mac and it seems it is trying to rebuild the cache but it is taking too long (>45 min) and we run into a timeout. I guess the double build of 32 and 64bit libraries just pushed us over the edge. Let's see what happens with the fixed Branch.
@CharlieFenton feel free to create a new PR with the mac_all_64-bit_fixed branched I pushed.

**Comment by CharlieFenton** [comment]
@ChristianBeer: Thank you for cleaning up the mess I apparently made (though i was not aware of it.) Despite having been a software engineer for 50 years, I find GIT very confusing with a steep learning curve. I didn't know what a "rebase" was before last night, and tried to figure out how to do it using SourceTree, so I may have inadvertently done a reverse rebase or merge. I finally did it using a combination of the command line and SourceTree after reading the git-rebase man page. 

I tried setting my current directory to my local repository with origin/mac_all_64-bit checked out and then doing "git rebase master" but GIT simply  replied "Current branch mac_all_64-bit is up to date." I then tried "git rebase master mac_all_64-bit" and got a similar response along with that I was already on that branch.  Finally I tried "git rebase origin/master" and that apparently worked, with just the one conflict which I was able to fix and do "git rebase --continue". After that, GitHub reported that there were no conflicts, so I though all was well and went to bed, having been up all night wrestling with this.

Again, thank you for your help and I will close this PR and soon create a new one.

**Pull request closed without merging**
