### PR TITLE
Re-enable work buffering in the presence of max concurrent constraints.

### PR DESCRIPTION
**Pull request by davidpanderson**
See https://boinc.berkeley.edu/trac/wiki/WorkFetchMaxConcurrent

### CODE REVIEW

**Comment by RichardHaselgrove** [comment]
Thanks David. I'll give it a test, and alert the other testers.

**Comment by RichardHaselgrove** [comment]
I said in the conference call that I'd run more tests. That seems to have shown up a problem. Client log file attached.

Log starts at 29-Mar-2019 12:05:36, which is when I deployed the artifact for this PR / test. All worked as expected all week.

Read from 05-Apr-2019 17:54:02: Test starts at 05-Apr-2019 18:06:57

At 17:54, NumberFields reported three completed tasks and fetched one new task - normal.

At 18:06 I read in a changed config: max_concurrent for NumberFields reduced from 3 (pre-existing) to 2. The client pre-empted one task, as expected, but immediately fetched more work. Unexpected. After a second work fetch at 18:08:06, I enabled work_fetch_debug, and you can see the repeated fetches every minute until I truncated the experiment at 05-Apr-2019 18:30:44 by resetting max_concurrent to 3. 22 new tasks (88 hours estimated) were fetched in all.

This is a mode of behaviour which I have observed in the past with Einstein@Home, but never been able to capture before in a detailed log (on previous occasions, setting a new log flag has stopped the problematic work fetches). The only feature the two projects have in common so far as I can see is that they both currently set a 60 second RPC delay - could that interact with the 60 second work fetch polling loop?

The files concurrent with this event log have been uploaded to Scenario 172, Simulation 0

[Client log for #3076 work fetch.zip](https://github.com/BOINC/boinc/files/3049116/Client.log.for.3076.work.fetch.zip)

**Comment by davidpanderson** [comment]
Does the problem show up in the simulation?

**Comment by RichardHaselgrove** [comment]
The simulator says

> 01:00:00 [NumberFields@home] [work_fetch] REC 2832.337 prio -0.019 can't request work: at max_concurrent limit

which is the old problem. Does the simulator have this new code yet?

**Comment by davidpanderson** [comment]
I committed a possible fix.  The emulator now has this version.

**Comment by RichardHaselgrove** [comment]
I've popped in win-client_PR3076_2019-04-05_4dce65a9.7z, and re-established the max_concurrent=2

No sign of any unexpected work fetches yet, but I'm a bit worried by

> 05/04/2019 23:02:47 |  | [work_fetch] ------- start work fetch state -------
> 05/04/2019 23:02:47 |  | [work_fetch] target work buffer: 21600.00 + 4320.00 sec
> 05/04/2019 23:02:47 |  | [work_fetch] --- state for CPU ---
> 05/04/2019 23:02:47 |  | [work_fetch] shortfall 11909.66 nidle 0.40 saturated 23220.22 busy 0.00

when I still have those 88 hours of extra work downloaded earlier this evening. It's gone 11pm on a Friday night: pulling down the shutters for now.

**Comment by davidpanderson** [comment]
There's a shortfall because the 88 hours of work are for a project with MC limits

**Comment by RichardHaselgrove** [comment]
After a night's sleep and a walk in the spring sunshine, that looks eminently reasonable. There was a genuine shortfall and an idle core: work would have been fetched from an alternative project if permitted, I'm sure. Nothing new to report, but with SETI down hard and a new app_version from NumberFields, I'll wait for things to settle down before further testing.

**Comment by RichardHaselgrove** [comment]
Other machines now seem to be fetching work from SETI, but this one isn't. Key lines seem to be

```
07/04/2019 18:44:37 |  | [work_fetch] --- state for NVIDIA GPU ---
07/04/2019 18:44:37 |  | [work_fetch] shortfall 25920.00 nidle 1.00 saturated 0.00 busy 0.00
```
(correct - one GPU is idle)
```
07/04/2019 18:44:37 | SETI@home | checking NVIDIA GPU
07/04/2019 18:44:37 | SETI@home | [work_fetch] using MC shortfall 0.000000 instead of shortfall 25919.999999
07/04/2019 18:44:37 | SETI@home | [work_fetch] set_request() for NVIDIA GPU: ninst 2 nused_total 0.00 nidle_now 1.00 fetch share 1.00 req_inst 0.00 req_secs 0.00
```
(wrong - SETI is completely dry of work and can't be anywhere near MC, even though there is an MC=4 set)

Full workfetch log 
[MC shortfall.txt](https://github.com/BOINC/boinc/files/3051876/MC.shortfall.txt)

**Comment by RichardHaselgrove** [comment]
I've re-confirmed the previous observation by allowing the work cache to run down to zero during the day.

With max_concurrent set:
```
08/04/2019 15:47:08 |  | [work_fetch] target work buffer: 21600.00 + 4320.00 sec
08/04/2019 15:47:08 | SETI@home | [work_fetch] REC 261170.762 prio -1.937 can request work
08/04/2019 15:47:08 |  | [work_fetch] --- state for NVIDIA GPU ---
08/04/2019 15:47:08 |  | [work_fetch] shortfall 41133.60 nidle 1.00 saturated 0.00 busy 0.00
08/04/2019 15:47:08 | SETI@home | [work_fetch] share 1.000
08/04/2019 15:47:08 | SETI@home | NVIDIA GPU needs work - excluded instance starved
08/04/2019 15:47:08 | SETI@home | [work_fetch] using MC shortfall 0.000000 instead of shortfall 41133.603897
08/04/2019 15:47:08 | SETI@home | [work_fetch] set_request() for NVIDIA GPU: ninst 2 nused_total 0.00 nidle_now 1.00 fetch share 1.00 req_inst 0.00 req_secs 0.00
08/04/2019 15:47:08 | SETI@home | NVIDIA GPU set_request: 0.000000
08/04/2019 15:47:08 |  | [work_fetch] No project chosen for work fetch
```
A few seconds later, with max_concurrent removed:
```
08/04/2019 15:48:15 |  | [work_fetch] target work buffer: 21600.00 + 4320.00 sec
08/04/2019 15:48:15 | SETI@home | [work_fetch] REC 261015.156 prio -1.937 can request work
08/04/2019 15:48:15 |  | [work_fetch] --- state for NVIDIA GPU ---
08/04/2019 15:48:15 |  | [work_fetch] shortfall 41194.72 nidle 1.00 saturated 0.00 busy 0.00
08/04/2019 15:48:15 | SETI@home | [work_fetch] share 1.000
08/04/2019 15:48:15 | SETI@home | NVIDIA GPU needs work - buffer low
08/04/2019 15:48:15 | SETI@home | [work_fetch] set_request() for NVIDIA GPU: ninst 2 nused_total 0.00 nidle_now 1.00 fetch share 1.00 req_inst 2.00 req_secs 41194.72
08/04/2019 15:48:15 | SETI@home | NVIDIA GPU set_request: 41194.717952
08/04/2019 15:48:15 | SETI@home | [work_fetch] request: CPU (0.00 sec, 0.00 inst) NVIDIA GPU (41194.72 sec, 2.00 inst) Intel GPU (0.00 sec, 0.00 inst)
```
We need to distinguish between resources idle because of deliberate configuration choices, and idle because of work supply failure.

**Comment by davidpanderson** [comment]
Please create an emulator scenario.  It's very difficult for me to debug sched stuff without this.

**Comment by RichardHaselgrove** [comment]
It will take time, because today was Tuesday and I over-cached in case of server crashes. I'll see if I can make it fail tomorrow with another project, and create a scenario if I can.

**Comment by RichardHaselgrove** [comment]
OK, created scenario 173, simulation 0

https://boinc.berkeley.edu/sim_web.php?action=show_simulation&scen=173&sim=0

NumberFields is dry, cores are idle, NF can fetch but won't.

17/04/2019 09:43:32 |  | [work_fetch] Request work fetch: Core client configuration
17/04/2019 09:43:33 |  | choose_project(): 1555490613.358389
17/04/2019 09:43:33 |  | [work_fetch] ------- start work fetch state -------
17/04/2019 09:43:33 |  | [work_fetch] target work buffer: 4320.00 + 4320.00 sec
17/04/2019 09:43:33 |  | [work_fetch] --- project states ---
17/04/2019 09:43:33 | Einstein@Home | [work_fetch] REC 8519.479 prio -2.243 can request work
17/04/2019 09:43:33 | GPUGRID | [work_fetch] REC 321884.152 prio -25.195 can't request work: "no new tasks" requested via Manager
17/04/2019 09:43:33 | NumberFields@home | [work_fetch] REC 2898.385 prio -0.381 can request work
17/04/2019 09:43:33 | SETI@home | [work_fetch] REC 342005.551 prio -138.531 can't request work: "no new tasks" requested via Manager (115.14 sec)
17/04/2019 09:43:33 | SETI@home Beta Test | [work_fetch] REC 0.000 prio -0.000 can't request work: "no new tasks" requested via Manager
17/04/2019 09:43:33 |  | [work_fetch] --- state for CPU ---
17/04/2019 09:43:33 |  | [work_fetch] shortfall 21244.97 nidle 2.40 saturated 0.00 busy 0.00
17/04/2019 09:43:33 | Einstein@Home | [work_fetch] share 0.000 blocked by project preferences
17/04/2019 09:43:33 | GPUGRID | [work_fetch] share 0.000 blocked by project preferences
17/04/2019 09:43:33 | NumberFields@home | [work_fetch] share 1.000
17/04/2019 09:43:33 | SETI@home | [work_fetch] share 0.000 blocked by project preferences
17/04/2019 09:43:33 | SETI@home Beta Test | [work_fetch] share 0.000 blocked by project preferences
17/04/2019 09:43:33 |  | [work_fetch] --- state for NVIDIA GPU ---
17/04/2019 09:43:33 |  | [work_fetch] shortfall 0.00 nidle 0.00 saturated 76603.12 busy 0.00
17/04/2019 09:43:33 | Einstein@Home | [work_fetch] share 0.000 blocked by project preferences
17/04/2019 09:43:33 | GPUGRID | [work_fetch] share 0.000 job cache full
17/04/2019 09:43:33 | NumberFields@home | [work_fetch] share 1.000
17/04/2019 09:43:33 | SETI@home | [work_fetch] share 0.000
17/04/2019 09:43:33 | SETI@home Beta Test | [work_fetch] share 0.000
17/04/2019 09:43:33 |  | [work_fetch] --- state for Intel GPU ---
17/04/2019 09:43:33 |  | [work_fetch] shortfall 1017.93 nidle 0.00 saturated 7622.07 busy 0.00
17/04/2019 09:43:33 | Einstein@Home | [work_fetch] share 1.000
17/04/2019 09:43:33 | GPUGRID | [work_fetch] share 0.000
17/04/2019 09:43:33 | NumberFields@home | [work_fetch] share 0.000 no applications
17/04/2019 09:43:33 | SETI@home | [work_fetch] share 0.000 blocked by project preferences
17/04/2019 09:43:33 | SETI@home Beta Test | [work_fetch] share 0.000
17/04/2019 09:43:33 |  | [work_fetch] ------- end work fetch state -------
17/04/2019 09:43:33 | SETI@home Beta Test | choose_project: scanning
17/04/2019 09:43:33 | SETI@home Beta Test | skip: "no new tasks" requested via Manager
17/04/2019 09:43:33 | NumberFields@home | choose_project: scanning
17/04/2019 09:43:33 | NumberFields@home | can fetch CPU
17/04/2019 09:43:33 | NumberFields@home | can fetch NVIDIA GPU
17/04/2019 09:43:33 | NumberFields@home | can't fetch Intel GPU: no applications
17/04/2019 09:43:33 | Einstein@Home | choose_project: scanning
17/04/2019 09:43:33 | Einstein@Home | can't fetch CPU: blocked by project preferences
17/04/2019 09:43:33 | Einstein@Home | can't fetch NVIDIA GPU: blocked by project preferences
17/04/2019 09:43:33 | Einstein@Home | can fetch Intel GPU
17/04/2019 09:43:33 | GPUGRID | choose_project: scanning
17/04/2019 09:43:33 | GPUGRID | skip: "no new tasks" requested via Manager
17/04/2019 09:43:33 | SETI@home | choose_project: scanning
17/04/2019 09:43:33 | SETI@home | skip: "no new tasks" requested via Manager
17/04/2019 09:43:33 |  | [work_fetch] No project chosen for work fetch

**Comment by RichardHaselgrove** [comment]
That started much more cleanly, despite two projects being dry: the CPU work fetch is exactly right at 25920, 3 cores allowed.

@KeithMyers is also testing and reports all good so far (https://setiathome.berkeley.edu/forum_thread.php?id=83645&postid=1990896#1990896)

I'll leave this running, but if nothing shows up by tonight we should be good to go.

21/04/2019 10:13:38 |  | [work_fetch] Request work fetch: project work fetch resumed by user
21/04/2019 10:13:40 |  | choose_project(): 1555838020.265511
21/04/2019 10:13:40 |  | [work_fetch] ------- start work fetch state -------
21/04/2019 10:13:40 |  | [work_fetch] target work buffer: 4320.00 + 4320.00 sec
21/04/2019 10:13:40 |  | [work_fetch] --- project states ---
21/04/2019 10:13:40 | Einstein@Home | [work_fetch] REC 8517.373 prio -0.087 can request work
21/04/2019 10:13:40 | GPUGRID | [work_fetch] REC 257229.183 prio -0.000 can't request work: "no new tasks" requested via Manager
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] REC 2712.713 prio -0.013 can request work
21/04/2019 10:13:40 | SETI@home | [work_fetch] REC 402039.296 prio -3.891 can request work
21/04/2019 10:13:40 | SETI@home Beta Test | [work_fetch] REC 0.000 prio -0.000 can't request work: "no new tasks" requested via Manager
21/04/2019 10:13:40 |  | [work_fetch] --- state for CPU ---
21/04/2019 10:13:40 |  | [work_fetch] shortfall 30596.28 nidle 3.50 saturated 0.00 busy 0.00
21/04/2019 10:13:40 | Einstein@Home | [work_fetch] share 0.000 blocked by project preferences
21/04/2019 10:13:40 | GPUGRID | [work_fetch] share 0.000 blocked by project preferences
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] share 1.000
21/04/2019 10:13:40 | SETI@home | [work_fetch] share 0.000 blocked by project preferences
21/04/2019 10:13:40 | SETI@home Beta Test | [work_fetch] share 0.000 blocked by project preferences
21/04/2019 10:13:40 |  | [work_fetch] --- state for NVIDIA GPU ---
21/04/2019 10:13:40 |  | [work_fetch] shortfall 17280.00 nidle 2.00 saturated 0.00 busy 0.00
21/04/2019 10:13:40 | Einstein@Home | [work_fetch] share 0.000 blocked by project preferences
21/04/2019 10:13:40 | GPUGRID | [work_fetch] share 0.000
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] share 0.667
21/04/2019 10:13:40 | SETI@home | [work_fetch] share 0.333
21/04/2019 10:13:40 | SETI@home Beta Test | [work_fetch] share 0.000
21/04/2019 10:13:40 |  | [work_fetch] --- state for Intel GPU ---
21/04/2019 10:13:40 |  | [work_fetch] shortfall 712.56 nidle 0.00 saturated 7927.44 busy 0.00
21/04/2019 10:13:40 | Einstein@Home | [work_fetch] share 1.000
21/04/2019 10:13:40 | GPUGRID | [work_fetch] share 0.000
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] share 0.000 no applications
21/04/2019 10:13:40 | SETI@home | [work_fetch] share 0.000 blocked by project preferences
21/04/2019 10:13:40 | SETI@home Beta Test | [work_fetch] share 0.000
21/04/2019 10:13:40 |  | [work_fetch] ------- end work fetch state -------
21/04/2019 10:13:40 | GPUGRID | choose_project: scanning
21/04/2019 10:13:40 | GPUGRID | skip: "no new tasks" requested via Manager
21/04/2019 10:13:40 | SETI@home Beta Test | choose_project: scanning
21/04/2019 10:13:40 | SETI@home Beta Test | skip: "no new tasks" requested via Manager
21/04/2019 10:13:40 | NumberFields@home | choose_project: scanning
21/04/2019 10:13:40 | NumberFields@home | can fetch CPU
21/04/2019 10:13:40 | NumberFields@home | CPU needs work - buffer low
21/04/2019 10:13:40 | NumberFields@home | checking CPU
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] using MC shortfall 25919.999996 instead of shortfall 30596.280439
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] set_request() for CPU: ninst 4 nused_total 0.00 nidle_now 3.50 fetch share 1.00 req_inst 0.00 req_secs 25920.00
21/04/2019 10:13:40 | NumberFields@home | CPU set_request: 25919.999996
21/04/2019 10:13:40 | NumberFields@home | checking NVIDIA GPU
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] using MC shortfall 17279.999997 instead of shortfall 17279.999997
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] set_request() for NVIDIA GPU: ninst 2 nused_total 0.00 nidle_now 2.00 fetch share 0.67 req_inst 0.00 req_secs 17280.00
21/04/2019 10:13:40 | NumberFields@home | NVIDIA GPU set_request: 17279.999997
21/04/2019 10:13:40 | NumberFields@home | checking Intel GPU
21/04/2019 10:13:40 | NumberFields@home | Intel GPU can't fetch: no applications
21/04/2019 10:13:40 | NumberFields@home | [sched_op] Starting scheduler request
21/04/2019 10:13:40 | NumberFields@home | [work_fetch] request: CPU (25920.00 sec, 0.00 inst) NVIDIA GPU (17280.00 sec, 0.00 inst) Intel GPU (0.00 sec, 0.00 inst)
21/04/2019 10:13:40 | NumberFields@home | Sending scheduler request: To fetch work.
21/04/2019 10:13:40 | NumberFields@home | Requesting new tasks for CPU and NVIDIA GPU
21/04/2019 10:13:40 | NumberFields@home | [sched_op] CPU work request: 25920.00 seconds; 0.00 devices
21/04/2019 10:13:40 | NumberFields@home | [sched_op] NVIDIA GPU work request: 17280.00 seconds; 0.00 devices
21/04/2019 10:13:40 | NumberFields@home | [sched_op] Intel GPU work request: 0.00 seconds; 0.00 devices

**Comment by KeithMyers** [comment]
I have no complaints either.  I couldn't make it break requesting work from 4 projects running simultaneously, even allowing them to run dry several times. All projects had max_concurrent statements in app_config files.

**Pull request merged**
