### PR TITLE
[Windows] Build using ARM64

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
image
image

**Comment by davidpanderson** [comment]
Woo hoo!   Nice work.

**Comment by talregev** [comment]
> Woo hoo! Nice work.

I agree!

**Review by talregev — APPROVED** [review]
I cannot run it.
It compile on the ci. it running on vm. (From Vitalii screenshots).
I review some of the vsxproject files. it seems ok to me.

**Pull request merged**
