### PR TITLE
Fix for issue 5024

### PR DESCRIPTION
**Pull request by davidbolvansky**
Works fine now.

image

### CODE REVIEW

**Comment by davidpanderson** [comment]
We should make the same change for account manager user name:
AccountManagerProcessingPage.cpp:266:                username = (const char*)pWA->GetAccountUsername().mb_str();

I guess we can assume that passwords, proxy names, etc. won't have problem characters.

**Comment by RichardHaselgrove** [comment]
@lfield - can we squeeze the consequentials and testing into server release 1.4.0? Else, when would it be deployed?

**Comment by davidbolvansky** [comment]
> We should make the same change for account manager user name: AccountManagerProcessingPage.cpp:266: username = (const char*)pWA->GetAccountUsername().mb_str();

Done.

> I guess we can assume that passwords, proxy names, etc. won't have problem characters.

Right.

**Comment by davidpanderson** [comment]
Thanks for the fix.  This should appear in a client release fairly soon.

**Comment by davidpanderson** [comment]
BTW, this is a client (manager) change, not a server change.

**Comment by davidbolvansky** [comment]
Thanks!

**Pull request merged**
