### PR TITLE
[Wasm] Compile wasm with html

### PR DESCRIPTION
**Pull request by talregev**
Compile wasm with html.

### CODE REVIEW

**Comment by AenBleidd** [comment]
Not sure we need 'boinc' to be built as html. JS is more convenient

**Comment by talregev** [comment]
> Not sure we need 'boinc' to be built as html. JS is more convenient

You didn't try. The js is the same, but now it also build the html that show the output of boinc.
Please try and understand.
Create an html server with python on the folder of the artifacts after you extract them. 
` python3 -m http.server`

**Comment by AenBleidd** [comment]
It looks good for now but later we might want to embed it in our own html page, that's why we would need a bare js file without any html

**Comment by talregev** [comment]
> It looks good for now but later we might want to embed it in our own html page, that's why we would need a bare js file without any html

We create also the same bare JavaScript file `boinc_client.js` that doesn't depends on the html, and we can create our own html.

I can insert back the previous html as additional to this one.

**Comment by AenBleidd** [comment]
No need for now. Keep it as is

**Comment by talregev** [comment]
@AenBleidd Ready for review.

**Review by AenBleidd — APPROVED** [review]

**Pull request merged**
