### PR TITLE
Add utilities to update version of client, vboxwrapper and wrapper

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@talregev, please review

**Review by talregev — CHANGES_REQUESTED** [review]
I tests all 3 scripts and it work beautifully. Thank you for your hard work.
But before we can merge this changes, we need to decide on my previous PR:
https://github.com/BOINC/boinc/pull/4678
I change there the windows projects files, also fix a bug in naming. (this PR will not solve the bug), also I clean and the update script should update less lines.

**Comment by AenBleidd** [comment]
@talregev, thanks for the review.
#4678 will be discussed later after next planned release, after that these scripts could be adjusted.

**Comment by AenBleidd** [comment]
@davidpanderson, please review and merge

**Comment by talregev** [comment]
please add another utility that change all the link of vcpkg for testing. 
`https://github.com/microsoft/vcpkg` -> other test link

**Comment by AenBleidd** [comment]
This is out of the scope of this PR. Please open a separate issue.

**Pull request merged**
