### PR TITLE
Web: fix sample project_specific prefs

### PR DESCRIPTION
**Pull request by ChristianBeer**
The allow_non_preferred_apps tag was renamed in 671446ced1 for the scheduler but the sample project_specific prefs were not updated.

Existing projects need to update the file on their own if they use a scheduler that was build after 671446ced1 and rename the old tag in the DB. See html/ops/fix_project_prefs.php to do that.

### CODE REVIEW

**Comment by davidpanderson** [comment]
Let's do it the other way around and change the scheduler code.  No need for DB repair.  I'll do this soon.

**Comment by ChristianBeer** [comment]
The supplied script html/ops/fix_project_prefs.php does more than just rename the allow_non_preferred_apps tag, does your comment mean this script is also rejected as a whole or just the part of renaming the tag in the PHP code?

**Comment by davidpanderson** [comment]
Just renaming allow_non_preferred_apps.
Changing it was a mistake on my part.

**Comment by AenBleidd** [comment]
@ChristianBeer, I found this stale branch. Are you ok to delete it?

**Pull request closed without merging**
