### PR TITLE
Python2 compatible changes on print() and Exception()

### PR DESCRIPTION
**Pull request by smoe**
Hello,

Please grant this patch some scrutiny that is meant to address (bits of) https://github.com/BOINC/boinc/issues/3241 and may continue work in https://github.com/BOINC/boinc/pull/2477 .

The 'from __future__ import print_function' likely preserves compatibility with Python2. I suggest to add this until the transition to Python3 is completed.

Best,
Steffen

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Awesome work! We should probably use some python tool to check if anything is missing, but I really like the changes!

**Comment by LocutusOfBorg** [comment]
Can you please also fix this?
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903762

**Comment by smoe** [comment]
> Can you please also fix this?
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903762

Was there a second exception that I have missed? Otherwise that fix is in.

**Comment by TheAspens** [comment]
@smoe - just to confirm.  The intent is that this will allow support for both python 2.3 and 3?
If so I'll set up a vm to test this on centos 6 (installing python 2.3 only) and centos 8 (installing python 3.0 only).

**Comment by smoe** [comment]
I am very confident wrt the print instructions.  The exceptions may need a bit of extra love.

**Comment by TheAspens** [comment]
@smoe - PR #4043 should allow support of both python2 and python3.  Is there anything from this PR that should be kept or should it be closed?

**Comment by smoe** [comment]
Not having the opportunity to confirm this myself, trusting upstream though. Many thanks for the support of Python3.

**Pull request closed without merging**
