### PR TITLE
[Android] Android get latest libs: curl,zlib,rappture

### PR DESCRIPTION
**Pull request by talregev**
Android get latest libs: curl,zlib,rappture

### CODE REVIEW

**Comment by AenBleidd** [comment]
Does this mean that OpenSSL3 now builds without any issue on Android x86?

**Comment by talregev** [comment]
> Does this mean that OpenSSL3 now builds without any issue on Android x86?

No. it still take the old openssl 1.1.1n.
But take the latest other libraries.
It just updated automated the latest vcpkg master inside the json file.

**Comment by talregev** [comment]
> Does this mean that OpenSSL3 now builds without any issue on Android x86?

We still need your fix for openssl 3.0.3 for Android.

**Comment by AenBleidd** [comment]
If you want - you can implement this fix by yourself and don't wait for me.

**Comment by talregev** [comment]
> If you want - you can implement this fix by yourself and don't wait for me.



> If you want - you can implement this fix by yourself and don't wait for me.

I didn't understand your fix, so it better you do it. Also, you can review my PR until you have time for your fix.

**Comment by talregev** [comment]
> If you want - you can implement this fix by yourself and don't wait for me.



> If you want - you can implement this fix by yourself and don't wait for me.

I didn't understand your fix, so it better you do it. Also, you can review my PR until you have time for your fix.

**Comment by AenBleidd** [comment]
There is an issue with this PR: every time you build binaries locally, vcpkg.json files will be changed, and every time you need to remember to not commit these changes.
Is there any way to eliminate this?

**Comment by talregev** [comment]
> There is an issue with this PR: every time you build binaries locally, vcpkg.json files are changed, and every time you need to remember to not commit these changes. Is there any way to eliminate this?

Tell me the final thing you want to achieve.

**Comment by talregev** [comment]
> There is an issue with this PR: every time you build binaries locally, vcpkg.json files are changed, and every time you need to remember to not commit these changes. Is there any way to eliminate this?

avoid commits unchanged files?
I think we can put them in ignore

**Comment by AenBleidd** [comment]
We can't put them in ignore because then you have to remember to force add them when you change them (e.g. by setting a new version).

I want to avoid errors as much as possible, and currently your solution will create errors later.

As far as I see, this later will not be needed when OpenSSL 3 issue for Android x86 is fixed.

So I'd not merge it at all for now.
The only case when we might need this is if we want to fix some particular version of any dependency on release branch but in that case vcpkg.json file change is expected.

So maybe it's better to always keep the last committed value of 'builtin-baseline' and update it from the script on demand only by passing some specific parameter to build script?

**Comment by talregev** [comment]
> We can't put them in ignore because then you have to remember to force add them when you change them (e.g. by setting a new version).
> 
> I want to avoid errors as much as possible, and currently your solution will create errors later.
> 
> As far as I see, this later will not be needed when OpenSSL 3 issue for Android x86 is fixed.
> 
> So I'd not merge it at all for now. The only case when we might need this is if we want to fix some particular version of any dependency on release branch but in that case vcpkg.json file change is expected.
> 
> So maybe it's better to always keep the last committed value of 'builtin-baseline' and update it from the script on demand only by passing some specific parameter to build script?

@AenBleidd When are you going to fix android openssl vcpkg? If it soon, there is no point to discuss.

**Comment by AenBleidd** [comment]
Fix is provided and currently in review: https://github.com/microsoft/vcpkg/pull/24801
@talregev, should we close this PR without merging or you have some other plans on it?

**Comment by talregev** [comment]
> Fix is provided and currently in review: https://github.com/microsoft/vcpkg/pull/24801
> @talregev, should we close this PR without merging or you have some other plans on it?

We should wait for your fix. After that we can discuss. Also if your fix is delay we can discuss again.

**Pull request closed without merging**
