### PR TITLE
client (Linux): Fix X-based idle detection

### LINKED ISSUE #3509: BOINC doesn't resume after inactivity period
**Describe the bug**
BOINC doesn't resume after inactivity period.
It's not an idle time detection problem, beacause with "idle_detection_debug" activated in "Event log options" I get log messages like

```
21-Mar-2020 15:09:26 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:26 [---] [idle_detection] idle_time: 57791
21-Mar-2020 15:09:27 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:27 [---] [idle_detection] idle_time: 58794
21-Mar-2020 15:09:28 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:28 [---] [idle_detection] idle_time: 59797
21-Mar-2020 15:09:29 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:29 [---] [idle_detection] idle_time: 60806
21-Mar-2020 15:09:30 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:30 [---] [idle_detection] idle_time: 61809
21-Mar-2020 15:09:31 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:31 [---] [idle_detection] idle_time: 62812
21-Mar-2020 15:09:32 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:32 [---] [idle_detection] idle_time: 63815
21-Mar-2020 15:09:33 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:33 [---] [idle_detection] idle_time: 64818
21-Mar-2020 15:09:34 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:34 [---] [idle_detection] idle_time: 65821
21-Mar-2020 15:09:35 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:35 [---] [idle_detection] idle_time: 66824
21-Mar-2020 15:09:36 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:36 [---] [idle_detection] idle_time: 67827
21-Mar-2020 15:09:37 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:37 [---] [idle_detection] idle_time: 68829
21-Mar-2020 15:09:38 [---] [idle_detection] XSS idle detection succeeded on DISPLAY ':0'.
21-Mar-2020 15:09:38 [---] [idle_detection] idle_time: 69832
```

**Steps To Reproduce**
1. run boinc
2. run boincmgr
3. set "'In use' means mouse/keyboard input in last [x] minutes" to 1 in preferences and save
4. wait 1 minute without touching mouse and keyboard: tasks won't resume (they will still show a "Suspended - computer is in use" status)

**Expected behavior**
BOINC tasks should resume after the inactivity period

**System Information**
 - OS: up-to-date Arch Linux with kernel 5.5.10-arch1-1
 - BOINC Version: 7.16.5

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #3509

### CODE REVIEW

**Comment by AenBleidd** [comment]
Closing this in favor of cleaner #3512

**Comment by davidpanderson** [comment]
Does anyone know how I can get rid of the unmerged commits?

**Comment by AenBleidd** [comment]
On you local master branch try to run next:
`git reset --hard origin/master`

**Comment by davidpanderson** [comment]
Thanks; I did this, hopefully it will work.

**Pull request closed without merging**
