### PR TITLE
[Manager][linux] Search for skins in /usr/(local)/share/boinc-manager/skins or ./skins folders.

### LINKED ISSUE #4809: [Manager][linux] Search for skins to display on Simple View
Currently BOINC Simple View on linux has no default skin and looks not so nice as on other OSs.
It would be nice to look for default skin in the next locations:
- /usr/share/boinc-manager/skins/
- /usr/local/share/boinc-manager/skins/
- ./skins

### PR DESCRIPTION
**Pull request by AenBleidd**
This fixes #4809.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@LocutusOfBorg, @Germano0, please review

**Comment by talregev** [comment]
Please add screen shots

**Comment by AenBleidd** [comment]
@talregev, done.
image

**Comment by talregev** [comment]
Thank you.
Also we should add to the CI that it will copy the skin folder along the binary.
Can you add that?

**Comment by AenBleidd** [comment]
> Also we should add to the CI that it will copy the skin folder along the binary.
Can you add that?

We don't do this for any other flow, so definitely not in this PR since it has nothing with the bug that is fixed with this PR

**Comment by talregev** [comment]
We should do this for all other flow. We will add this also for windows and mac. Also locale folder.

**Comment by talregev** [comment]
@AenBleidd Where is the skin folder? I don't see it on our repo.

**Comment by AenBleidd** [comment]
@talregev, https://github.com/BOINC/boinc/tree/master/clientgui/skins

**Comment by talregev** [comment]
> @talregev, https://github.com/BOINC/boinc/tree/master/clientgui/skins

Thank you!

**Comment by talregev** [comment]
> We should do this for all other flow. We will add this also for windows and mac. Also locale folder.

Can you make a PR after this PR will merge?

**Comment by AenBleidd** [comment]
> > We should do this for all other flow. We will add this also for windows and mac. Also locale folder.
> 
> Can you make a PR after this PR will merge?

@talregev, I'll add it to the backlog and will decide if that is necessary

**Comment by talregev** [comment]
> > > We should do this for all other flow. We will add this also for windows and mac. Also locale folder.
> > 
> > 
> > Can you make a PR after this PR will merge?
> 
> @talregev, I'll add it to the backlog and will decide if that is necessary

We should. Usually I am testing the binary from CI. That why I added the c files for WebAssembly debug.

**Comment by LocutusOfBorg** [comment]
why aren't such skins installed in Makefile.am? How can the packager know they are needed if the build system is not installing them?

**Comment by AenBleidd** [comment]
That's a very good question! Thanks, @LocutusOfBorg, I'll fix that

**Comment by talregev** [comment]
@LocutusOfBorg Please answer on discord. Thank you :)

**Comment by LocutusOfBorg** [comment]
Any subsequent build after boinc https://code.launchpad.net/~costamagnagianfranco/+recipe/boinc-upstream-daily
7.22.0+dfsg+git20220627+r25142~r115
or https://code.launchpad.net/~costamagnagianfranco/+recipe/boinc-daily
7.20.0+dfsg+202206271354

Should have skins installed, but please install them from Makefile.am

**Comment by AenBleidd** [comment]
> Should have skins installed, but please install them from Makefile.am

This is exactly what I am working on right now.

Thanks, @LocutusOfBorg

**Review by talregev — APPROVED** [review]
I download the manger with webview artifact, run it on wsl.
locale and skins folder are working. 


image

**Comment by LocutusOfBorg** [comment]
Ok nice thanks! I committed the change in my packaging system to use the upstream installation path. Now the build is broken in boinc-upstream-daily until this PR is merged :)

**Comment by talregev** [comment]
> Ok nice thanks! I committed the change in my packaging system to use the upstream installation path. Now the build is broken in boinc-upstream-daily until this PR is merged :)

Can you test your build on this PR before merge?
To change to vitalii branch?

**Comment by LocutusOfBorg** [comment]
>Can you test your build on this PR before merge?
yes

>Build on vitalii branch?
no

I can fetch different branches from BOINC/boinc, but I don't want to add new sources. Instead, I extracted the PR as patch on this link https://github.com/BOINC/boinc/pull/4811.patch and added it to the Debian packaging

https://git.launchpad.net/~costamagnagianfranco/+git/boinc-upstream/commit/?id=ee0fec1474d100a905ad111d6724fca4ae5a45ca

So, this patch will break the build once this PR is merged, and I'll just remove it.

G.

**Comment by talregev** [comment]
> >Can you test your build on this PR before merge?
> yes
> 
> >Build on vitalii branch?
> no
> 
> I can fetch different branches from BOINC/boinc, but I don't want to add new sources. Instead, I extracted the PR as patch on this link https://github.com/BOINC/boinc/pull/4811.patch and added it to the Debian packaging
> 
> https://git.launchpad.net/~costamagnagianfranco/+git/boinc-upstream/commit/?id=ee0fec1474d100a905ad111d6724fca4ae5a45ca
> 
> So, this patch will break the build once this PR is merged, and I'll just remove it.
> 
> G.

Thank you!

**Comment by LocutusOfBorg** [comment]
Screenshot from 2022-06-29 10-03-17
Screenshot from 2022-06-29 10-07-01

**Comment by LocutusOfBorg** [comment]
On simple view, click "notices" brings an empty page and then the program exits...

**Comment by AenBleidd** [comment]
@LocutusOfBorg, is looks like this issue: #4784

**Comment by LocutusOfBorg** [comment]
mmm but I didn't switch between simple and advanced view, just clicked on "notices"

**Comment by AenBleidd** [comment]
@LocutusOfBorg, yeah because the real crash is happens inside wxWebView component that is used on Notices windows and Notices tab

**Comment by AenBleidd** [comment]
@LocutusOfBorg, thank you for testing this!

**Pull request merged**
