### PR TITLE
client, mgr: add support for registering user's consent to project's terms of use

### PR DESCRIPTION
**Pull request by JuhaSointusalo**
This PR adds the missing pieces of code to the consent work done in #2504 making it possible for users to consent to project's terms of use using Manager and having that consent recorded in project database.

This is implemented by
- Adding `<name>` element to `<exchange_versions>` GUI RPC. The name is something like "BOINC Manager 7.15.0". `<major>`, `<minor>` and `<release>` in `<exchange_versions>` is now interpreted as API version.
- Adding `<consented_to_terms/>` element to `<create_account>` GUI RPC to mark that the project had terms of use and the user consented to the terms.
- Including the GUI name and consent in `create_account` Web RPC.

I didn't add consent functionality to `boinccmd` because I don't think we can do that. `boinccmd` doesn't know if the user has seen the terms. `boinccmd` could be made to print terms first and ask for consent but I see it as a very simple tool over the GUI RPCs. It just converts command line options to XML and pretty prints results.

Release Notes:
client, mgr: add support for registering user's consent to project's terms of use

### CODE REVIEW

**Comment by brevilo** [comment]
Let's see. As far as I can tell this PR mainly deals with the communication between client and manager. The only interaction between client and server I can find is [this one](https://github.com/BOINC/boinc/pull/2835/files#diff-67aa44aadac41351a9b3f3928fd44c9eR190). Is that correct?

**Comment by JuhaSointusalo** [comment]
> The only piece affecting the client/server communication I can find is [this one](https://github.com/BOINC/boinc/pull/2835/files#diff-67aa44aadac41351a9b3f3928fd44c9eR190). Is that correct?

Correct. The extra parameters are added only if the project has terms and only the user accepted them. The parameters are added whether the project is pre- or post-GDPR. I don't think the pre-GDPR server cares about the extra parameters but I don't remember if I actually tested that.

There is no check to see if the the server is pre- or post-GDPR because that doesn't seem necessary.

**Comment by brevilo** [comment]
> There is no check to see if the the server is pre- or post-GDPR because that doesn't seem necessary.

Hm, you're right. I misjudged that which means that what I [said earlier](https://github.com/BOINC/boinc/issues/2413#issuecomment-442844822) about `get_project_config.php` needing an update was incorrect (now marked in strikethrough).

That said, from a project's perspective, the only thing we care about is that `consent_flag` and `source` are properly passed. What we still need is a configuration option for `create_account.php` that let's us re-enable it but **only for requests with the two new parameters passed**. That should probably be handled in a separate PR, though.

I can't really say anything about the whole manager/client communication covered by this PR, so the other two guys should review it instead of me. But thanks for taking on this part of the solution! 👍

**Comment by brevilo** [comment]
> There is no check to see if the the server is pre- or post-GDPR because that doesn't seem necessary.

Yep, I agree. That's because the additional request parameters are simply ignored by the server. Thanks!

The manager/client parts need to be reviewed by someone else, though, as these are not my area of expertise.

**Comment by TheAspens** [comment]
@JuhaSointusalo - is this pull request still ready for review?  If so I'll start reviewing.  Thanks.

**Comment by JuhaSointusalo** [comment]
IIRC it was ready but now that I looked at it again I noticed this comment:
```cpp
// client passes its version, but ignore it for now
//
static void handle_exchange_versions(GUI_RPC_CONN& grc) {
```
That might be outdated. I can't remember right now if the 'client' there refers to the BOINC core client or RPC client.

**Comment by JuhaSointusalo** [comment]
I decided to remove the comment. I didn't test this again or anything. Since I have opened the pull request I'm going to assume I have tested it thoroughly already.

**Comment by brevilo** [comment]
> What we still need is a configuration option for `create_account.php` that let's us re-enable it but **only for requests with the two new parameters passed**.

I added this just now via PR #3049.

**Comment by brevilo** [comment]
FYI, #3049 was merged, so this PR here is missing link which would allow us to re-enable client-based account registration.

**Comment by brevilo** [comment]
Also, could reviewers please have a look at #3053? It asks for some clarification regarding the consent RPC workflow, focusing on the client/manager/boinccmd/AM workflow in particular.

**Comment by JuhaSointusalo** [comment]
Ready for review again.

There was a merge conflict due to @brevilo stealing error number -242 from me. 😃 That's fixed now.

**Comment by brevilo** [comment]
Ooops, first! 😇

**Comment by TheAspens** [comment]
@JuhaSointusalo - I started to test this today against a website build from the master branch and I'm getting a bunch of unusual things (global_prefs and project_prefs null for new users, website asking me to approve prefs again after registering through your version of client that prompted me for ToU).  I need to go back and rebuild the test environment and figure out what is going on.  I'm assuming there is something built wrong on my end.

Unfortunately, I'm going out for vacation over the next week so I won't be able to get back to this until after.  I'm going to remove my name from it for now but if it is still here when I'm back I'll pick it up again.

Sorry for the delay.

**Comment by JuhaSointusalo** [comment]
I tested this again but couldn't replicate your problem with registering consent except by forgetting to use not only Manager from this PR but also Client.

As for null prefs, aren't those created only when user saves preferences and until then defaults are used? FWIW, my Raspberry PI has only ever worked for Einstein@home and it doesn't have `global_prefs.xml` (I have never set computing prefs there). My account there was created before Drupal so I don't know if these days new accounts would get prefs stored in database when account is created.

(Though I'm not sure why computing preferences have not propagated to Einstein@home from other machines. Maybe because I'm using local prefs on all machines.)

**Comment by TheAspens** [comment]
@JuhaSointusalo - sorry for the delay.  I'm assigning myself to this and hope to get it tested by and reviewed by end of week.

**Comment by TheAspens** [comment]
I've been testing this today.  I'm testing the following:

- Fresh install of website from the master branch.
- BOINC core client from branch js-client-mgr-consent-stuff
- BOINC manager from branch js-client-mgr-consent-stuff

If I'm I create a terms_of_use.txt file and then enable the consent type via the ops interface, then the manager will prompt the user to accept the terms of service after selecting the project but before it asks them for their user account information.  It always does this.

The users acceptance of the terms of use is never stored in the database when it is accepted on the client.  

If the user logs into the website and if the config.xml option enable_login_mustagree_termsofuse has been enabled, then the user is prompted to accept the terms of use on the website.  Only then is the consent stored in the database.

I've already found one bug in the website consent logic (which I'll open an issue and fix for shortly).  I'll need to take a look at exactly what the client is sending and how the server is handling it.  I'll let you know when I figure out what is going on.

In the meantime, one question.  Is it intended that if a project has terms of use (and the consent enable) that the user must always accept those terms of user during the project attach process?

**Comment by TheAspens** [comment]
If I register via the client when the website has a terms_of_use.txt file and the ENROLL consent type is enabled then the consent record is stored in the database and I am not prompted to accept the terms of use when I log into the website.  This is what I would expect.

In all other cases, when attaching to a project using an existing account, the user will always been shown the terms of use (regardless of if they have previously accepted it or not) and the user's acceptance of the terms of use on the client will not be recorded in the database.  

This seems like an extra click through screen for the user in most cases (they register once but attach dozens of times).  I think that the user should only have to accept the terms of use once on either the client or on the website.  The client should get a signal back from lookup_account.php and based on that only show the terms of use if the user has not previously accepted them.

**Comment by JuhaSointusalo** [comment]
I don't really remember all the finer details but I think consent is registered only when creating a new account because that's all the server can do. I don't think there was any RPCs or anything for registering consent when adding a machine to an existing account.

As for showing terms always. That's bad user experience but it has always been like that, no change there. It could be improved but I think it would be best to carefully go through all the different cases. Draw a flowchart or whatever. This so that it can be easily verified that you thought of all the cases. It'll also provide a nice check list for implementing and review phases.

If I remember correctly @brevilo opened an issue to discuss and clarify the consent stuff. You should probably take a look at that too and maybe the original issues as well to see if anything there requires changes here.

**Comment by TheAspens** [comment]
@JuhaSointusalo - I misunderstood the scope of this pull request then.  Just to be clear - your changes are designed only to impact the behavior when the user registers through the client?  (i.e. this PR does not changing anything with regards to an existing user attaching to a project?).  Let me know and I will narrow my review to that scope.

I developed a set of test cases for testing this that would provide good input to a state chart diagram and I can code it with what works currently and what remains to be done.  I'll connect that with @brevilo issue.

**Comment by brevilo** [comment]
> If I remember correctly @brevilo opened an issue to discuss and clarify the consent stuff

Yes, see [above](https://github.com/BOINC/boinc/pull/2835#issuecomment-474290930).

**Comment by TheAspens** [comment]
I've tested this and this code successfully sets the required fields and parameters to update the consent table (if the server is using an updated version) to record that the user accepted the TOU in the client.

Thanks for the contribution!

**Pull request merged**
