### PR TITLE
Mac: Automatically build Universal x86_64 / arm64 binaries

### LINKED ISSUE #3827: Support Apple's transitioning of Macs to new ARM CPU & GPU
Bloomberg and others report that Apple is developing its own ARM processors for use in Macs starting in 2021, gradually replacing the current Intel processors in various Mac models.

<https://www.bloomberg.com/news/articles/2020-04-23/apple-aims-to-sell-macs-with-its-own-chips-starting-in-2021>

When Apple transitioned Macs from PowerPC to Intel CPUs in 2006, they temporarily provided an emulator (which Apple called "Rosetta") to allow the new computers to run the older software. They also added a capability in the development tools to create "fat binaries", which contained two copies of software, one for PowerPC architecture and one for Intel architecture. It seems likely that Apple will use a similar approach again. 

Rosetta was introduced in Mac OS 10.4.4 (January 2006) and discontinued as of OS 10.7 (July 2011.) The ability to generate both PowerPC and Intel code and generate a fat binary was introduced in Xcode 2.1 (June 2005); PowerPC code generation was discontinued as of Xcode 4 (March 2011.)

Assuming Apple follows the same pattern, current Intel-based BOINC code will probably run on the new ARM based Macs for a few years, though at a reduced efficiency due to emulation. However, it is not clear whether BOINC Mac GPU code will be able to run on the Apple GPU.

To take full advantage of the new Mac hardware, we will need to update all Xcode projects, build scripts and autoconf / make files to build both Apple ARM and Intel architectures and release fat binaries. Note that this applies to building all the dependent libraries (cURL, OpenSSL, wxWidgets, etc.), as well as BOINC projects.

I hope that some of the Mac developers who have more recently expressed interest in helping BOINC will be able to take this on. I especially want to bring this to the attention of @ShanghaiTimes and @RoboticMind.

### PR DESCRIPTION
**Pull request by CharlieFenton**
Mac: Automatically build:
* Universal x86_64 / arm64 binaries on Xcode versions that support building both architectures
* x86_64-only binaries on _Xcode_ versions that support only x86_64
* arm64-only binaries on _Xcode_ versions that support only arm64.

CAUTION # 1: I don't have arm64 macintosh hardware so this has been tested only on an x86_64 system.
CAUTION # 2: This was developed on _MacOS 11.0 beta 3_ and _Xcode 12.0 beta 2_, not final release builds
CAUTION # 3: At this time _OpenSSL_ does not yet provide a way to build for MacOS with arm64 architecture, so I implemented a temporary workaround, which may or may not work properly on arm64 Macs.

Fixes #3827 

Apple has announced that they will be transitioning to all arm64 ("Apple Silicon") Macs over the next two years, with the first ones to be released at the end of 2020. Apple Silicon Macs will initially include an emulator or virtual machine capable of running x86_64 code, but these will run less efficiently than native arm64 binaries and this capability will be phased out over time.

At this time, some (but not all) builds of _Xcode 12_ support building binaries for both Intel x86_64 Macintoshes and Apple Silicon (arm64) Macs. While these will automatically build _Xcode_ based projects as Universal Binaries containing both architectures, BOINC's third party dependent libraries use _configure_ and _make_ and so require additional effort to produce Universal Binaries. And BOINC code itself required a few modifications to be compatible with arm64 Macs.

This PR does the following:

* Updates the build scripts for the dependent libraries _c-ares_, _curl_, _freestyle_, _ftgl_, _openssl_ and _wxWidgets_ to automatically build for x86-64 architecture, arm64 architecture, or both, depending on the capabilities of the _Xcode_ version being used.

* Eliminates obsolete build settings in the _Xcode_ project which were incompatible with building for arm64.

* Adds arm64-apple-darwin as a valid BOINC platform in addition to i686-apple-darwin and x86_64-apple-darwin. (Note that the 32-bit i686-apple-darwin platform is only available on versions of MacOS prior to _OS 10.15_.)

* Updates the release script release_boinc.sh to name the directories containing the installer and associated files boinc_x.y.z_macOSX_x86_64boinc_x.y.z_macOSX_arm64 or  boinc_x.y.z_macOSX_universal as appropriate. It similarly updates the release_brand.sh script to label its products with the appropriate architecture.

* Updates other Macintosh-specific BOINC files for arm64 compatibility.

### CODE REVIEW

**Comment by CharlieFenton** [comment]
Xcode 12 beta 3 warns that the deployment target is OS 10.7 but the minimum supported by this version of Xcode is OS 10.11, though it builds successfully. This makes me think that BOINC may not work properly under MacOS versions earlier than OS 10.11 7when we build with Xcode 12.

**Comment by CharlieFenton** [comment]
This is as complete as possible without having an arm64 Mac to test with. 

A couple more considerations:

* We will need to add code for arm64 CPUs to the method `get_cpu_info_mac(HOST_INFO& host)` in _hostinfo_unix.cpp_. That file already has arm64 code for linux. I suspect we may be able to copy that code as a starting point for supporting arm64 Macs.

* The method int `is_native_i386_app(char*)` in _app_start.cpp_ and _app.h_ was originally needed in the early years of Intel Macs, which had Apple's Rosetta emulator to run PowerPC code. It was needed because PowerPC apps emulated on i386 Macs crashed if running graphics. Apple's Rosetta PowerPC emulator was discontinued a long time ago, but the new arm64 Macs will have a new Rosetta emulator to run x86_64 apps. 

If needed, I expect that the `is_native_i386_app(char*)` method will require little or no modification to test for x86_64 apps on arm64 Macs. We don't know whether or not this capability will be needed, so I have not removed it.

**Comment by CharlieFenton** [comment]
Since @AenBleidd feels this PR needs review, and since Macs with _arm_ CPUs will not be released for a few months, there may be a delay in merging this PR. But I expect that MacOS 11, which is well into beta testing, will be released soon.

So I have included two of the same files that are in this PR in a new PR #3963 because they are necessary for the BOINC screensaver coordinator to work properly under MacOS 11 and so should be included in the next release of BOINC for the Mac. The two files are  _clientscr/gfx_switcher.cpp_ and _clientscr/screensaver.cpp_.

**Comment by CharlieFenton** [comment]
I feel it is **important to merge this as soon as possible**, and certainly within a very few days. Although more work may be needed for running on Apple Silicon (arm64) Macs, it is safe to release this code now, because none of the changes affecting arm64 will be included in a build with Xcode 11 or earlier. Only Xcode 12 will include the arm64 code in a build. I have tested this code on my Intel Mac under multiple versions of MacOS and found no problems.

I have removed the WIP from this PR because have done as much as possible without access to an arm64 Mac, but merging this code into master now will make it much easier to finalize arm64 support quickly when **Apple starts selling arm64 Macs before the end of this year**.

@AenBleidd has marked this as requiring review, but I don't know of anyone qualified to do that. Please do not let this PR sit in limbo if there is no one who can quickly perform a review.

**Comment by CharlieFenton** [comment]
Closing and reopening to trigger CI Travis build

**Comment by AenBleidd** [comment]
@davidpanderson, could you please review and merge this if you're ok with these changes?

**Pull request merged**
