### PR TITLE
Expand usage of HTTPS and fix a few URLs

### PR DESCRIPTION
**Pull request by funkydude**
@davidpanderson This pull request is really a continuation of https://github.com/BOINC/boinc/issues/1475

It expands the use of HTTPS significantly. I've also changed some URLs to be relative where possible, and fixed a few outdated/broken ones.

Some URLs I tried to change to be relative/HTTPS but used elements loaded from a "load.php" which forced them to load over HTTP, creating mixed content errors in browsers. Unfortunately load.php doesn't seem to be in this repo, so I've left those URLs as (forced) HTTP for now.

### CODE REVIEW

**Comment by romw** [comment]
Thanks for the submission.

**Comment by brevilo** [comment]
@funkydude Please add your email address to your git author details. Thanks.

FYI, the http -> https changes are incomplete and caused a regression in Drupal as at least one of the changed strings is used as a reference but the referencing code wasn't updated accordingly. I'll either revert that part of the commit or fix the reference. We'll see.

That said, we should think about how to sign-off and accept PRs that affect multiple subsystems. I think that all maintainers of the subsystems affected need to sign-off a PR in order to avoid regressions like this...

**Comment by funkydude** [comment]
> Please add your email address to your git author details. Thanks.

No.

> FYI, the http -> https changes are incomplete and caused a regression in Drupal

I purposely tried to avoid all Drupal related code, seems one slipped through.

> Please pay attention to little but important details like this.

This PR wasn't supposed to be merged as-is. I was expecting review, commentary, and requests for further improvements/missed areas to fully polish it off. For example, my commentary on the Wikimedia load.php file.

If you have feedback, please don't be vague about it, simply state the exact problem so we can clean this up.

**Comment by brevilo** [comment]
Ok, I fixed the regression in de824306564d61859feca23579b8250212a4e2c5

>> Please add your email address to your git author details. Thanks.

> No.

Well, authors should always be able to be contacted, without depending on a certain platform like GitHub, so the email is essential. I for one would reject PRs with commits without proper email address but I leave this with BOINC to decide...

> This PR wasn't supposed to be merged as-is. I was expecting review, commentary, and requests for further improvements/missed areas to fully polish it off

Yeah, that's a known issue and should be improved.

**Comment by funkydude** [comment]
> Well, authors should always be able to be contacted, without depending on a certain platform like GitHub, so the email is essential. I for one would reject PRs with commits without proper email address but I leave this with BOINC to decide...

I agree, but adding my email address simply encourages the use of an awful, archaic system. You try to validate having an email address by "not depending on GitHub" yet justify it by 1) using another system that requires being dependant upon, 2) Requires being logged into that system.

PRs have commentary for a reason. All discussion involving this PR should be in this thread, fully viewable and readable by everyone, not hidden in an inconvenient email discussion.

Quite frankly if you're concerned about historic reasons, this GitHub thread is far more likely to still be here 5 years from now than digging up some email thread. There is even references to it in the commit itself which there wouldn't be in an email.

>Ok, I fixed the regression
... 
Yeah, that's a known issue and should be improved.

I still think this specific PR requires more discussion and more work to fully encompass everything with HTTPS, if anyone is interested.

**Comment by brevilo** [comment]
> You try to validate having an email address by "not depending on GitHub" yet justify it by 1) using another system that requires being dependant upon, 2) Requires being logged into that system.

Nope, git repos exist independently of the **current** hosting platform. Your author information is simply part of the repo's autarkic history (it's incomplete without it). It shouldn't depend on more systems than necessary. E-Mail is certainly the smallest common denominator.

> PRs have commentary for a reason. All discussion involving this PR should be in this thread, fully viewable and readable by everyone, not hidden in an inconvenient email discussion.

Yep, I agree. My comment about your missing email was independent of the regression discussion which I would have started here in any case - that is, even if I'd have had your mail address.

> I still think this specific PR requires more discussion and more work to fully encompass everything with HTTPS, if anyone is interested.

Sure, I fully agree. @romw etc. need to chime in here though as the other changes affect their subsystems.

**Pull request merged**
