### PR TITLE
Improve code base using cppcheck part.1

### LINKED ISSUE #3513: Code improvements results from Cppcheck
I ran [cppcheck](https://github.com/danmar/cppcheck) on the Boinc codebase which resulted in the some code improvements. 

Download the results here: [boinc_cppcheck.zip](https://github.com/BOINC/boinc/files/4365631/boinc_cppcheck.zip)

### PR DESCRIPTION
**Pull request by winkies**
Partially Fixes #3513 (need to be split just for review)

**Description of the Change**
- Add constness 
- Add explicit keyword on ctor definition
- Initialize attributs using c++ style
- Clean whitespace
- ...

**Alternate Designs**
Use another analysis tool.

**Release Notes**
Apply changes according performance, portability and style warnings through cppcheck.

### CODE REVIEW

**Comment by AenBleidd** [comment]
`zip` is a 3rdparty component and it should not be changed (we're not supporting it, just using).
Also please split this and #4287 into smaller PRs (e.g. 1 cppcheck issue type - 1 PR), otherwise it's almost impossible to review it

**Comment by winkies** [comment]
@AenBleidd Alright, I will not modify `zip` 3rd party.

What?! It's easy to review a PR with 70 modified files ah-ah :upside_down_face: 

I will close this and the next one in order to propose a better PR organization!

Just one question: Do you modify Code coverage rule on CI recently ? :thinking:

**Comment by AenBleidd** [comment]
> Just one question: Do you modify Code coverage rule on CI recently ? 🤔

Yes, it contained issues and show wrong numbers. Should be more correct now.

**Comment by winkies** [comment]
Thanks for this clarification. I close this :)

**Pull request closed without merging**
