### PR TITLE
Project-Rain Merge

### PR DESCRIPTION
**Pull request by grctest**
I have successfully implemented 'project-rain' functionality into the BOINC web server, tested with the boinc-server docker.

I have added cryptocurrency fields to the BOINC stat extracts (user.xml.gz), configured within the user's profile.

I do notice that there are new changes since development (late may), I'll look into updating my version in the near future.

Relevant issue: https://github.com/BOINC/boinc/issues/1998

### CODE REVIEW

**Comment by davidpanderson** [comment]
Our policy is to not have code in the BOINC distribution that's directly related to virtual currencies.

**Comment by grctest** [comment]
What about a single custom field which doesn't mention virtual currencies?

Where is this virtual currency policy documented? Is this the stance of the entire PMC?

**Comment by davidpanderson** [comment]
The policy is the consensus of the PMC.

I'm not sure a new DB field would accomplish without accompanying code.  Projects can manually add such a field.  Might be better to use a new table.

**Comment by grctest** [comment]
> The policy is the consensus of the PMC.

Can you direct me to discussions and or minutes related to the PMC's consensus on this topic please? As far as I'm aware the PMC isn't actively governing in a public/transparent manner (other than this enforced undocumented 'policy').

>  Might be better to use a new table.

These fields were added as a new table, rather than integrated within existing tables as you previously instructed (can't locate the old post but I previously attempted to include it within the main tables which caused errors) : https://github.com/grctest/boinc/blob/07c9c3dacd51d0c1fc88170ba0aac142d9eaa2ee/db/schema.sql#L338

---

Might be better to dump the fields to a separate xml gz than user.xml.gz given that it would be massively inflated.

Cheers

**Comment by ChristianBeer** [comment]
This PR needed to be rejected either way because it contains unrelated changes and reverts changes done to master. Two commits that it reverts are: 90f8a1d4b4280ead1 and 20d07be2b8ee5c59e58

**Pull request closed without merging**
