### PR TITLE
[Android] Update on-screen instructions

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Screenshot_2021-05-02-04-20-55-194_edu berkeley boinc

**Review by Isira-Seneviratne — APPROVED** [review]

**Comment by davidpanderson** [comment]
"Hint" makes it sound like the user has to solve a puzzle.
Maybe "tip" (or no word).

The screenshot shows hint 1/3.  What are the other 2?

**Comment by AenBleidd** [comment]
> "Hint" makes it sound like the user has to solve a puzzle.
Maybe "tip" (or no word).

Yeah, "tip" could be better. Will change it.

> The screenshot shows hint 1/3. What are the other 2?

Screenshot_2021-05-03-00-37-22-147_edu berkeley boinc
Screenshot_2021-05-03-00-37-27-359_edu berkeley boinc

**Comment by AenBleidd** [comment]
@davidpanderson, 'Hint' changed to 'Tip'

**Comment by AenBleidd** [comment]
@davidpanderson, could you please review again? Thanks in advance

**Pull request merged**
