### PR TITLE
[CI] Add *.yml files to the hash while resolving cache, remove restore-key

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Review by CharlieFenton — COMMENTED** [review]
Sorry, I know absolutely nothing about YML syntax or how Github Actions work, so I can't offer any help.

**Comment by AenBleidd** [comment]
@CharlieFenton, at least you can check that this fixes the initial issue with cache

**Comment by CharlieFenton** [comment]
I think you would be better asking @ChristianBeer. I have added him as a reviewer.
@ChristianBeer please see Issue #4612.

> @CharlieFenton, at least you can check that this fixes the initial issue with cache

OK, I will do that, but not tonight.

**Comment by CharlieFenton** [comment]
@AenBleidd But how do I clone your changes into my feature branch from yours, or make commits to this branch? I have already deleted my branch when I closed #4619, so I will have to create a new brand and a new PR.

**Comment by AenBleidd** [comment]
@CharlieFenton, you can do this next way:

```
git checkout -b AenBleidd-vko_fix_cache_issue master
git pull https://github.com/AenBleidd/boinc.git vko_fix_cache_issue
```

**Comment by CharlieFenton** [comment]
@AenBleidd In my test branch [here](https://github.com/BOINC/boinc/pull/4625/commits/8ee751b67aa3808c8efd84a2bacc4458a9de76f2) It is rebuilding the cache even though I removed the patch to force a rebuild. So this appears to not work correctly. But I will try again after this I run is finished, changing a different file to trigger another CI run.

**Comment by CharlieFenton** [comment]
[Here ](https://github.com/BOINC/boinc/runs/5060395122?check_suite_focus=true) is the CI output from my first run, with the patch to force a cache rebuild in _3rdParty/buildMacDependencies.sh_.

**Comment by CharlieFenton** [comment]
My test PR is #4625 where the second run is not finding the cache created in the first (original) run.

**Comment by CharlieFenton** [comment]
I just ran another test PR #4626 and found that a newly created branch off master and PR normally do not build a new dependency cache for MacOS, but this PR #4622, and my PR #4625 which branched  of this one both did build a new cache instead of using the existing one. I believe my PR #4625 should have used the same cache your #4622 had previously created. But i am still investigating.

**Comment by AenBleidd** [comment]
@CharlieFenton, this is basically the problem of the GitHub Actions cache mechanism: it saves multiple caches (based on hash) so when you force a rebuild - it will definitely do a rebuild even if the cache will be found, but when you change it back - old cache will be used because it will be found by the cache, so the only way to not use the old cache is to add smth to the files that affect the cache to make it unique again.
I can basically change it to self-implemented cache mechanism (which will take time, of course, but still possible to do) to work the way similar to TravisCI way when only last cache for every CI flow was saved.
Probably I'll start working on its implementation this weekend.

**Comment by CharlieFenton** [comment]
After changing a different file (one that is not used by the build) the next CI run of PR #4625 did find and re-use the old cache and built without errors. [Here](https://github.com/BOINC/boinc/runs/5061646220?check_suite_focus=true) is the build log from that one. So it does appear that your changes fixed the cache problem. I will now do another small change to trigger another CI run to confirm it is working correctly and will report back. If i t works correctly, shall I merge it into master?

I will also run some tests on my PR #4626 to see if I can get more information on why the build was failing before your fix.

**Comment by AenBleidd** [comment]
@CharlieFenton,

> If i t works correctly, shall I merge it into master?

Yes, go ahead.

Thanks for the testing.

**Comment by CharlieFenton** [comment]
My [last test](https://github.com/BOINC/boinc/runs/5063163956?check_suite_focus=true) worked again, so I think you have fixed the cache issue. But I will wait to merge this so that you can continue to reproduce the MacOS build errors in branches off master. This will be needed to debug why CI thinks the build succeeded when it failed. Please let me know when I should merge.

**Comment by CharlieFenton** [comment]
> when you force a rebuild - it will definitely do a rebuild even if the cache will be found, but when you change it back - old cache will be used

I finally was able to determine what missing symbols caused the linker errors for MacOS, and I think we may be misunderstanding the problem. I suspect that maybe the dependency cache for GIT Master may out of date, and that is the cache being used for all branches created from master. How we can we remove the old cache from master and force a new cache build there? 

To summarize what I found: it appears that libcurl is looking for the libnghttp2 and libidn2 libraries, which are not present on the Mac by default. I updated the libcurl build script on 16 November 2021 to not require those libraries in commit 4010e8d2db which you merged into master with commit 7d01ee565e. The change added the following to the configure command:
`--without-libidn --without-libidn2 --without-nghttp2 --without-ngtcp2 --without-nghttp3 --without-quiche
`
I rebuilt the cache on my feature branch for testing, but this did not trigger a cache rebuild in master, and I suspect the master cache has not been rebuilt since before then. We need to find a way to ensure that the master cache is properly rebuilt when such changes are made. I also wonder whether the cache will automatically be rebuilt when the Xcode project and dependent library build scripts are updated to use a new version of a dependent library. This may also be an issue for other platforms besides MacOS.

I also wonder if your changes in this PR #4622 gave the appearance of solving the problem only because by adding a new items to the cache in each *.yml file you forced a one-time cache rebuild, but that this one-time change might not solve this problem for future changes of the sort I made on 16 November.

Should I do a commit directly to master of _3rdParty/buildMacDependencies.sh_, adding `doclean="yes"` to force a cache rebuild, and then doing another commit with that removed? Will that work? If I do this, I can create a new test feature branch from master and a new test PR to see i f that solves the problem without your changes in this PR #4622. What do you think?

**Review by CharlieFenton — COMMENTED** [review]
Please see my [previous comment](https://github.com/BOINC/boinc/pull/4622#issuecomment-1029854463)

**Comment by AenBleidd** [comment]
> Should I do a commit directly to master of 3rdParty/buildMacDependencies.sh, adding doclean="yes" to force a cache rebuild, and then doing another commit with that removed? Will that work? If I do this, I can create a new test feature branch from master and a new test PR to see i f that solves the problem without your changes in this PR https://github.com/BOINC/boinc/pull/4622. What do you think?

Unfortunately, no. GitHub Acvtions saves several caches.
The situation is next:
- Let's say, current hash on master is XXXX
- You do a commit, hash changes to YYY, cache rebuilds
- You do another commit to revert your change, hash becomes XXX again, and older cache will be used.

I can include XCode project files to hash, so when you change XCode project files without changing build scripts, hash will change and cache will be invalidated.

If you want this - just tell me what files to include in hash and I'll do this (or you can do this by yourself, I think it shouldn't be too complicated for you since you see how I added YML files to the hash).

Please tell me what you think.

**Comment by CharlieFenton** [comment]
In that case, we should probably add the following to the hash:
3rdParty/buildMacDependencies.sh
mac_build/setupForBOINC.sh
mac_build/buildopenssl.sh
mac_build/buildc-ares.sh
mac_build/buildcurl.sh
mac_build/buildWxMac.sh
mac_build/buildfreetype.sh
mac_build/buildFTGL.sh

The above should take care of all changes to the dependent libraries for MacOS, and also if we add or remove needed libraries. Please do **not** add the Xcode project to the hash. That is not needed because changes to the Xcode project should not affect the dependent libraries and it would trigger unnecessary cache rebuilds for every change to the project.

You may also want to add  the other _3rdParty/build*.sh_ files to the appropriate hashes. I don't know whether the .yml files which you added in this PR #4622 still need to be part of the hash; I will let you decide that.

Let me know when you have finished this and I will merge it into master. That should of course immediately cause a cache rebuild so I expect that will fix the build errors for now. But I don't know how we will be able to determine whether it fixes it for future changes of the type I made on 16 November. Do you have any thoughts about that?

**Comment by AenBleidd** [comment]
@CharlieFenton, all these files should be already in hash for OSX: https://github.com/BOINC/boinc/blob/35e3d70704b8431fa91b7fe943f87ec1d4882048/.github/workflows/osx.yml#L29

So my PR should fix the issue that we have now.
For the possible future cases I can switch to our own cache implementation (that I can implement) and store only 1 cache for every flow (that should make it the same way TravisCI did and that is more predictable in my opinion).

I think we're good to go with current solution, and when I will be ready with our cache implementation, we can test this properly together and decided whether it's better or not.

**Comment by AenBleidd** [comment]
Ah, no, we are missing one file, `mac_build/setupForBOINC.sh`
I'll add it to my PR now

**Comment by CharlieFenton** [comment]
I will merge this after all checks have run, but probably tomorrow since I will be going to bed soon.

**Comment by AenBleidd** [comment]
@CharlieFenton, thank you for your help!

**Review by CharlieFenton — APPROVED** [review]

**Comment by CharlieFenton** [comment]
@AenBleidd Thank you for explaining the use of a hash for the dependency cache under Github Actions. Now that I understand how tis works, I am confident that these changes are the correct solution for MacOS, so I don't feel that you need to spend time on creating a custom cache implementation. But I strongly recommend doing the same thing for the other platforms as you did for MacOS. 

But I don't know how you would do this for the vcpkg runs to assure that the CI runs will use a cache with the same library versions as are being used for release builds.

**Comment by AenBleidd** [comment]
@CharlieFenton, other platforms should be already ok with this. I checked build scripts and looks like all of them already affect the  hash.
Regarding vcpkg, we use completely different cache mechanism because Github Actions cache is not suitable for it, and it works fine also.
Thank you for merging this.

**Pull request merged**
