### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@CharlieFenton, sorry for the delay with localizations. Please review

**Review by CharlieFenton — APPROVED** [review]
While I approve this, the new string I specifically care about has been translated in only 6 languages at this point in time. It may be worthwhile to send a message via the boinc_loc email list asking the translators to update the files for their languages, or to let us know if they no longer can help us. 

I did not received the announcement from Transifex; when I investigated I found that emails for announcements was turned off in my Transifex account. There may be others in that situation, and it's possible that the email address we have for some translators are no longer valid. (Do we get notified when emails sent by Transifex or boinc_loc bounce?

**Comment by AenBleidd** [comment]
@CharlieFenton, please merge this PR.
I'll send a notification in a some other channels (including mailing list).
Regarding your question, not sure we are notified in such cases.

**Comment by AenBleidd** [comment]
@CharlieFenton, translations were updated. Not sure there will be more in the near future since there was no activity on Transifex during last week. I suggest you to merge this PR into your master and your release branch and release a new version for OSX

**Comment by CharlieFenton** [comment]
@AenBleidd Is it Ok if I merge this PR into master first?

**Comment by AenBleidd** [comment]
@CharlieFenton, yes

**Pull request merged**
