### PR TITLE
[CI] Clean deploy python script

### PR DESCRIPTION
**Pull request by talregev**
Clean deploy python script.

### CODE REVIEW

**Comment by AenBleidd** [comment]
Both these files are present in the output folder. What is the intention to not put them to the output zip?
image

**Comment by talregev** [comment]
> Both these files are present in the output folder. What is the intention to not put them to the output zip?

This files already find in the list. If you look closely in all the list, you will find I delete the duplicate lines.

**Review by AenBleidd — APPROVED** [review]

**Comment by talregev** [comment]
I look in your list, and I want to change some of the apps names.
Why there is a number 6.1? also remove the name windows and platform from their names.

**Comment by talregev** [comment]
And we don't compile for 32bit (x86_x64). Is it a left over files in your local machine?

**Comment by AenBleidd** [comment]
@talregev, `6.1` is there for historical reasons, and could be removed.
`windows` and `x86_64` should still stay there as this is represent the current naming scheme

**Comment by talregev** [comment]
I also want to remove the other weird number like 26155, and other number. 
I will make another PR.

**Comment by AenBleidd** [comment]
> I also want to remove the other weird number like 26155, and other number.

This is not a weird number, this is a version and it also should be kept as-is

**Comment by talregev** [comment]
You allow me to remove 6.1 regular version number, but not weird version number?

**Comment by AenBleidd** [comment]
> You allow me to remove 6.1 regular version number, but not weird version number?

Because `6.1` is outdated. Others - no

**Comment by talregev** [comment]
Can you do it yourself?

**Comment by AenBleidd** [comment]
> Can you do it yourself?

Yes

**Pull request merged**
