### PR TITLE
[VS2019] Add boinccas.vcxproj

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@davidpanderson, please review

**Comment by davidpanderson** [comment]
boinccas built successfully but only after I changed line 10 of boinccas.rc from
#include "afxres.h"
to
#include <windows.h>

**Comment by AenBleidd** [comment]
@davidpanderson, strange, on CI it was built with no issues. But I think it's ok to apply this change. I'll do this.

**Comment by AenBleidd** [comment]
@davidpanderson, I changed boinccas.rc a little bit to be similar to all other our resources. Should be fine now. Could you please review it again? Thanks is advance.

**Pull request merged**
