### PR TITLE
[AppVeyor] Skip commits that are not related to Windows build

### PR DESCRIPTION
**Pull request by AenBleidd**
Add 'skip_commits' section to skip commits that are not related to Windows builds.
This PR contains changed to skip on;y most used folders and do not contain ones that are changed very rare.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Ready for review

**Comment by CharlieFenton** [comment]
A small suggestion: It would be helpful if in the future you included _Appveyor_ in the title of the PR. I see you did include _Appveyor_ in the branch name; thank you for doing that.

**Comment by AenBleidd** [comment]
@CharlieFenton, sorry for that, thank you for the suggestion.

**Comment by ChristianBeer** [comment]
You should add `sched/`, `db/`, `tools/`, `vda/` and `xcompile/` to the list. The list is very long but specifying only the directories where we build for windows is not very future proof as one tends to forget to add new directories to the list.

**Comment by TheAspens** [comment]
I defer to @ChristianBeer.  I don't have any objections.  Thanks.

**Comment by AenBleidd** [comment]
I agree with all changes except sched folder. It is used by boincsim project. Maybe somewhere else but I didn;t check all places where it can be used, one is enough as from my POV

**Comment by JuhaSointusalo** [comment]
Umm... `boincsim` isn't built by default and can't be built because it's totally broken.

**Comment by AenBleidd** [comment]
@JuhaSointusalo maybe, but this project is included in the solution. So once someone will decide to fix it he will require CI build. So I'd prefer do not add this folder to excluded one

**Comment by AenBleidd** [comment]
By the way, I'll try to fix it and make at least compilable

**Comment by JuhaSointusalo** [comment]
Well yes maybe. I once poked it to see if it can be fixed but gave up after realising it has been broken for ages and nobody is using it. I don't even really know what it was used for if it ever worked.

**Comment by ChristianBeer** [comment]
I would like to include `sched` to the list but as @AenBleidd said the boincsim Windows build uses the file `sched\edf_sim.cpp`. I'm fine with that for now but if that could be moved elsewhere we would have a better separation between client and server and the platforms for each.

**Comment by AenBleidd** [comment]
@CharlieFenton, could you please review this pull request? Thanks

**Comment by ChristianBeer** [comment]
I'll merge this now so it is underway. Additional directories can still be added later.

**Comment by AenBleidd** [comment]
@ChristianBeer, thank you. I'll open new pull request with new folders mentioned by @CharlieFenton as soon as I'll verify that none of the files within these directories is used for Windows build (just to be sure).

**Pull request merged**
