### PR TITLE
Improve and fix Android build scripts

### PR DESCRIPTION
**Pull request by brevilo**
A lot of house-keeping and fixing. These commits (see them for details) facilitate Android builds.

Related to #1829.

### CODE REVIEW

**Comment by brevilo** [comment]
Ok, but it's already outdated in a number of ways 🙁

**Comment by davidpanderson** [comment]
Thanks,Oliver.

**Comment by brevilo** [comment]
Thanks guys 👍

**Comment by brevilo** [comment]
The doc updates are as follows:
* [AndroidBuildClient](http://boinc.berkeley.edu/trac/wiki/AndroidBuildClient?action=diff&version=15&old_version=13)
* [AndroidBuildApp](http://boinc.berkeley.edu/trac/wiki/AndroidBuildApp?action=diff&version=26&old_version=25)

**Pull request merged**
