### PR TITLE
Update development version to 7.11

### PR DESCRIPTION
**Pull request by RichardHaselgrove**
Update master ready for the next development cycle

### CODE REVIEW

**Comment by JuhaSointusalo** [comment]
Please use `git pull` to update your copy. It just doesn't look right to have that merge commit there.

**Comment by RichardHaselgrove** [comment]
Yes, it did that last time too. I forked to a private repo under my account so I could commit changes: then had to update my private copy ready for the next change. GitHub Help said I had to use a pull request to update, and GitHub itself allowed that to happen - but won't let me remove the evidence. Now, performing what I thought would be the same help search, it's telling me to use the command line:  https://help.github.com/articles/syncing-a-fork/. I'll try that next time, along with the github desktop and tortoise git GUI, both of which I'm having to use to make the commits in the correct branch. Argh.

I agree the merge FROM boinc/master is ugly, but I think it's of no effect - see #2302

**Comment by TheAspens** [comment]
I looked at this history around #2302 and other than the confusing pull request notation I don't see anything that will cause an issue if that pull request is merged.   

In the future, please follow the process described in the [development workflow document](https://github.com/BOINC/boinc-policy/blob/master/Development_Workflow.md): The link for "Fork and Pull" goes to https://gist.github.com/Chaser324/ce0505fbed06b947d962 which describes the desired way to create and maintain a fork for using during contributions.

**Comment by RichardHaselgrove** [comment]
OK, that all seems consistent now. The takeaway keywords are 'Fetch' to synchronise two remote repos on Github (project and personal), and 'Pull' to update a local clone on hard disk. Fetch is available in the GUI, or bash is a right-click away. When some new commits have built up in master, I'll experiment with those. Thanks.

**Comment by TheAspens** [comment]
Are we waiting for anything else?  Or can we go ahead and merge this?

**Comment by RichardHaselgrove** [comment]
The 'effective' commit (0f628055b7f64b875902501f4c3ab55359a7313b) is trivial and atomic - it does nothing except what's stated on the subject line. The rest is procedural - teaching a newbie to use Git efficiently. I'd urge commit and spare my blushes. :-)

**Pull request merged**
