### PR TITLE
Fix issue #1423

### PR DESCRIPTION
**Pull request by AenBleidd**

### CODE REVIEW

**Comment by CharlieFenton** [comment]
Where is the new icon for the task bar? This will not build without the XPM file.  Also, you have not included the corresponding change and icon for the Mac Dock, as I explained in reply to your earlier posting <https://github.com/BOINC/boinc/issues/1421#issuecomment-151687660>.  

BOINC is cross-platform, so any changes to the UI must work for Macintosh and Linux as well as MS Windows.

**Comment by AenBleidd** [comment]
@CharlieFenton, I'm sorry but this fix is not about the changing the icon. This one is fix only pop-up menu

**Comment by CharlieFenton** [comment]
I apologize; I was confusing this with issue #1421.

However, I just tested this change and it also checks and disables the "Snooze GPU" menu item when CPU activity is set to "suspend" (RUN_MODE_NEVER), which I believe is not corrected nor what you intended.

**Comment by AenBleidd** [comment]
@CharlieFenton, Hm, the main idea was to check and disable "Snooze GPU" when "Snooze CPU" is checked. Please correct me if I'm wrong and there is some another workflow which I don't know.
Thanks

**Comment by ChristianBeer** [comment]
@AenBleidd can you please add a description to pull requests in the future? This would prevent such confusions. Referencing the issue is ok but please also write what you did or intended with the change.

**Comment by AenBleidd** [comment]
@CharlieFenton, sure, I will. Thank you for advice.

**Comment by CharlieFenton** [comment]
The logic here is a bit more complex than one might expect at first, due to the interaction with the Activity menu.

I have committed a fix for this problem, and added code to disable the Snooze GPU menu item in some additional cases where appropriate. 

When committing changes, please include in the commit message a description of the problem being solved or the purpose of the change, in addition to "Fix issue #xxxx" so that the commit log is self-explanatory without a need to go back to the original issue.  Also, please follow our convention of prefixing all commit messages with the BOINC component affected, such as "MGR:", "client", :server:". etc.  This will make it much easier to understand the change history.  Thank you.

**Pull request merged**
