### PR TITLE
db_purge: use zlib

### PR DESCRIPTION
**Pull request by bema-ligo**
The current `db_purge` pipes its output through external programs for compression, which leads to bad error handling and possible data loss (e.g. if the disk runs full). Add a compress option to use zlib to produce gz files without relying on an external program / pipe.

### CODE REVIEW

**Comment by AenBleidd** [comment]
I think this pull request should be splitted into two: first about xml and second about zlib

**Comment by bema-ligo** [comment]
@AenBleidd 
> I think this pull request should be splitted into two: first about xml and second about zlib

Which of the two PRs should the third commit belong to? Logically it belongs to the XML one, but technically it changes only db_purge and requires the zlib commit.

**Comment by AenBleidd** [comment]
23f0f6e578631811beb705e91bf3f620313fef9b and ad4cd5ce92011393f914556fa9f5e6ac17ec5afa are related to xml only so they can be moved to a separate pull request as far a I see.

**Comment by bema-ligo** [comment]
@AenBleidd moved 23f0f6e and ad4cd5c to #2006

**Comment by ChristianBeer** [comment]
Sorry for creating the conflicts by merging #2021 before this. I didn't see that there was a slight overlap. Can you please rebase or merge master again?

**Comment by bema-ligo** [comment]
@ChristianBeer Not easily, i.e. automatically. This will require more work, and probably re-building the branch, losing the references. I'll try to keep the original SHA1s in the commit messages, though.

**Comment by bema-ligo** [comment]
The conflicting functionality was split out in #2031. Original SHA1s of this branch were kept in "cherry-picked from" comments.

**Comment by bema-ligo** [comment]
From a recent occurrence on Einstein@Home I can confirm that the current db_purge will inevitably lead to data loss when using compression and the disk runs full, and that this PR definitely fixes it. So I strongly recommend to merge at least this one.

**Comment by davidpanderson** [comment]
Thanks!

**Pull request merged**
