### PR TITLE
Manager: Fix #1083 EventLog window GUI glitch with selected unfocused…

### LINKED ISSUE #1083: GUI Glitch - Actions on 2+ selected rows appear to leave every other row unselected
**Reported by JacobKlein on 8 Jun 41333780 03:33 UTC**
If 2+ rows are selected, and an action is performed (like "Show Graphics"), the UI then shows only every other row selected, but actions indicate the initial rows are still selected (like "Properties" is greyed out)

Another example would be clicking "Copy" when having several consecutive rows selected in the Event Log.

An even more interesting case would be clicking "Copy" when having several random rows selected in the Event Log.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1107

### PR DESCRIPTION
**Pull request by AenBleidd**
… rows.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
This pull request is more clear then previous one: #2137

**Comment by AenBleidd** [comment]
Changes are made according to @JuhaSointusalo comments.

**Comment by JuhaSointusalo** [comment]
My idea wasn't well tested and that shows - the build fails on Linux and Mac.

```
DlgEventLog.cpp: In member function ‘bool CDlgEventLog::Create(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int)’:
DlgEventLog.cpp:257:50: error: ‘wxListCtrl’ is not a base of ‘CDlgEventLogListCtrl’
     const wxColour stripe = m_pList->wxListCtrl::OnGetItemAttr(1)->GetBackgroundColour();
                                                  ^
```
That's because Linux and Mac use `wxGenericListCtrl` directly. That could be fixed by changing the base class used in the call but I'm having second thoughts about this. This error tells me the code is getting too clever.  I think it will be better to copy the colour setting code from `wxListCtrlBase::EnableAlternateRowColours` here rather than add more cleverness (and eventually break the build in more clever ways).

I can make a PR that I promised earlier that fixes this and adds more error checking in a bit if that's ok with you.

In related matters, have you reported or are you working on reporting the problem to wxWidgets developers? I started poking the list control sample the other day to turn it into something reportable. If you are not working on the report I could finish it up.

**Comment by AenBleidd** [comment]
@JuhaSointusalo,

> I can make a PR that I promised earlier that fixes this and adds more error checking in a bit if that's ok with you.

Of course this is OK.

> In related matters, have you reported or are you working on reporting the problem to wxWidgets developers? I started poking the list control sample the other day to turn it into something reportable. If you are not working on the report I could finish it up.

I do not work on the report so please finish it.

Thank you

**Pull request closed without merging**
