### PR TITLE
web: fix various XSS vulnerabilities

### PR DESCRIPTION
**Pull request by davidpanderson**
Most of these involve putting user text in error messages. Use htmlspecialchars() for this.

filenames: require POSIX portable names

### CODE REVIEW

**Review by AenBleidd — APPROVED** [review]

**Comment by lfield** [comment]
There is one small issue which I have put in the comments.

**Comment by davidpanderson** [comment]
Where in the comments?

**Comment by lfield** [comment]
Just above.

**Comment by davidpanderson** [comment]
the comments of this PR?  I'm not seeing it.

**Comment by lfield** [comment]
Yep. https://github.com/BOINC/boinc/pull/5968/files/443889e7bcee9ac5ef06afe9e8c6b25814b78b72#diff-97e70dc5379ea2d29ea02ed3832e7f163355342bc52397071279f176f8ec1caf

"Bug 209 is still there. It would require .htmlspecialchars($req) on line 302"  in job_file.php

**Comment by davidpanderson** [comment]
github didn't show a comment there for some reason.  Anyway, fixed now

**Comment by lfield** [comment]
LGTM

**Comment by AenBleidd** [comment]
Merging this to master since this already merged to the release branch.

**Pull request merged**
