### PR TITLE
[Client] Change default end time in daily schedules from 23:59 to 24:00

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Small fix related to #2583 and #2589

**Comment by CharlieFenton** [comment]
@davidpanderson: I don't know whether the web-based preferences also have a default value which needs changing. But I just now looked at the computing preferences on the SETI@home website and see that the "Compute only between" and "Transfer files only between" fields allow only times on the hour (0:00, 1:00, 2:00 ... 23:00.) There is no way to enter times like 3:30.

**Comment by AenBleidd** [comment]
@TheAspens, @RichardHaselgrove, @davidpanderson, could you please take a look at this PR and decide whether it can be merged or not. Thanks

**Comment by TheAspens** [comment]
@AenBleidd - looks good - thanks for the fix.  I reviewed it and also noted that @CharlieFenton set those defaults originally so since he approved the change as well I think this is good.

The comments about the web interface should be handled in a different issue/pull request if a change is required.

**Pull request merged**
