### PR TITLE
[Linux] Openclapp in CI

### PR DESCRIPTION
**Pull request by talregev**
Add opencl check to apps

### CODE REVIEW

**Review by AenBleidd — APPROVED** [review]

**Comment by LocutusOfBorg** [comment]
@talregev sorry but this pull request regressed the build for debian and ubuntu.
Don't ask me why but revering it works, somewhat with your changes ld refuses to link shared libraries and fails badly
Look for example:
last master build:
https://launchpadlibrarian.net/527562892/buildlog_ubuntu-hirsute-amd64.boinc_7.18.0+dfsg+git20210312+r24856~r79~ubuntu21.04.1_BUILDING.txt.gz
and with this pull request reverted:
https://launchpadlibrarian.net/527579012/buildlog_ubuntu-hirsute-amd64.boinc_7.18.0+dfsg+git20210312+r24856~r80~ubuntu21.04.1_BUILDING.txt.gz

**Comment by AenBleidd** [comment]
@LocutusOfBorg, on ci it's built on Ubuntu with no issues

**Comment by talregev** [comment]
@LocutusOfBorg I will look on the logs you post here.
Can you help and type here the errors with some context? thank you.

**Comment by LocutusOfBorg** [comment]
We build with shared libraries not static
```
dh_auto_configure -- --build x86_64-linux-gnu --with-boinc-platform=x86_64-pc-linux-gnu --with-boinc-alt-platform=x86_64-linux-gnu --prefix=/usr --bindir=/usr/bin --localstatedir=/var/lib --enable-client --enable-manager --enable-dynamic-client-linkage  --disable-fcgi --enable-libraries --enable-unicode --enable-shared --enable-static --enable-dynamic-client-linkage --with-ssl --with-x CFLAGS="-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/boinc-7.18.0+dfsg+git20210312+r24856~r80~ubuntu20.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -O3 -funroll-loops -fforce-addr -ffast-math"
	./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --build x86_64-linux-gnu --with-boinc-platform=x86_64-pc-linux-gnu --with-boinc-alt-platform=x86_64-linux-gnu --prefix=/usr --bindir=/usr/bin --localstatedir=/var/lib --enable-client --enable-manager --enable-dynamic-client-linkage --disable-fcgi --enable-libraries --enable-unicode --enable-shared --enable-static --enable-dynamic-client-linkage --with-ssl --with-x "CFLAGS=-g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/boinc-7.18.0+dfsg+git20210312+r24856~r80~ubuntu20.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -O3 -funroll-loops -fforce-addr -ffast-math"
```
the check if the linker can provide shared library now its broken, this is why it fallsback into static ones, breaking the Debian/Ubuntu builds

**Comment by talregev** [comment]
I am trying to reproduce your problem in our ci.
Can you submit a PR with your flags that will break the build?

**Comment by talregev** [comment]
@LocutusOfBorg Also if you can check your build on my branch:
https://github.com/talregev/boinc/tree/TalR_android_all_apps

**Comment by talregev** [comment]
@LocutusOfBorg If you install only the client and manger (like you show me in the line), you shouldn't install the package `ocl-icd-opencl-dev`. It only of one app. apps it for projects creators, and not for users that use boinc client and manager.

**Comment by talregev** [comment]
I propose a fix: #4268.

**Pull request merged**
