### PR TITLE
lib: don't include config.h from .h files

### LINKED ISSUE #2964: config.h is not installed
In #1624 @tomasbrod mentioned:

> I am affected by this issue. config.h is not installed. Almost all header files installed in /usr/include include that "config.h" file making them useless without the missing header.

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #2964

### CODE REVIEW

**Comment by davidpanderson** [comment]
Oops!  I also included a minor change to allow invite code for create-account RPCs

**Comment by AenBleidd** [comment]
I'll take over this

**Comment by davidpanderson** [comment]
Thanks!

**Comment by davidpanderson** [comment]
I fixed the build errors

**Comment by AenBleidd** [comment]
It still contains non-related changes. Let me take a look at it later after the call. Probably I'll have even cleaner fix :)

**Comment by AenBleidd** [comment]
Fixed via #4063

**Pull request closed without merging**
