### PR TITLE
Fix bug that caused bad values to be written to cc_config.xml

### LINKED ISSUE #3247: Manager: writes garbage to cc_config.xml
**Describe the bug**
When the 'Event log options...' dialog is used to modify the active set of Event Log flags, garbage is written to cc_config.xml.

**Steps To Reproduce**
1. Open Event Log Options dialog, change a setting, apply or save your changes
2. Inspect the contents of cc_config.xml visually
3. (optional) Shut down and restart the BOINC client...

**Expected behavior**
Existing option settings are left unchanged'

**Screenshots**
Original entries in cc_config.xml:
```
    <options>
        <abort_jobs_on_exit>0</abort_jobs_on_exit>
        <allow_multiple_clients>1</allow_multiple_clients>
        <allow_remote_gui_rpc>0</allow_remote_gui_rpc>
        <disallow_attach>0</disallow_attach>
```

New entries in cc_config.xml:
```
    <options>
        <abort_jobs_on_exit>1069290768</abort_jobs_on_exit>
        <allow_gui_rpc_get>0</allow_gui_rpc_get>
        <disallow_attach>0</disallow_attach>
```

**System Information (please complete the following information):**
 - OS: Windows, Linux (Mac untested)
 - BOINC Version: 7.16.1 (new in this version)

**Additional context**
Possibly came about as a side effect of #3214 (added <allow_gui_rpc_get>), but I haven't tracked it down yet - I'll look over the weekend.

With a value >0 in abort_jobs_on_exit - guess what happens on exit! That's the blocker.

Problem was noticed as a result of using the **release** version of 7.16.1 from @LocutusOfBorg PPA, verified with self-build version of boincmgr for Windows (no test version available yet).

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #3247

### CODE REVIEW

**Comment by TheAspens** [comment]
Thanks for the fix!

**Comment by RichardHaselgrove** [comment]
Kevin beat me to it, but tested and confirmed: problem fixed with the appveyor Windows builds.

This needs to be duplicated into the release branch and a new PPA (@LocutusOfBorg) made as soon as possible, because it's already out in the wild.

**Comment by LocutusOfBorg** [comment]
thanks, uploaded with high urgency, to unstable and buster backports!

**Comment by Germano0** [comment]
Backported to Fedora / EPEL too

**Pull request merged**
