### PR TITLE
job submission: don't error out if standard templates missing; change comment in transitioner

### PR DESCRIPTION
**Pull request by davidpanderson**
If you specify the input or output templates,
the standard ones (appname_in, appname_out) don't need to exist.

Also, in create_work():
- don't read the output template; just check that it exists.
- deprecate the result_template_filepath arg; redundant

### CODE REVIEW

**Comment by ChristianBeer** [comment]
I don't really like that the changes to `create_work()` are hidden in the commit message. IMHO they are independent from the remote submission changes and warrant their own commit so the commit subject is more descriptive.

**Comment by davidpanderson** [comment]
create_work is part of remote job submission.

**Comment by ChristianBeer** [comment]
`create_work` is a standalone program that can be used for local job submission as well as remote job submission. You are changing the function which affects both use cases. My point is that someone looking for a change made to the standalone program doesn't recognize that a commit message titled "remote job submission" is affecting `create_work` too.

What explanation do you have for the comment change to the transitioner? This one is certainly not part of remote job submission.

In my eyes 921dcd14982c3f8e102ae37a2a736af2b9222b4f is not atomic and contains unrelated changes.

**Comment by davidpanderson** [comment]
I changed the title.  Any problem w/ the content of the PR?

**Comment by ChristianBeer** [comment]
Changing the title of the PR doesn't change the commit message where the unrelated change is embedded in. This is not what is meant by atomic commits. I stand by my objection which is about atomicity not about the quality of the code (which I think is fine).

**Pull request merged**
