### PR TITLE
AndroidBOINC: Fix coding style and formatting (resources)

### PR DESCRIPTION
**Pull request by GITNE**
No functional changes, just cleanup.

### CODE REVIEW

**Comment by GITNE** [comment]
The Travis build has been broken by commit b6c0d75a8c268e5a8b39fd44917f2f801061783e.
Eh, do you build before you commit/push?

**Comment by GITNE** [comment]
I do not exactly understand why this pull request should have merge conflicts since I did not touch any files except for the Android project.

Is there anything I can or should do?

**Comment by romw** [comment]
I suspect it is because I pulled in one of the localization changes you made after this pull request.

I won't know the details until somebody attempts to follow the instructions GitHub is recommending.

**Comment by GITNE** [comment]
I now realize, it might have been better if I would have split this pull request into more commits, especially the language files.

**Comment by ChristianBeer** [comment]
I think it would be a good idea to create a new pull request that has no conflicts. Either cherry-pick and resolve the commits on top of master or create new commits by fixing the coding style again starting with current master.

**Comment by AenBleidd** [comment]
This PR will be completely broken after #1703
Maybe someone can take a look at it?

**Comment by ChristianBeer** [comment]
Maybe @denravonska can take a look at the intended changes and apply them to the files after #1703 got merged.

**Comment by brevilo** [comment]
Since this PR doesn't apply anymore (after #1703): do you want to redo it? Also, which auto-formatter did you use and with which ruleset? We should make that available such that future style-checks could be automated.

**Pull request closed without merging**
