### PR TITLE
NeedRunDaemon option should be applied when connecting to localhost o…

### PR DESCRIPTION
**Pull request by AenBleidd**
…nly.

This commit fixes a situation when trying to connect to remote client with option 'Run client' on leads to unability to connect to selected client.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
For some reason github decided that this pr doesn't required travis ci build I put direct link here: https://travis-ci.org/BOINC/boinc/builds/438855940

**Comment by RichardHaselgrove** [comment]
I need to check this in the morning. At the moment, it reads with the wrong polarity - in my testing (over LAN), specifying 'no daemon' prevented connection. But the virtual machine case is different.

**Comment by AenBleidd** [comment]
Yes, this particular pr fixes the case when you specifying --no-daemon option when trying to connect to the client over LAN. Now it should works.
Virtual machine case is different, you're right but I still can't reproduce it on my side. Will try again later but looks like it doesn't really connected to --no-daemon option.

**Comment by AenBleidd** [comment]
> I won't merge just now in case it messes the base for any WIP, but I'd ask any more experienced Git user to merge when appropriate.

WIP PRs just should be rebased before merge but I'm OK waiting for merge. It is not a critical issue fix so it could wait

**Comment by RichardHaselgrove** [comment]
Problem found with this commit.

On normal launch, Manager shows "Connected to localhost (7.14.2)" in status bar. You can then run, from the File menu, "New BOINC Manager window...", which displays a customised version of the Select Computer dialog in front of the (blank - disconnected) new window:

new boinc manager window

Filling in a valid remote hostname and password connects the new window to localhost.

beta v7.14.2 and alpha artifact c9bacd5a both connect correctly to the remote client: it's only with a local build, with this patch applied over v7.14.2 source code, that the problem appears. Testing under Windows 7.

**Comment by RichardHaselgrove** [comment]
@AenBleidd - I need to **withdraw** my approval of this PR for the time being, because of the problem. But I can't persuade Github to do so.

**Comment by AenBleidd** [comment]
Ok, will check and fix this. Thank you for testing this.

**Comment by RichardHaselgrove** [comment]
Thanks. I should have said: if you subsequently do a normal 'Select computer...' in the new window, it attaches to a remote client just fine. It's only the initial creation that fails.

**Comment by RichardHaselgrove** [comment]
I'll try to test and update my review in the morning, but I may get called away to deal with issues that have arisen suddenly this evening. I'll let you know if I have to duck out for a while.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, should be fixed now.

**Comment by AenBleidd** [comment]
Could someone merge this, please?

**Comment by AenBleidd** [comment]
Should be fixed now

**Comment by AenBleidd** [comment]
@JuhaSointusalo, did you have a chance to review this one more time?

**Comment by JuhaSointusalo** [comment]
Well, actually I haven't had the time earlier. I guess that would be on the
agenda today.

**Pull request merged**
