### PR TITLE
[osx][vcpkg][manager] Compile dependencies of osx manger with vcpkg

### PR DESCRIPTION
**Pull request by talregev**
Compile dependencies of osx manger with vcpkg.
I don't have a mac machine. I just compile it. It need to run and test it.

### CODE REVIEW

**Review by AenBleidd — CHANGES_REQUESTED** [review]
This need to be revisited after #5056 reviewed and merged since these two PRs both touch the same files

**Comment by talregev** [comment]
Can you check what illegals symbols I have? 
`./mac_build/boinc.vcpkg.xcodeproj/project.pbxproj`

**Comment by AenBleidd** [comment]
> Can you check what illegals symbols I have? `./mac_build/boinc.vcpkg.xcodeproj/project.pbxproj`

I don't think it's a good idea to have a separate project file for vcpkg build.
I strongly suggest to not duplicate it.
Remember, that `vcpkg` is **additional** way of handling dependencies and definitely not the default one when speaking about OSX.

**Comment by talregev** [comment]
> > Can you check what illegals symbols I have? `./mac_build/boinc.vcpkg.xcodeproj/project.pbxproj`
> 
> I don't think it's a good idea to have a separate project file for vcpkg build. I strongly suggest to not duplicate it. Remember, that `vcpkg` is **additional** way of handling dependencies and definitely not the default one when speaking about OSX.

I cannot. Each project have different names for libraries, also the vcpkg use more of them. so different libs.

**Comment by talregev** [comment]
I try to:
`unix2dos -c mac ./mac_build/boinc.vcpkg.xcodeproj/project.pbxproj`
And it didn't help. I need some help with these symbols.

**Comment by AenBleidd** [comment]
> I try to: `unix2dos -c mac ./mac_build/boinc.vcpkg.xcodeproj/project.pbxproj` And it didn't help. I need some help with these symbols.

Original file was just skipped from this check

**Comment by AenBleidd** [comment]
> I cannot. Each project have different names for libraries, also the vcpkg use more of them. so different flags of libs.

I strongly disagree. Better solution should be found instead of just making a duplicate of a project file

**Comment by AenBleidd** [comment]
Also, since we do not have a goal to move all projects to vcpkg, we can put it on hold and get back to it when we have time and efforts to make it in a good and easy way.
Supporting two duplicating projects is not a good and easy way.
That's why currently for Windows we have only one solution for VS2022 only, and no support of older versions of VS.

**Comment by talregev** [comment]
Can you run it and test it that it working? And share some screenshots?

**Comment by AenBleidd** [comment]
> Can you run it and test it that it working? And share some screenshots?

Nope. I don't have any OSX device

**Comment by talregev** [comment]
> Member

As you write here, you have limited access to osx device.
https://github.com/BOINC/boinc/issues/4892#issuecomment-1221231633

**Comment by talregev** [comment]
> > > > Can you run it and test it that it working? And share some screenshots?
> > > 
> > > 
> > > Nope. I don't have any OSX device
> > 
> > 
> > As you write here, you have limited access to osx device. [#4892 (comment)](https://github.com/BOINC/boinc/issues/4892#issuecomment-1221231633)
> 
> Yes, but cli only with no UI access, so useless for this particular testing

Will you try to x forward the gui like in linux?
https://www.businessnewsdaily.com/11035-how-to-use-x11-forwarding.html

**Comment by AenBleidd** [comment]
> Will you try to x forward the gui like in linux? https://www.businessnewsdaily.com/11035-how-to-use-x11-forwarding.html

No because it won't work. It is a very limited environment with very limited access.

**Comment by talregev** [comment]
Hi @CharlieFenton, I compile the dependencies with vcpkg along with osx project. It easier and better way to maintain the dependencies that constantly updated, and have a large of community that update it fast and reliable. We also can control the if we want to the versions for each dependency. Also control if we need to change and patch it in case wxwidgets as you did. 
Also if Microsoft will close this repo. This repo can be handle independently and completely open. 
So I compile boinc osx with all the recent libs. for wxwidgets compile it for 3.1.7. (From version 3.1.6 it needed additional libs to compile, it mean additional scripts and project to create for each lib). 

Can you test it that this project is running and no have some issue? Maybe you have other insights.

**Comment by CharlieFenton** [comment]
Please remember that I have very intentionally designed the Xcode project for a version of BOINC to fail if there is an attempt to build it with a different version of a dependent library tan the one which was originally used for that version of BOINC, to guarantee 100% reproducibility if built again, even years later. Do **not** change that.

This means that you must configure vcpkg to not update library versions automatically if you want to use it with MacOS.

**Comment by talregev** [comment]
> Please remember that I have very intentionally designed the Xcode project for a version of BOINC to fail if there is an attempt to build it with a different version of a dependent library tan the one which was originally used for that version of BOINC, to guarantee 100% reproducibility if built again, even years later. Do **not** change that.
> 
> This means that you must configure vcpkg to not update library versions automatically if you want to use it with MacOS.

As I mention before. We can control on each library for specific version. For now it only along side and not official, so I let it run for the most recent vcpkg versions.

**Comment by CharlieFenton** [comment]
> Can you test it that this project is running and no have some issue? Maybe you have other insights.

Sorry, I do not have time for that. The CI build should tell you whether there is a problem building it, but this will not tell us whether the code will work as intended. My experience has been that, especially with wxWidgets, updating the library often breaks things and requires patches to the library code to fix it.

**Comment by talregev** [comment]
> > Can you test it that this project is running and no have some issue? Maybe you have other insights.
> 
> Sorry, I do not have time for that. The CI build should tell you whether there is a problem building it, but this will not tell us whether the code will work as intended. My experience has been that, especially with wxWidgets, updating the library often breaks things and requires patches to the library code to fix it.

The code is compiled. How I can test it that it running and see it nothing break?

**Comment by AenBleidd** [comment]
> The code is compiled. How I can test it that it running and see it nothing break?
Even If I will stay on the same wxwidgets 3.1.5 as you did. How I will know for sure what I did is working?

Maybe you should just not touch anything you can't properly test?

**Comment by talregev** [comment]
> > The code is compiled. How I can test it that it running and see it nothing break?
> > Even If I will stay on the same wxwidgets 3.1.5 as you did. How I will know for sure what I did is working?
> 
> Maybe you should just not touch anything you can't properly test?

We can properly test it. I just asking from you that you have access to mac. I am doing for myself for Windows, Linux and Android.

**Comment by AenBleidd** [comment]
> I just asking from you that you have access to mac.

You're overestimating availability of my resources.

**Comment by CharlieFenton** [comment]
> How I can test it that it running and see it nothing break?

It is a great deal of work to do that. It requires installing it on a Mac computer and:
* Testing every dialog and every function.
* Running some projects.
* Carefully examining the displays in both Simple View and Advanced View make sure they are working correctly.
* Testing all the buttons and controls in both Simple View and Advanced View.
* Testing hiding and showing different columns.
* Making sure the project tasks succeed.

**Comment by AenBleidd** [comment]
I still don't like this solution with duplicate project file.
So I put it on hold.
Will review it later and try to check better solution for this.

**Comment by talregev** [comment]
> I still don't like this solution with duplicate project file. So I put it on hold. Will review it later and try to check better solution for this.

As you mention, it not replace the official way. We can insert it with duplicate project, and when we see it harder to add new libs or to track the libs we depends on. Usually the osx project don't change. Charlie like to keep it preserve. 
Please check that if it running to see if it worth to invest on this direction.

**Comment by talregev** [comment]
> > > I still don't like this solution with duplicate project file. So I put it on hold. Will review it later and try to check better solution for this.
> > 
> > 
> > As you mention, it not replace the official way. We can insert it with duplicate project, and when we see it harder to add new libs or to track the libs we depends on the osx scripts. Usually the osx project don't change. Charlie like to keep it preserve. Please check that if it running to see if it worth to invest on this direction.
> 
> I already see it harder because: 1 - I have no way to test that. And as @CharlieFenton correctly told, if it's building it doesn't mean that it's working. 2 - I have no experience with OSX to fix anything in case smth become broken on CI, and since this is not an official way of building OSX BOINC, I can't bother @CharlieFenton every time just to fix the CI 3 - We have other more important tasks to invest available time instead of supporting smth that is not used.

As you say you don't have experience with OSX, yet you compile the wholes example apps of OSX.
Also If you don't have no experience and something is broken, it more easier to disconnect the duplicate file then to try to fix the merge one.

**Comment by AenBleidd** [comment]
> For testing I agree, that why I asking you guys that you have access to mac and compiled stuff for mac to test it.

Again, I don't have full access to the GUI on OSX, so I can't test it.

> As you say you don't have experience with OSX, yet you compile the wholes example apps of OSX.

Because this was already there, just not on the CI, and the tools I added I could test on CI, because they are cli only.

> Also If you don't have no experience and something is broken, it more easier to disconnect the duplicate file then to try to fix the merge one.

This situation pretty similar to what we had before, and now I've learnt on my mistakes and will follow this piece of advice: https://twitter.com/awesomekling/status/1622189280306118656?s=20&t=n84KZqQihQAScbgZLWW5Og

**Comment by talregev** [comment]
> This situation pretty similar to what we had before, and now I've learnt on my mistakes and will follow this piece of advice: https://twitter.com/awesomekling/status/1622189280306118656?s=20&t=n84KZqQihQAScbgZLWW5Og

All I asking that you test the project. I didn't tell you to accept it. You can see for yourself how hard it add dependencies to osx. This will make the dev work easier. Also you have knowledge in vcpkg. 
As you tested together with @CharlieFenton the osx apps, you can have some effort to go to this direction, that you and all dev in boinc will benefit.  You already know all the positive things for vcpkg.

**Comment by talregev** [comment]
@AenBleidd 

Beside the duplicate project file, any other comments?

Boinc client runs on cli. Also there are some tools that also can run on the cli. Run only the version argument on boincmgr:
`boincmgr --version` Can also run on the cli. It checks that the libs are loading correctly. 
Can you run some basic tests on your mac cli machine to test it and share some screenshots?

**Comment by AenBleidd** [comment]
> @AenBleidd 
> 
> Beside the duplicate project file, any other comments?

I had no chance to review it.
From the first look - project file has either incorrect encoding vor incorrect line endings, because it looks unstructured on the web page (original project files look ok).

> Boinc client runs on cli. Also there are some tools that also can run on the cli. Run only the version argument on boincmgr:
> `boincmgr --version` Can also run on the cli. It checks that the libs are loading correctly. 
> Can you run some basic tests on your osx cli machine to test it and share some screenshots?


I'll try to find some time and make some tests. Not sure when.

**Comment by talregev** [comment]
> > @AenBleidd 
> > 
> > Beside the duplicate project file, any other comments?
> 
> I had no chance to review it.
> From the first look - project file has either incorrect encoding vor incorrect line endings, because it looks unstructured on the web page (original project files look ok).
> 
> > Boinc client runs on cli. Also there are some tools that also can run on the cli. Run only the version argument on boincmgr:
> > `boincmgr --version` Can also run on the cli. It checks that the libs are loading correctly. 
> > Can you run some basic tests on your osx cli machine to test it and share some screenshots?
> 
> 
> I'll try to find some time and make some tests. Not sure when.
> 

I run on it unix2dos with mac format before inserting it to skip on code check. I guess it changes it that way. I will revert it as the original.

Thanks, I will appreciate it.

**Comment by talregev** [comment]
> From the first look - project file has either incorrect encoding vor incorrect line endings, because it looks unstructured on the web page (original project files look ok).

I reverted back as it was before. Can you verify that you are now see it correctly? 
Note you can hide the side bar on the review, that the windows will grow, and allow lines to be more longer and to have some structured to the file.

**Comment by AenBleidd** [comment]
1. `MACOSX_DEPLOYMENT_TARGET` should be set to `10.13`
2. `DMAC_OS_X_VERSION_MAX_ALLOWED` should be set to `101300`
3. wxWidgets and other dependencies should be built exactly with the same dependencies as it done by `3rdParty\buildMacDependencies.sh`. If some of the options are not available in the vcpkg port - then vcpkg port should be modified to support building needed dependencies without unnecessary nested dependencies.

If you do that - there will be no need in duplicate project file at all.
Meanwhile you can test this on the original file by overriding list of linked libraries passing it to the `BuildMacBOINC.sh` script using `-setting` parameter.

**Comment by talregev** [comment]
> 1. `MACOSX_DEPLOYMENT_TARGET` should be set to `10.13`
> 2. `DMAC_OS_X_VERSION_MAX_ALLOWED` should be set to `101300`
> 3. wxWidgets and other dependencies should be built exactly with the same dependencies as it done by `3rdParty\buildMacDependencies.sh`. If some of the options are not available in the vcpkg port - then vcpkg port should be modified to support building needed dependencies without unnecessary nested dependencies.
> 
> If you do that - there will be no need in duplicate project file at all. Meanwhile you can test this on the original file by overriding list of linked libraries passing it to the `BuildMacBOINC.sh` script using `-setting` parameter.

vcpkg itself compile the libs in target 12.6. 
If I revert the project to be in target 10.13, the result will be a warning that new libs are compiled with old project. 
As you mention, it not meant to replace the original way.
There is no point for add vcpkg and be exact as the dependencies in the original script. (Like we do for all other os we support in boinc). This is meant for upgrade all the current dependencies and see if something is break, or understand what it mean to move forward in the original without break the original, and without touch or change the scripts that you are also don't want to break. 

Any reason why boinc osx target to 10.13?

**Comment by AenBleidd** [comment]
> vcpkg itself compile the libs in target 12.6. 

We should find a way to do that with the version we need

> There is no point for add vcpkg and be exact as the dependencies in the original script. (Like we do for all other os we support in boinc).

There is: less differences - easier to support and test.

> Any reason why boinc osx target to 10.13?

Because we want to support older OSX versions, not just the latest one.
So this is essential to us.

**Comment by AenBleidd** [comment]
@talregev, some hints to you:
- https://github.com/microsoft/vcpkg/issues/21445#issuecomment-971140497
- https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by talregev** [comment]
I compile vcpkg dependencies in target 10.13, also compile with it with the original project file.
I needed to change the original project file. setVersion project is the first project that compile.
I needed to add a ld libboinc flag to all projects inside. Now setVersion depend on libboinc and libboinc will compile first.

I also Modify BuildMacBOINC.sh. On the original osx manager compilation now create an empty flags because there isn't new setting flag for it. BuildMacBOINC.sh now accept empty string and ignore them, switch to the next parameter.

> Meanwhile you can test this on the original file by overriding list of linked libraries passing it to the `BuildMacBOINC.sh` script using `-setting` parameter.

Thank you, I use your suggestion.



> @talregev, some hints to you:
> 
> * [[aws-sdk-cpp] build failure on macOS when targeting macOS 10.9 microsoft/vcpkg#21445 (comment)](https://github.com/microsoft/vcpkg/issues/21445#issuecomment-971140497)
> * https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

Thank you for your suggestion, I did it in other way.

**Comment by AenBleidd** [comment]
> I needed to change the original project file. setVersion project is the first project that compile.
I needed to add a ld libboinc flag to all projects inside. Now setVersion depend on libboinc and libboinc will compile first.

Why this is needed? Not all projects depend on libboinc, so there is no need to add it to every target.

I strongly recommend to not touch neither XCode project nor BuildMacBOINC.sh. Simply because they are working correctly now.
If smth additional needed - it should be passed from the BuildMacBOINC-CI.sh.

**Comment by talregev** [comment]
> Why this is needed? Not every project depends on libboinc, so there is no need to add it to every target.

Set version is not dependent on any project, as you can see on my change how it was before.
As you insisted to compile both vcpkg and original, on the same project and as I told you before, changes is needed to made for XCode project.
As you also suggested to add the flags as settings, now it create empty string in original compilation, that needed to ignore.
This is because how the BuildMacBOINC.sh is written.

These is the minimal changes I can do for support both on the same XCode project.
Also when you add the osx mac you modify both BuildMacBOINC.sh and BuildMacBOINC-CI.sh.

**Comment by AenBleidd** [comment]
@talregev,

> I needed to add a ld libboinc flag to all projects inside. Now setVersion depend on libboinc and libboinc will compile first.

> Set version is not dependent on any project, as you can see on my change how it was before.

Don't you think these two phrases contradict each other?

> As you also suggested to add the flags as settings, now it create empty string in original compilation, that needed to ignore.

Yes, but just for testing purposes, that you could test during vcpkg without having separate XCode project.

Now the goal is to compile all dependencies with vcpkg exactly the same way as its done via existing script to have the same list of libraries to link for both vcpkg and non-vcpkg version.
Because there is a reason why these dependencies are build without some particular nested dependencies, and this should be preserved.

So, just to summarize: at the end you should be able to build vcpkg and not-vcpkg version of OSX BOINC without any change in XCode project and with exactly the same list of dependent libraries.

> Also when you add the osx mac apps you modify both BuildMacBOINC.sh and BuildMacBOINC-CI.sh.

This was needed to update these projects because they were outdated for a while. Also, they were simplified and aligned with the main XCode project.
And these changes were made and tested very carefully to avoid unexpected changes.

**Comment by talregev** [comment]
> Yes, but just for testing purposes, that you could test during vcpkg without having separate XCode project.

As you suggested and mention this for testing purposes. Please test it.
I am waiting for your testing results and screenshots.

**Comment by AenBleidd** [comment]
@talregev,
As you may probably know (if not - that means that before starting to work on any topic you should invest some time doing some research (or at least asking around) to understand how it works), OSX BOINC is very different from other OSs (to compare, it's like Windows BOINC and Android BOINC that have a lot of differences in the workflow).
At first, OSX BOINC built on ci is not ready from being just copied and used.
To build OSX BOINC package that could be usable to install and run you need to do some additional steps described here: https://github.com/BOINC/boinc/blob/master/mac_build/HowToBuildBOINC_XCode.pdf

That basically means that CI only shows you that all components are built with no issues, but it doesn't give you a usable binaries.

Taking this into account, in order to test this, user should build the whole project by themselves including additional steps described in a document I mentioned above.

Unfortunately, I have no long-living OSX machine with GUI accessible to build everything by myself, install and run it every time you ask for testing.

Also, as I already wrote above, it's a hard requirement to build OSX BOINC with exactly the same set of dependencies and nested dependencies. While this is not done from your side - I see no reason to invest so much time from my side to find a possible solution of testing this.

P.S. Learning new areas is always good, but working on a topic you have no idea about without proper investigation first and, what is more important. without any possibility to test what you did, is not good, because it's a waste of your time and the time of project maintainers.
You should value not only your time, but also the time of others, and you can't just simply delegate your unfinished work to others.
Asking for help is fine, but pushing others to follow your vision is not an example of good relationships, especially when project maintainers asking you to fix your solution but instead of listening to them you prefer to push your line.
Pay some respect to others, and then other will pay respect to you in return.

**Comment by talregev** [comment]
> > @AenBleidd
> > Beside the duplicate project file, any other comments?
> 
> I had no chance to review it. From the first look - project file has either incorrect encoding vor incorrect line endings, because it looks unstructured on the web page (original project files look ok).
> 
> > Boinc client runs on cli. Also there are some tools that also can run on the cli. Run only the version argument on boincmgr:
> > `boincmgr --version` Can also run on the cli. It checks that the libs are loading correctly.
> > Can you run some basic tests on your osx cli machine to test it and share some screenshots?
> 
> I'll try to find some time and make some tests. Not sure when.

In the past recent months, I ask for your help twice. 
On on the other PR, and on this PR for testing. If we will count the numbers of help, you asked me more help then I asked from you.
As I mention before, boinc client and other tools can run on the cli, and can test them there. You already agreed to test it.

**Comment by AenBleidd** [comment]
> You already agreed to test it.

Ok, then you have to wait for that.

But this doesn't mean that I'll accept this PR with the list of dependencies that differs from the original building method's list of dependencies.

**Comment by talregev** [comment]
> > You already agreed to test it.
> 
> Ok, then you have to wait for that.
> 
> But this doesn't mean that I'll accept this PR with the list of dependencies that differs from the original building method's list of dependencies.

As I mention before, I am waiting for your tests results. Thank you.

**Comment by AenBleidd** [comment]
After discussion with @CharlieFenton and careful consideration, we kindly ask you to stop working on this for the next reasons:
- you have no experience building OSX applications
- you have no environment to test what you build
- official OSX build will not use vcpkg, and will continue to rely on existing build scripts
- I have no resources (suitable test environment) to work on and support OSX vcpkg build
- neither me nor Charlie have desire and time to work on and support stuff that will not used

That is why I'm closing this PR without merge.
I kindly ask you for your understanding.

**Pull request closed without merging**
