### PR TITLE
client - Update ca-bundle.crt

### PR DESCRIPTION
**Pull request by TheAspens**
Update ca-bundle.crt to latest copy of certificates from
https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
using the curl provided script at
https://github.com/curl/curl/blob/master/lib/mk-ca-bundle.pl

I tested using the 7.9 client with this new version of the ca-bundle.crt file and connected to Seti@Home, Einstein@Home, CPDN and World Community Grid.

Updating this so that the list of trusted certificate providers is update to date.

### CODE REVIEW

**Comment by davidpanderson** [comment]
Thanks.  Not sure why CI build failed but this change is not the reason.

**Comment by CharlieFenton** [comment]
Interesting. Christian and I are working on a Travis CI build failure on my mac_fix_travis_script branch. Yet the CI build worked on my mac_update_dependencies branch, but failed on my mac_generalize_build_scripts branch.

The only other commits to master between the mac_update_dependencies branch and mac_generalize_build_scripts branch are these 2:

6af841c Merge pull request #2314 from progger/optimize_results_page
Optimized the counts of results by states and apps for results page

6f92305 Merge pull request #2312 from BOINC/dpa_amrpc
Add boinccmd commands to do acct mgr RPC, and to show acct mgr info

**Comment by ChristianBeer** [comment]
I deleted the `master` branch cache to test and troubleshoot #2323 which means the Mac travis build will fail until the build problems with FTGL are solved. Hopefully my last commit already did that. I'm going to restart the failed mac tests on the latest PRs once the mac cache is rebuilt.

**Comment by JuhaSointusalo** [comment]
@ Someone with write access to Windows dependency store.

Windows build script takes `ca-bundle.crt` from dependency store, not from the source tree. The following change fixes it.
```
diff --git a/win_build/dependspaths.cmd b/win_build/dependspaths.cmd
index b70c464..2ce20bc 100644
--- a/win_build/dependspaths.cmd
+++ b/win_build/dependspaths.cmd
@@ -29,7 +29,7 @@ IF /I "%BUILDPLATFORM%"=="x86" SET CPUARCH=x86

 SET INSTALLERREDIST=%BUILDROOT%\win_build\installerv2\redist\Windows\%VSPLATFORM%
 SET CURLREDIST=%BUILDTOOLSROOT%\curl\mswin\%VSPLATFORM%\%BUILDTYPE%\bin
-SET CURLSUPPORT=%BUILDTOOLSROOT%\curl\
+SET CURLSUPPORT=%BUILDROOT%\curl\
 SET OPENSSLREDIST=%BUILDTOOLSROOT%\openssl\mswin\%VSPLATFORM%\%BUILDTYPE%\bin
 SET ZLIBREDIST=%BUILDTOOLSROOT%\zlib\mswin\%VSPLATFORM%\%BUILDTYPE%\bin
 SET SQLITEREDIST=%BUILDTOOLSROOT%\sqlite3\mswin\%VSPLATFORM%\%BUILDTYPE%\bin
```

I would also remove `ca-bundle.crt` from the dependency store to avoid any potential future confusion about which file is used.

Please make the change to both VS2010 and VS2013 deps.

**Comment by RichardHaselgrove** [comment]
I concur with this suggestion - my private builds have been presenting an outdated ca-bundle in the build folder.

**Comment by TheAspens** [comment]
Please review this: https://github.com/BOINC/boinc/issues/2346

I don't know how to update the dependency stores and I think we should move them to make maintenance easier.

**Comment by RichardHaselgrove** [comment]
It might be worth asking @romw.

**Comment by JuhaSointusalo** [comment]
@davidpanderson has updated Alpha repo last November so he should be able to update build deps too.

**Comment by davidpanderson** [comment]
Thanks; I updated the dependencies repo.

**Comment by AenBleidd** [comment]
@davidpanderson, did you update dependencies repo for vs2013 too?

Best regards,
Vitalii Koshura

2018-02-14 7:08 GMT+02:00 David Anderson <notifications@github.com>:

**Comment by RichardHaselgrove** [comment]
The Index of /git/boinc_depends_win_vs2013.git/objects (http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git/objects/?C=M;O=D) is showing datestamps from 2016, matching Rom's f0cbfc3aaada30c80030006e356b21ed08475cd8 - that's still the last item in my git log following attempts to update this morning (which report that my old files are up-to-date).

**Comment by davidpanderson** [comment]
Oops!  I forgot to update 2013.  Done now.

On Wed, Feb 14, 2018 at 2:30 AM, RichardHaselgrove <notifications@github.com

**Comment by RichardHaselgrove** [comment]
Got my first connection failure apparently pointing to a certificate error - BOINC v7.8.3 at Einstein. Failure cleared after replacing certificate file with this one. Full Event Log at https://einsteinathome.org/content/reporting-error-file-not-found

**Comment by CharlieFenton** [comment]
I have added a tiny installer package to update the ca-bundle.crt file on very old Mac clients to the http://boinc.berkeley.edu/download_all.php web page. This is only for clients running on OS 10.3.9 through OS 10.5.8, which can't run the current BOINC builds; it should work for both PowerPC and Intel Macs. 

@davidpanderson please look over how I did this and make any changes you feel are appropriate.

Users running on OS 10.6 or later should install BOINC 7.10, which will include the new ca-bundle.crt file. (The installer package format required by OS 10.3.9 cannot be code signed, so Gatekeeper won't allow users with OS 10.8 or later to run it.)

My PR #2489 adds a script to the mac_installer directory in the GIT repository which builds this updater installer package.

**Comment by CharlieFenton** [comment]
The http://boinc.berkeley.edu/download_all.php web page currently shows both a _recommended version_ and one or more _older versions_ for each platform. As mentioned in my previous comment, I have added an updater for those older Mac builds which cannot run on newer Macs. This updater cannot be used on Macs with OS 10.8 or newer.

Since the _older versions_ for each platform have the old ca-bundle.crt, they should be removed unless an updater is provided to install the new ca-bundle.crt, once version 7.10 is released as the _recommended version_.

**Comment by CharlieFenton** [comment]
Thinking about this a bit more ...
Despite our best efforts, show-stopper bugs are sometimes not reported until after a public release. In those cases, it is important for users to be able to revert to a previous build.  

So perhaps when we promote the 7.10 build to _recommended version_, we should should **temporarily** leave the currently _recommended version_ up as the _older version_, removing it after we are fully confident in the latest build (assuming the old ca-bundle.crt certificate is still working.)

Do we have any idea when the old ca-bundle.crt certificate will stop working?

**Comment by JuhaSointusalo** [comment]
> Do we have any idea when the old ca-bundle.crt certificate will stop working?

If you referring to removal of trust to Symantec issued certificates and Einstein@home updating their certificate, the date was April 16th for Einstein@home update. [Certificate update - please update old BOINC clients](https://einsteinathome.org/content/certificate-update-please-update-old-boinc-clients)

I haven't seen anyone complain about BOINC client not able to contact servers so this looks like a no issue after all.

**Pull request merged**
