### PR TITLE
Set the corrrect permissions

### PR DESCRIPTION
**Pull request by lfield**
Sets the permissions to be -rwxrwx---

Fixes an issues found during testing of the server release 1.4

### CODE REVIEW

**Comment by davidpanderson** [comment]
what is the issue and how does this fix it?

**Comment by lfield** [comment]
Sorry, here is the bug report. #5008

**Comment by AenBleidd** [comment]
@davidpanderson, could you please take a look at this PR one more time?

**Comment by davidpanderson** [comment]
I don't understand what the problem was, or how this change fixes it.
The 2770 sets the "setgid" bit in the permissions, which is necessary.
This has been here forever and seems to work.

**Comment by lfield** [comment]
I am not sure this is needed.

**Pull request closed without merging**
