### PR TITLE
[Android] Fix localization issues.

### PR DESCRIPTION
**Pull request by AenBleidd**
This fixes: #4429, #4432

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Review by talregev — CHANGES_REQUESTED** [review]
Please add the iw string for Hebrew locale

**Comment by AenBleidd** [comment]
> Please add the iw string for Hebrew locale

This will be added in a separate PR

**Comment by AenBleidd** [comment]
@Ageless93, could you please briefly review that necessary strings are fixed (without new build, just code review)?

**Comment by talregev** [comment]
ok. let me check this PR is crunch, and we update iw string in other PR.

**Comment by Ageless93** [comment]
Looks okay to me.

**Review by talregev — APPROVED** [review]
I compile, run and crunch on Oneplus One (android 9). 
I approve.

**Pull request merged**
