### PR TITLE
[CI] Update actions to fix deprecations

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@CharlieFenton, looks like we have some issues on CI with OSX build:

```
Ld /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/ss_app.build/Objects-normal/x86_64/Binary/boincscr normal x86_64 (in target 'ss_app' from project 'boinc')
    cd /Users/runner/work/boinc/boinc/mac_build
    /Applications/Xcode_12.5.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-macos10.10 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -L/Users/runner/work/boinc/boinc/mac_build/build/Deployment -L/Users/runner/work/boinc/boinc/3rdParty/buildCache/mac/lib -L../lib -F/Users/runner/work/boinc/boinc/mac_build/build/Deployment -filelist /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/ss_app.build/Objects-normal/x86_64/boincscr.LinkFileList -dead_strip -Xlinker -object_path_lto -Xlinker /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/ss_app.build/Objects-normal/x86_64/boincscr_lto.o -stdlib\=libc++ -fobjc-link-runtime -lresolv -ljpeg -lfreetype -lftgl -lz -lbz2 -framework IOSurface -framework AppKit -framework GLUT -framework OpenGL -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/ss_app.build/Objects-normal/x86_64/boincscr_dependency_info.dat -o /Users/runner/work/boinc/boinc/mac_build/build/boinc.build/Deployment/ss_app.build/Objects-normal/x86_64/Binary/boincscr
Undefined symbols for architecture x86_64:
  "_hb_buffer_get_glyph_positions", referenced from:
      _af_shaper_get_elem in libfreetype.a(autofit.o)
  "_hb_ft_font_create", referenced from:
      _af_face_globals_new in libfreetype.a(autofit.o)
  "_hb_buffer_add_utf8", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
  "_hb_buffer_guess_segment_properties", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
  "_hb_shape", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
  "_hb_buffer_clear_contents", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
  "_hb_buffer_get_length", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
  "_hb_buffer_destroy", referenced from:
      _af_shaper_buf_destroy in libfreetype.a(autofit.o)
      _af_face_globals_free in libfreetype.a(autofit.o)
  "_hb_font_set_scale", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
  "_hb_buffer_create", referenced from:
      _af_shaper_buf_create in libfreetype.a(autofit.o)
      _af_face_globals_new in libfreetype.a(autofit.o)
  "_hb_font_get_face", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_ot_tags_from_script_and_language", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_set_is_empty", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_set_subtract", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_ot_layout_collect_lookups", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_ot_layout_lookup_would_substitute", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_ot_layout_lookup_collect_glyphs", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_set_destroy", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_set_next", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
  "_hb_font_destroy", referenced from:
      _af_face_globals_free in libfreetype.a(autofit.o)
  "_hb_buffer_get_glyph_infos", referenced from:
      _af_shaper_get_cluster in libfreetype.a(autofit.o)
      _af_shaper_get_elem in libfreetype.a(autofit.o)
  "_hb_set_create", referenced from:
      _af_shaper_get_coverage in libfreetype.a(autofit.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Do you have any idea what went wrong?

**Comment by CharlieFenton** [comment]
Apparently someone added a library package called [HarfBuzz](https://en.wikipedia.org/wiki/HarfBuzz) to the CI build system for Macintosh. I never heard of  HarfBuzz before and it is certainly not installed on my Mac. All these undefined symbols are in the HarfBuzz library.

Freetype configure tests for its presence and #defines `FT_CONFIG_OPTION_USE_HARFBUZZ` if the HarfBuzz library is found. Most of the file Freetype-2.11.0/afshaper.c is guarded by: `#ifdef FT_CONFIG_OPTION_USE_HARFBUZZ`. 

I suspect adding either `--with-harfbuzz=no` or `--without-harfbuzz` to both configure calls in _mac_build/buildfreetype.sh_ would fix this on the CI builds.

**Comment by AenBleidd** [comment]
Will try that. Thanks!

**Comment by CharlieFenton** [comment]
@AenBleidd It would be good to know who installed the HarfBuzz library into the CI build system for Macintosh. No one within the BOINC community should be installing library packages without announcing that they are doing so. But it may not be within our control.

Who maintains the GitHub CI build system? Might it be possible that the HarfBuzz developers installed it into the CI build system not realizing this could break other projects?

**Comment by AenBleidd** [comment]
@CharlieFenton,we're using images hosted on GitHub Actions and controlled by Microsoft: https://github.com/actions/runner-images
OSX 11 image (we're building on now): https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
OSX 12 image that will be the default soon: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

And this is completely out of our control.
If I find any breaking change, I can report this to them (I already did that once for Windows OS image).
Could do that for OSX if needed but in this particular case this should be fixed by us in config scripts that we can control.
We're currently not using OSX CI for release builds (I mean the one we release to public), so I see currently no urgency in this.

**Comment by CharlieFenton** [comment]
@AenBleidd Make sure that the freetype library has been rebuilt using the new configure option after you changed the build script.

**Comment by AenBleidd** [comment]
@CharlieFenton, FreeType was successfully rebuild without HarfBuzz and now our CI works correctly again.
Please review

**Review by CharlieFenton — APPROVED** [review]
I approve the changes to buildfreetype.sh. I do not have the expertise to comment on the changes to other files.

**Pull request merged**
