### PR TITLE
[Lib] Add remote_submit to lib for linux and android

### PR DESCRIPTION
**Pull request by talregev**
Add remote_submit to lib for linux and android and mingw.

### CODE REVIEW

**Comment by davidpanderson** [comment]
The functions in remote_submit.cpp don't belong in the client.

**Comment by talregev** [comment]
ok. I can rename `struct ERROR` -> `struct RS_ERROR` for compile condor example in mingw.   
This is acceptable?

**Comment by davidpanderson** [comment]
What error are you trying to fix?

**Comment by talregev** [comment]
Expected identifier before numeric constant.   
My guess that ERROR is some define in mingw. (maybe also in windows).

**Comment by talregev** [comment]
I am closing this PR. this PR is meant to insert inside the `remote_submit.cpp` inside lib, to give services to apps, that want to submit report. 
I will create another PR for compile more apps (examples) in mingw. 
If we want, we can create public discussion if `remote_submit.cpp` inside lib.

**Pull request closed without merging**
