### PR TITLE
client: fix bug in work fetch logic for case of zero resource share and zero work buf.

### LINKED ISSUE #4827: Pull #4800 into 7.20.1 to fix #4396 seems to have not covered GPU case
**Describe the bug**
Pull #4800 to fix #4396 seems to have possibly worked only on CPU tasks not getting pre-fetched to let PrimeGrid folk idle their resources in the quest of being the 1st to be the finder of a prime, by setting ResShare=0 & Buffer=0 (although I have seen CPU tasks in the waiting when I first started the client), however GPU tasks still seem to be pre-fetched at times.

**Steps To Reproduce**
The 3 posts by me starting with http://www.primegrid.com/forum_thread.php?id=9951&nowrap=true#156197 describe what I saw, and what I found out by turning work fetch logging on. Here is a screenshot of the relevant section:

image

**System Information**
 - OS: Windows 10
 - BOINC Version: 7.20.1

### PR DESCRIPTION
**Pull request by AenBleidd**
Fixes #4827

### CODE REVIEW

**Comment by AenBleidd** [comment]
@TunaErtemalp, could you please test this?

**Comment by AenBleidd** [comment]
Please download this archive: https://github.com/BOINC/boinc/suites/7252954243/artifacts/291457518
Unpack it somewhere.
Then stop current BOINC client (simply by closing BOINC Manager and checking the first checkbox). Go to C:\Program Files\BOINC and copy/save somewhere BOINC.exe.
Afterwards replace the existing BOINC.exe with the one from the archive. Then start BOINC manager again.
This should help you to test it.
If you have BOINC installed in a non-default location - please use the corresponding correct path.

**Comment by RichardHaselgrove** [comment]
You can get ready-to-run compiled versions from this GitHub page. You want the Windows client.

1) in the box about checks below, click 'show all checks' (top right)
2) scroll to bottom, and find 'Android / Windows Test Report' (three above the end of list) - click Details
3) in the next page, look below the highlighted 'Windows Test Reports' for 'Windows - on: pull request' - click it
4) in the next page, see a list of 'Artifacts'. Click to download the one that starts 'win_client_x64_...'

You'll need to go through two stages of archive decompression to reach a replacement 'boinc.exe'. Stop BOINC on your machine, replace the existing boinc.exe file with the one you've just downloaded, restart and test.

**Comment by TunaErtemalp** [comment]
> Please download this archive: https://github.com/BOINC/boinc/suites/7252954243/artifacts/291457518 Unpack it somewhere. Then stop current BOINC client (simply by closing BOINC Manager and checking the first checkbox). Go to C:\Program Files\BOINC and copy/save somewhere BOINC.exe. Afterwards replace the existing BOINC.exe with the one from the archive. Then start BOINC manager again. This should help you to test it. If you have BOINC installed in a non-default location - please use the corresponding correct path.

Running it as I type this... Will report back soon.

**Comment by RichardHaselgrove** [comment]
'Give a man a fish, and you feed him for a day. Teach a man to fish, and you feed him for life.'

:)

**Comment by TunaErtemalp** [comment]
@AenBleidd What a beautiful sight! :)

> 7/7/2022 9:50:04 AM |  | choose_project(): 1657212604.595810
> 7/7/2022 9:50:04 AM |  | [work_fetch] ------- start work fetch state -------
> 7/7/2022 9:50:04 AM |  | [work_fetch] target work buffer: 180.00 + 0.00 sec
> 7/7/2022 9:50:04 AM |  | [work_fetch] --- project states ---
> 7/7/2022 9:50:04 AM | PrimeGrid | [work_fetch] REC 5439450.590 prio -0.022 can request work
> 7/7/2022 9:50:04 AM |  | [work_fetch] --- state for CPU ---
> 7/7/2022 9:50:04 AM |  | [work_fetch] shortfall 2052.00 nidle 11.40 saturated 1678.33 busy 0.00
> **7/7/2022 9:50:04 AM | PrimeGrid | [work_fetch] share 0.000 zero resource share**
> 7/7/2022 9:50:04 AM |  | [work_fetch] --- state for NVIDIA GPU ---
> 7/7/2022 9:50:04 AM |  | [work_fetch] shortfall 0.00 nidle 0.00 saturated 189.05 busy 0.00
> **7/7/2022 9:50:04 AM | PrimeGrid | [work_fetch] share 0.000 zero resource share**
> 7/7/2022 9:50:04 AM |  | [work_fetch] ------- end work fetch state -------
> 7/7/2022 9:50:04 AM | PrimeGrid | choose_project: scanning
> **7/7/2022 9:50:04 AM | PrimeGrid | can't fetch CPU: zero resource share
> 7/7/2022 9:50:04 AM | PrimeGrid | can't fetch NVIDIA GPU: zero resource share**
> 7/7/2022 9:50:04 AM |  | [work_fetch] No project chosen for work fetch
> 

I only have tasks that are in progress, and only get a new one when one completed task is uploaded. Just what the Dr ordered...

Seems it could go into 7.20.2 to make it official... Please let me know when something installable is ready; I will post it on PrimeGrid message board.

Thanks for the prompt attention & resolution!

Tuna

**Pull request merged**
