### PR TITLE
client: disable GET feature of GUI RPC

### PR DESCRIPTION
**Pull request by davidpanderson**
This feature isn't being used and is a security risk.

### CODE REVIEW

**Comment by TheAspens** [comment]
This looks correct.   I will hold off merging this over the weekend in case anyone wants to comment.  Thanks for making the change.

**Comment by AenBleidd** [comment]
Personally I'd completely remove it from the code as well. In any case it will be saved in git history and could be reverted if necessary.

**Comment by Rytiss** [comment]
Why are there code changes dealing with path handling, and all of it later gets disabled? I agree with @AenBleidd about removing it completely.

**Comment by davidpanderson** [comment]
This feature may be used in the future.  It's easier to remove #if 0 than to scan git history.

**Pull request merged**
