### PR TITLE
Convert uses of concatenated string resources to string resources with placeholders.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Fixes #

**Description of the Change**
Convert string resources which are concatenated with other values to string resources with placeholders. This reduces the number of string resources needed in the Android app and allows it to be localized more easily.

**Release Notes**
N/A

### CODE REVIEW

**Comment by AenBleidd** [comment]
Please remove all values-*/strings.xml files from this commit because localization on this project is made by Transifex, so all changes in localized files will be overwritten.
And don't split commits to every file, they should be splitted logically, not by file.
Thanks in advance :)

**Comment by Isira-Seneviratne** [comment]
> 
> 
> Please remove all values-*/strings.xml files from this commit because localization on this project is made by Transifex, so all changes in localized files will be overwritten.
So I should just leave the code changes?
> And don't split commits to every file, they should be splitted logically, not by file.
I did it because you suggested making the commits atomic.
> Thanks in advance :)
No problem :)

**Comment by AenBleidd** [comment]
> So I should only alter values/strings.xml?

Yes.

> I did it because you suggested making the commits atomic.

Yes, but atomic means that they contain only minimal logically connected changes. E.g., it should be possible to make a cherry-pick of any commit to different branch and everything should work as expected and no unnecessary changes will be merged with main changes.
I hope you understand my point :)

**Comment by Isira-Seneviratne** [comment]
> 
> 
> > So I should only alter values/strings.xml?
> 
> Yes.
> 
> > I did it because you suggested making the commits atomic.
> 
> Yes, but atomic means that they contain only minimal logically connected changes. E.g., it should be possible to make a cherry-pick of any commit to different branch and everything should work as expected and no unnecessary changes will be merged with main changes.
> I hope you understand my point :)

Yeah, thanks!

**Comment by AenBleidd** [comment]
Could you please fix build errors? Just remove translated values that are not used anymore but do not add new values to the translation files. It could be done in one commit.
Sorry for misleading you before .
Thanks in advance

**Comment by Isira-Seneviratne** [comment]
Ah, it's no issue.

**Pull request merged**
