### PR TITLE
Update links in license files to point correct link to sources

### LINKED ISSUE #2357: Windows Installer License Agreement
In the blurb on the Windows Installer license agreement:

""This is free software. It is distributed under the terms of the GNU Lesser General Public License as published by the Free Software Foundation (http://www.fsf.org/). The source code may be obtained from the BOINC web site (http://boinc.berkeley.edu/)."
a) URLs should be HTTPS.
b) source code isn't available from the BOINC website, but from Github.

### PR DESCRIPTION
**Pull request by AenBleidd**
This fixes #2357 

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by Ageless93** [comment]
You're still pointing to http://www.fsf.org/ for the Free Software Foundation. The link may redirect to https://www.fsf.org/, but it's better to immediately point to that, instead of letting a redirect do it. 

I.e. 

> -\par This is free software. It is distributed under the terms of the GNU Lesser General Public Licenseas published by the Free Software Foundation (http://www.fsf.org/). The source code may be obtained from the BOINC web site (http://boinc.berkeley.edu).
> +\par This is free software. It is distributed under the terms of the GNU Lesser General Public Licenseas published by the Free Software Foundation (http://www.fsf.org/). The source code may be obtained from the BOINC official repository on GitHub (https://github.com/BOINC/boinc/).

**Comment by AenBleidd** [comment]
@Ageless93, sorry, missed this. Fixed. Thanks

**Comment by Ageless93** [comment]
Well, I missed the missing space. :)

**Comment by TheAspens** [comment]
Looks good - thanks for updating those.

**Pull request merged**
