### PR TITLE
[sched] add docker plan class spec

### PR DESCRIPTION
**Pull request by AenBleidd**

### CODE REVIEW

**Comment by AenBleidd** [comment]
Depends on #5757 that needs to be merged first.

**Comment by AenBleidd** [comment]
@davidpanderson, I have fixed conflicts in this PR.
Please review and test when ready.
Thank you in advance.

**Comment by AenBleidd** [comment]
@davidpanderson, I believe this is not relevant anymore. Should I just discard this PR or you still need it for some purposes?

**Comment by davidpanderson** [comment]
OK to discard.

**Pull request closed without merging**
