### PR TITLE
update french .mo file; update installshield files

### PR DESCRIPTION
**Pull request by davidpanderson**

### CODE REVIEW

**Comment by AenBleidd** [comment]
@davidpanderson do we really need all this changes made in 7.8.2 to be merged back to master?

**Comment by JuhaSointusalo** [comment]
As far as I can tell, the French .mo file was merged earlier and the InstallShield files were pushed to 7.8 directly without a pull request.

**Comment by JuhaSointusalo** [comment]
Actually, @AenBleidd had it right. The direction is from 7.8 to master. This needs to be closed without merging.

**Comment by davidpanderson** [comment]
Nope.  I made a mistake of some sort.

**Pull request closed without merging**
