### PR TITLE
Build: experimental Travis CI configuration for OSX

### PR DESCRIPTION
**Pull request by ChristianBeer**
DO NOT MERGE!

### CODE REVIEW

**Comment by AenBleidd** [comment]
@ChristianBeer Why it takes so much time for Travis CI to start OSX build after linux build? Waiting for free slot or something else? Thanks

**Comment by ChristianBeer** [comment]
Yes, there is usually a backlog for OSX builds. You can see actual numbers here: https://www.traviscistatus.com/

I'm therefore thinking to reduce the number of builds from three to one and just build all components (lib, client, manager) in one build.

**Comment by AenBleidd** [comment]
I think this is not neccessary: there is no such active development on BOINC to reduce the time of CI build. On the other hand separate build jobs could help to identify the root of the possible issue faster when you can see which component is failed during the build.

**Comment by ChristianBeer** [comment]
This is getting cumbersome to do remotely. I'm stopping now. Maybe I can get my hands on a Mac to figure out how to build the dependencies in a way that fits into the Travis cache.

**Comment by AenBleidd** [comment]
As I see last error was:

```
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/travis/build/BOINC/boinc/mac_build/build/Development -L/Users/travis/build/BOINC/boinc/mac_build/build/Development -F/Users/travis/build/BOINC/boinc/mac_build/build/Development -filelist /Users/travis/build/BOINC/boinc/mac_build/build/boinc.build/Development/ss_app.build/Objects-normal/i386/boincscr.LinkFileList -mmacosx-version-min=10.6 -Xlinker -no_deduplicate -lresolv -ljpeg ../build/mac/freetype-2.6.2/objs/.libs/libfreetype.a ../build/mac/ftgl-2.1.3~rc5/src/.libs/libftgl.a -lz -lbz2 -fobjc-link-runtime -framework AppKit -framework GLUT -framework OpenGL -Xlinker -dependency_info -Xlinker /Users/travis/build/BOINC/boinc/mac_build/build/boinc.build/Development/ss_app.build/Objects-normal/i386/boincscr_dependency_info.dat -o /Users/travis/build/BOINC/boinc/mac_build/build/Development/boincscr

Undefined symbols for architecture i386:

  "_png_create_info_struct", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_create_read_struct", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_destroy_read_struct", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_error", referenced from:

      _read_data_from_FT_Stream in libfreetype.a(sfnt.o)

  "_png_get_IHDR", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_get_error_ptr", referenced from:

      _error_callback in libfreetype.a(sfnt.o)

      _read_data_from_FT_Stream in libfreetype.a(sfnt.o)

  "_png_get_io_ptr", referenced from:

      _read_data_from_FT_Stream in libfreetype.a(sfnt.o)

  "_png_get_valid", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_read_end", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_read_image", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_read_info", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_read_update_info", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_expand_gray_1_2_4_to_8", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_filler", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_gray_to_rgb", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_interlace_handling", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_longjmp_fn", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

      _error_callback in libfreetype.a(sfnt.o)

  "_png_set_packing", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_palette_to_rgb", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_read_fn", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_read_user_transform_fn", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_strip_16", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

  "_png_set_tRNS_to_alpha", referenced from:

      _Load_SBit_Png in libfreetype.a(sfnt.o)

ld: symbol(s) not found for architecture i386

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Does this mean a problem with cache?

**Comment by ChristianBeer** [comment]
No, that seems to be a problem how libfreetype was built. But If I can't get the cache working I would download and build all dependencies with every try to fix this. Which is why I want to fix the cache problem first and then see what went wrong with libfreetype.

**Comment by AenBleidd** [comment]
Thank you for the explanation. Good luck!

**Comment by ChristianBeer** [comment]
I found a copynpaste bug in my last commit that didn't remove unneeded files. I'll give it one more try to see if at least the caching issue can be solved this way.

**Comment by ChristianBeer** [comment]
That worked but the cache is still large with ~800MB just for the Mac dependencies. Need to find a way to reduce this some more.

**Comment by ChristianBeer** [comment]
There is a successful build and I pushed a new branch that has a consolidated version of the working scripts. Thanks for watching.

**Comment by AenBleidd** [comment]
@ChristianBeer, I found this stale branch. Are you ok to delete it? Thanks

**Pull request closed without merging**
