### PR TITLE
changes for wcg branded mac client

### PR DESCRIPTION
**Pull request by seippel**
Fixes #

**Description of the Change**

**Alternate Designs**

**Release Notes**

### CODE REVIEW

**Comment by CharlieFenton** [comment]
[1] Your propose changes remove the deployment target 10.6 without replacing it. I strongly object to this for two reasons:
* the current BOINC GIT master has deployment target set to 10.7, not 10.6, except for the boinc_finisn_install target which chas deployment target 10.13 (ince it is only  used in OS 10;13 and later.)
* by totally removing this, you are probably eliminating backward compatibility with older systems back to 10.7 for no good reason. I have worked extremely hard over the years to maintain backward compatibility as far back as possible, since many people repurpose older Macs to run BOINC full time. The changes you are proposing affect all branded and unbranded builds of BOINC, not just WCG branded builds.

[2] Also, you are adding CLANG_CXX_LIBRARY = "libc++", but the the current BOINC GIT master already has C__ Standard Library set to this value.

[3]Please ensure that your branch is starting from the current BOINC GIT master.

**Comment by CharlieFenton** [comment]
It is important that all branded and unbranded builds of a particular version of BOINC be built from the same source repository. This means that changes need to eventually be merged into GIT Master. Please see my outline of the process below and read the links under _Development Processes_ [here](https://github.com/BOINC/boinc-policy) for more information.

Please note that you should not be modifying version.h; only the Release Manager should do that.

The usual process is:
* create a feature branch from GIT Master
* make your changes
* after review, a committer (one who is authorized to update GIT Master) merges your branch into GIT Master
* the Release Manager creates a release branch from GIT Master
* the Release Manager updates version.h in the release branch
* Both branded and unbranded builds of BOINC are built from the release branch

**Comment by CharlieFenton** [comment]
> Both branded and unbranded builds of BOINC are built from the release branch

For Macintosh, unbranded (generic) installers are created from the built binaries by running the `mac_installer/release_boinc.sh` script. Branded installers (such as World Community Grid) are created from the **same** built binaries by running the `mac_installer/release_brand.sh` script.

Instructions for running these scripts can be found  in the comments near the top of each script.

**Comment by CharlieFenton** [comment]
After studying this PR more I think I understand what you are trying to do: release an WCG branded BOINC 7.14 with a few needed fixes, independently of the general BOINC release process, rather than continuing to wait for the long overdue BOINC 7.16.4.

But you are trying to build the Mac release using a newer version of the Xcode development tools rather than Xcode 9.4.1 which I used to build the original 7.14.x releases. And you have found that requires changes to the Xcode project. 

I have already solved that problem. Rather than struggle with this, I suggest you cherry pick / merge the following commits from GIT master into your branch:

342be191f2 Mac allow building with xcode10 PR #2762

a178281d8d Mac fix build dependencies xcode10 PR #2981

Another issue you may not have considered is that the BOINC 7.14 code will not work properly on Macs running OS 10.15.x Catalina. I suggest you cherry pick / merge the following commits from GIT master into your branch:

7d99c87976  mac: Fixes for screensaver under OS 10.15 Catalina PR #3369

535cd94936  Fix Mac installer & uninstaller for branded BOINC screensavers on OS 10.15  PR #3395

Finally, I also suggest you cherry pick / merge the following commit (which is a one-line change) from GIT master into your branch:

48bfac3d5d  Mac: Fix computation of non_BOINC CPU usage PR #3368

I hope this helps.

**Comment by CharlieFenton** [comment]
One more reminder: 
Apple has introduced a new level of security which Apple calls _notarization_. OS 10.15 Catalina refuses to install Developer ID–signed software unless it has been _notarized_ by Apple (though expert users have a way to work around this restriction.) Be sure to _notarize_ the installer and uninstaller following the directions in the comments at the top of both the `mac_installer/release_brand.sh` and `mac_installer/release_boinc.sh` scripts.

**Comment by CharlieFenton** [comment]
> OS 10.15 Catalina refuses to install Developer ID–signed software unless it has been notarized by Apple

To clarify: that applies only to applications downloaded from the Internet. When I was building releases, I would email them to myself to ensure that OS X's Gatekeeper security would allow me to install them after downloading.

**Comment by seippel** [comment]
You're right - I am trying to release a WCG branded 7.14 client with additional fixes.  We don't have approvals for 7.16, so that's unfortunately not an option even when it's ready.  I also only have access to OS 10.15 which doesn't seem to work with Xcode 9.x.  

I'll revert my changes and try cherry picking the commits you listed and see where I end up.  Thank you for taking the time to look at this.

**Comment by CharlieFenton** [comment]
You should probably also apply the changes from my PR #3426 in my branch fix_mac_platform. I don't have a commit number for you because it has not yet been merged into master.

**Comment by CharlieFenton** [comment]
I recently ported my changes for compatibility with OS 10.15 to the BOINC version 7.14 code base. You may want to look at my PR #3485 and GIT branch mac_7_14_3.

**Comment by mcandre** [comment]
GitHub is showing no net changes for these commits.

**Comment by CharlieFenton** [comment]
> GitHub is showing no net changes for these commits.

I'm not sure what this means. In any case, this PR should be closed, as the necessary changes to accomplish the intent of this PR have already been merged in the _client_release/7/7.14_ branch by PR #3395 and #3485. You should be able to build a WCG branded BOINC for the Mac directly from the _client_release/7/7.14_ branch.

**Comment by CharlieFenton** [comment]
@seippel:  Please see my PR #3537. Once it is merged you should be able to build a branded client installer from the `client_release/7/7.14` branch.

**Comment by TheAspens** [comment]
@CharlieFenton thanks.  We should have closed this sooner.  Sorry for the confusion.  I will be working this later this afternoon.

**Pull request closed without merging**
