### PR TITLE
[Manager] Fix fields populating on 'Add Project' wizard on launch

### LINKED ISSUE #2444: [Client GUI] Add Project wizard doesn't populate all fields
This with v7.9.3 under Windows 7/64. When the 'Attach project' wizard is first opened, the fields for Research area, Organisation, and Web site are blank.

wizard initial load

After viewing other projects, or changing the category filter, the missing fields are fully populated.

wizard reselect

### PR DESCRIPTION
**Pull request by AenBleidd**
When opening 'Add Project' wizard it shows next fields empty:
Research area, Organisation, and Web site.
This happens because of EllipseStringIfNeeded() function that truncates the string to 0 symbols because the wizard window was not constructed yet and has undefined size.

This fixes #2444.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
Guys, could you please review this?

Personally I hate this fix because this is a dirty hack from my POV.
I found no other way to get the size of the window and make proper string truncation.

If you have another idea please feel free to close this and reimplement it in a better way.

**Comment by AenBleidd** [comment]
Reopened to rerun CI

**Comment by CharlieFenton** [comment]
The added space on line 564 of _clientgui/ProjectInfoPage.cpp_ appears to be wrong.
I do not know whether or not your changes to lines 123 and 139-140 in _clientgui/wizardex.cpp_ are correct.

Otherwise it looks good to me. I played with it a bit and did not find a better way to fix this. It is surprising that this has not been reported before, since it has been a bug for quite some time.

**Comment by AenBleidd** [comment]
@CharlieFenton, 

> The added space on line 564 of clientgui/ProjectInfoPage.cpp appears to be wrong.

I agree. I have settings in my diff viewer to skip line ending and space changes.
I'll fix this

**Comment by JuhaSointusalo** [comment]
`wxStaticText` has built-in support for ellipsizing text these days. No idea how well it works, just read it in the docs. `wxHyperlinkCtrl` of course doesn't. You could subclass `wxHyperlinkCtrl` and add ellipsizing. Maybe a lot of work.

wxWidgets' own wizard class has a page shown event. You could hook up to it and fix the labels then. Maybe a bit less of a hack but you'd need to either convert the code to use upstream wizard class or update our copy of it.

Or you could hook up to resize event of some suitable control and fix the labels then. This would add support for resizing the dialog. Not that it is resizeable but, you know, if it were.

Or you could stick to what you have done here.

Shrug.

**Comment by AenBleidd** [comment]
> wxWidgets' own wizard class has a page shown event. You could hook up to it and fix the labels then. Maybe a bit less of a hack but you'd need to either convert the code to use upstream wizard class or update our copy of it.

I tried to do this but with no success. As far as I remember page shown event happened before wizard window shown event and there are still no size of the page.

> Or you could hook up to resize event of some suitable control and fix the labels then. This would add support for resizing the dialog. Not that it is resizeable but, you know, if it were.

I don't want to bind to some another control and it actually will do the same as now.

> wxStaticText has built-in support for ellipsizing text these days. No idea how well it works, just read it in the docs. wxHyperlinkCtrl of course doesn't. You could subclass wxHyperlinkCtrl and add ellipsizing. Maybe a lot of work.

This looks like a very good idea. Will play with it

**Comment by JuhaSointusalo** [comment]
> I tried to do this but with no success. As far as I remember page shown event happened before wizard window shown event and there are still no size of the page.

Well bummer.

**Comment by TheAspens** [comment]
@JuhaSointusalo  or @CharlieFenton  - if you guys are both good with this change can one of you merge it?  @RichardHaselgrove was mentioning he would like to include it in the next client build  for 7.9/10 if possible

**Comment by AenBleidd** [comment]
@TheAspens, I think this can be merged. But in any case I want to play with the solutions suggested by @JuhaSointusalo.

**Pull request merged**
