### PR TITLE
Manager: 'Add Project Wizard': Change label from 'Forgot your passwor…

### LINKED ISSUE #1049: When adding a project, "Forgot your password?" link should say "Forgot your account info?"
**Reported by JacobKlein on 10 Mar 41246431 17:46 UTC**
Since the hyperlink takes you to a page called "Forgot your account info?", and the page can be used to determine more than just the password (i.e.: can determine email address)...

The link should say: "Forgot your account info?"

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1073

### PR DESCRIPTION
**Pull request by AenBleidd**
…d?' to 'Forgot your account info?'

This fixes #1049.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
This fixes #1049

**Comment by AenBleidd** [comment]
@Ageless93, @ChristianBeer, could you please review this? Thanks

**Comment by AenBleidd** [comment]
@CharlieFenton, could you please review this? Thanks

**Comment by davidpanderson** [comment]
The Manager and the web page should both say "Forgot your password?"

**Comment by CharlieFenton** [comment]
I believe this was an extension of PR #1049. Please see the comment I just added there. I'm not disputing either wording, just trying to provide context and explain the motivation for the change.

**Pull request merged**
