### PR TITLE
Revert commit that added GPL code

### PR DESCRIPTION
**Pull request by TheAspens**
This fixes issue #2304 

This reverts commit 73a95378f54964b118f84352c6cdd72b6915b124.

### CODE REVIEW

**Comment by TheAspens** [comment]
@CharlieFenton - can you review and compile on mac to confirm I didn't break anything?  After testing feel free to merge.  Thanks!

**Comment by TheAspens** [comment]
@davidpanderson - it would be good if you confirmed as well.

**Comment by davidpanderson** [comment]
Fine with me.  Builds on Win and Linux.

**Comment by CharlieFenton** [comment]
Builds fine on Mac. Merged and closed.

**Comment by CharlieFenton** [comment]
@TheAspens: Should I delete the `knr_revert_gpl` branch, or will you do it?

**Comment by TheAspens** [comment]
@CharlieFenton - I've deleted the branch.  Thanks for the reminder.

**Pull request merged**
