### PR TITLE
[WIP] Auto update certificate bundles

### LINKED ISSUE #4544: Temporary release problems following certificate expiry
I tried downloading and building under VS2019 for the first time today. The client built - with warnings, but it's currently running.

But the Manager failed to build. I can provide error messages tomorrow, but that's not important.

There's a suggestion that we could release a composite installer, with an updated client and ca-certificate bundle, but an older Manager. Could that keep the science on track, and buy time to sort out what's wrong with the Manager build?

### PR DESCRIPTION
**Pull request by CharlieFenton**
Fixes #4544

**Description of the Change**
Adds code to the BOINC client to automatically download a fresh _ca-bundle.crt_ file from the BOINC server every 2 weeks. It expects the file to be at
`https://boinc.berkeley.edu/ca-bundle.crt` which is a shortcut for the full URL: 
`https://boinc.berkeley.edu/dl/ca-bundle.crt`

**Note**: Currently, this code will not affect curl on MS Windows computers because as of PR #4545 curl uses _schannel_ instead of _openssl_ and so uses the Windows certificate store rather than _curl/ca-bundle.crt_. If it is desired to return to using _curl/ca-bundle.crt_, this automatic updating can be enabled for MS Windows by changing line 55 of _client/http_curl.cpp_ from 
`#define AUTO_UPDATE_MSW_CERTS 0`
 to 
`#define AUTO_UPDATE_MSW_CERTS 1`

**Alternate Designs**
PR #4545 partly solves this, but only for computers running currently supported versions of MS Windows. (Versions of MS Windows which are no longer supported by Microsoft do not get their certificate store updated automatically, though many can be updated manually by the user.)

Another approach would be to create mini-installers for each supported platform which update a new _ca-bundle.crt_ file from either BOINC, https://curl.se or Mozilla. But these require every BOINC user to be aware when a certificate is about to expire (or has expired) and to manually run the mini-installer.

**To Do:**
A chron job must be added to the BOINC server (currently on isaac) to periodically update the file 
`https://boinc.berkeley.edu/ca-bundle.crt` from either https://curl.se or Mozilla. I suggest doing this about every week or two, since https://curl.se updates it on their web site about every 6 weeks or so. This can be done with the following shell script:
`cd /home/boincadm/boinc-site/dl/`
`curl --remote-name --time-cond cacert.pem https://curl.se/ca/cacert.pem`
`if [  $? -ne 0 ]; then`
      `mv -f cacert.pem ca-bundle.crt`
`fi`

See https://curl.se/docs/caextract.html for more information.

### CODE REVIEW

**Comment by CharlieFenton** [comment]
The only reason this is marked [WIP] is that it is waiting on implementation of the chron job on the BOINC server as described above. @davidpanderson are you willing to do that? I can probably do it but would be more comfortable if you did.

**Comment by AenBleidd** [comment]
@CharlieFenton, I'd abandon this and instead create a code to update certificates in Windows certificate store (if needed). Since this is needed for Windows only, I'd not return to OpenSSL (or hybrid mode).
Speaking of task to automate update of ca-bundle.crt on git - sure, I'll do this.

**Comment by CharlieFenton** [comment]
>  I'd abandon this and instead create a code to update certificates in Windows certificate store (if needed). Since this is needed for Windows only, I'd not return to OpenSSL (or hybrid mode).

@AenBleidd Why is using _schannel_ and the Windows certificate store, which is only for Windows, preferable to using a common code base for all platforms (_OpenSSL_ and _ca-bundle.crt_)?

**Comment by RichardHaselgrove** [comment]
I think I can answer that one: because the MS Windows platform doesn't have any current access to an auto-updating process. That's because (as we established yesterday) it was designed before the introduction of an accessible Windows certificate store, with Windows Vista.

Windows could continue to use OpenSSL, but only if it was updated to at least a new version with LTS. The current v1.0 doesn't meet that criterion.

But, apart from a tip of the hat to the Open Source community, what benefit would a newer OpenSSL bring over schannel?

**Comment by CharlieFenton** [comment]
> If it is desired to return to using curl/ca-bundle.crt, this automatic updating can be enabled for MS Windows by changing line 55 of client/http_curl.cpp from
#define AUTO_UPDATE_MSW_CERTS 0
to
#define AUTO_UPDATE_MSW_CERTS 1

I have moved this to client/client_state.h line 65 so that it can be tested in `CLIENT_STATE::all_projects_list_check()` to avoid downloading ca-bundle.crt when that file is not used on MS Windows.

**Comment by CharlieFenton** [comment]
@RichardHaselgrove Of course I'm assuming that if we switched BOINC for MS Windows back to _OpenSSL_, it would use the latest version of _OpenSSL_. If we reverted the changes in PR #4545 and just updated the Windows build to use the current _OpenSSL_, my code will keep the certificate store up to date for all versions of Windows. All that is needed is to enable my code for Windows by changing 
_#define AUTO_UPDATE_MSW_CERTS 0_
to
`#define AUTO_UPDATE_MSW_CERTS 1`

With schannel, there needs to be separate code to update the Windows certificate store. The advantage is simpler BOINC using a common code base for all platforms.

**Comment by RichardHaselgrove** [comment]
> CLIENT_STATE::all_projects_list_check()

I have an instant gut worry over that. I run my machines with `<dont_contact_ref_site> 1`, because I have a reliable fibre broadband connection, and pinging Google doesn't give me any additional connection failure diagnostics.

But I've been told - #2352 - that setting that flag also deliberately blocks the auto download of all_projects_list - for the benefit of security-minded administrators who do not want their employees to have open access to the full internet.

By that rule, dont_contact_ref_site should also inhibit auto-download of a public ca-bundle.crt. The corporate system admins of such a site will presumably only permit BOINC use on quasi internal projects like WCG. and will have their own ways of achieving that.

**Comment by RichardHaselgrove** [comment]
> we can't update any file in installation directory because of lack of permissions

**False**. An installer could give itself permission. Take a look at [Lunatics Installer v0.46 released for 64-bit Windows](https://setiathome.berkeley.edu/forum_thread.php?id=85144&postid=2030148#2030148). The download link is to my Google Drive, because I prepared and distributed it.

**Comment by AenBleidd** [comment]
> An installer could give itself permission. 
Installer - yes. BOINC client - no. BOINC client might even run as a service with much less permissions as a regular user.
I mean, auto-update by client might be possible if we put this file to BOINC data directory only. But this could lead to another consequences I already wrote in my previous message.

**Comment by AenBleidd** [comment]
@CharlieFenton,

> But isn't the Windows certificate store in a place where BOINC can't update it? This would mean that on unsupported systems such as Windows 7 the user would need to know to run a special updater installer? 

True. But this might be necessary maybe once in next decade or even rarer.

> It seems better to let BOINC do this automatically.

Again, it's too risky for me. If this file is deleted, corrupted, or anything else, BOINC has no way to recover.
And it would be harder to explain people how to recover their BOINC Data directory (and not just run the installer that will do everything for them).

> We could make the rpc that downloads ca-bundle.crt use http:// instead of https://.

And this is a security hole

**Comment by AenBleidd** [comment]
@CharlieFenton, If http connection is intercepted in any way - you can't verify anything, and at least for two weeks you'll have compromised certificates. And this is too much time.
The real question is next: does this really worth to implement this now?
For me it looks like a waste of time, because if this work on the OS that was not updated last 5 years (and I doubt it's used for BOINC at all) - then we're quite safe with Windows 7/8/8.1/10/11.
Reference: https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide

**Comment by RichardHaselgrove** [comment]
And in the context we're considering it:

> This site can’t provide a secure connection
> asher.tools sent an invalid response.
> ERR_SSL_PROTOCOL_ERROR

**Comment by CharlieFenton** [comment]
> By that rule, dont_contact_ref_site should also inhibit auto-download of a public ca-bundle.crt. The corporate system admins of such a site will presumably only permit BOINC use on quasi internal projects like WCG. and will have their own ways of achieving that.

@RichardHaselgrove Yes, that is how I programmed it.

**Comment by CharlieFenton** [comment]
I may have a solution to the concerns expressed by @AenBleidd. [This article](https://stackoverflow.com/questions/16291809/programmatically-verify-certificate-chain-using-openssl-api) shows that we can use OpenSSL to verify the certificate bundle. If the verification fails, my code can leave the old certificate in place and (as it already does for other errors) set things up to try again one day later.

**Pull request closed without merging**
