### PR TITLE
Add CTRL+A shortcut

### LINKED ISSUE #2155: CTRL+A shortcut doesn't work
The CTRL+A shortcut doesn't work on the Projects and Tasks tab. Assuming also this is the case on the Transfers tab.
The CTRL+Left Click and the SHIFT+UP/DOWN/HOME/END shortcuts are working.

### PR DESCRIPTION
**Pull request by winkies**
Fixes #2155

**Description of the Change**
Define shortcut on accelerator table and bind it with event table. 

**Alternate Designs**
Tested only on Linux environment. It should work as well on Windows but **it should be tested on MacOS X**.

**Release Notes**
Add CTRL+A shortcut for advance view of boinc manager.

### CODE REVIEW

**Comment by RichardHaselgrove** [comment]
Tested on Windows: it does work on the Tasks tab, which is where it will be most useful for me (see #3778).

I rarely need to operate on all tasks across all projects, but I might need to operate on all tasks from a single project. It would be helpful to have a command button "Show [tasks from] only this project", analogous to the button at the foot of the Event Log window - the two controls would work well together.

**Comment by AenBleidd** [comment]
@RichardHaselgrove, sound like a new feature request ;)

**Comment by winkies** [comment]
@RichardHaselgrove Glad it's useful :)

I see what you need : it doesn't seem to be too much difficult. 
If maintainer (@AenBleidd ) approve your feature request, I could implement it in another one pull request ;)

**Comment by RichardHaselgrove** [comment]
The test for me of how useful a feature is: how many machines do I install in on, on the first day of testing.

Three hosts so far, monitoring eight clients between them!

So, yes, I propose "Show [tasks from] only this project" as a feature request, and I look forward to testing the resulting PR!

**Comment by RichardHaselgrove** [comment]
@winkies: not wanting to overwhelm you, but if you're comfortable working with the keyboard handler in wxWidgets, may I draw your attention to my #3359 - that one might be up your street too.

**Review by AenBleidd — APPROVED** [review]

**Pull request merged**
