### PR TITLE
Seippel wcg win client

### PR DESCRIPTION
**Pull request by seippel**

### CODE REVIEW

**Comment by davidpanderson** [comment]
Do WCG-specific files belong here?

**Comment by AenBleidd** [comment]
@seippel, could you please squash all your commits into one? Thanks

**Comment by TheAspens** [comment]
> Do WCG-specific files belong here?

This is how the branded installers have always been built and maintained.  Note that other branded installers assets:
https://github.com/BOINC/boinc/tree/master/clientgui/skins
https://github.com/BOINC/boinc/tree/master/win_build/installerv2

@romw established this way of doing things.  It also helps the branded installers comply with the LGPL requirement of providing a complete copy of what they distribute.

**Comment by seippel** [comment]
>  could you please squash all your commits into one? Thanks

@AenBleidd Sure - I've squashed them all into one commit now

**Comment by CharlieFenton** [comment]
Regarding your changes to _client_state.cpp_ and _cs_prefs.cpp_: In the past, we have never put any brand-specific code in the client, changed the output of the event log for branding or branded the client in any way. All brand-specific code has been limited to the BOINC Manager, screensaver and installer. I don't know if this is a formal policy; perhaps @davidpanderson pr @romw could comment.

**Comment by davidpanderson** [comment]
I think the message log should identify the program correctly (as BOINC, not WCG)

**Comment by RichardHaselgrove** [comment]
@davidpanderson I agree.

Maybe the way to handle this would be to keep the original message log entry

`NULL, MSG_INFO, "Starting BOINC client version %d.%d.%d for %s%s",`

and immediately follow it with a second line

"Using customizations from World Community Grid"

(or whichever distribution channel is providing the skins/branding - it should be general to allow other distributions to operate the same way)

**Comment by seippel** [comment]
I've removed the changes from _client_state.cpp_ and _cs_prefs.cpp_

**Comment by TheAspens** [comment]
@davidpanderson @CharlieFenton.  Since @seippel removed the disputed changes, are there any other concerns blocking the merge of this pull request?

**Comment by CharlieFenton** [comment]
I have no issues with it.

**Comment by davidpanderson** [comment]
fine w/ me

**Comment by TheAspens** [comment]
@CharlieFenton  and @davidpanderson - thanks!

The remaining changes are very specific to the WCG branded windows installer.  Normally, we discourage having someone from the same organization merge code contributed by someone in that same organization.  However, in this case the remaining changes in this pull request are specific to WCG and don't touch code elsewhere so I will proceed with merging this change.  If someone objects, please feel free to revert the merge and we can discuss on the contributor call or via a new pull request.  Thanks!

**Comment by TheAspens** [comment]
@seippel - what changes necessitated a rebuild of win_build/installerv2/redist/Windows/Win32/boinccas.dll?

**Comment by seippel** [comment]
I've removed the rebuild of Win32/boinccas.dll.  clientsetup/win/* was updated two months ago and boinccas.dll was last rebuilt 10 months ago.  I think boinccas.dll should be rebuilt, but that's unrelated to this pull request.

**Comment by TheAspens** [comment]
Ok - thanks.  Looks good and I'll merge.

**Pull request merged**
