### PR TITLE
[Improvement]: add overide keyword on abstract method

### LINKED ISSUE #3513: Code improvements results from Cppcheck
I ran [cppcheck](https://github.com/danmar/cppcheck) on the Boinc codebase which resulted in the some code improvements. 

Download the results here: [boinc_cppcheck.zip](https://github.com/BOINC/boinc/files/4365631/boinc_cppcheck.zip)

### PR DESCRIPTION
**Pull request by winkies**
Partially fixes #3513 

**Description of the Change**
Add `override` keyword on abstract method.

**Alternate Designs**
Use another analysis tool.

**Release Notes**
Apply changes according performance, portability and style warnings through cppcheck.

**Other related PR**
constness: #4295 
override keyword: #4296 (this PR)
printf format: #4297
explicit keywork: #4302
static cast: #4305

### CODE REVIEW

**Comment by talregev** [comment]
Don't warry about android fail.  I already fix it. When my fix will be merge you can rebase to the master and check again.

**Comment by talregev** [comment]
My fix was merge and working on the master.

**Comment by winkies** [comment]
Seems good - Thanks @talregev

**Comment by talregev** [comment]
@winkies You are welcome :)

**Comment by winkies** [comment]
Closing due to inactivity!

**Pull request closed without merging**
