### PR TITLE
manager fixes

### PR DESCRIPTION
**Pull request by JuhaSointusalo**
- fixes aborting and suspending tasks running on older clients 
- restores "run daemon" check

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Hi @JuhaSointusalo seems that you have to rebase your commits and fix the conflicts...

**Comment by JuhaSointusalo** [comment]
@LocutusOfBorg Thanks, I hadn't noticed.

**Comment by AenBleidd** [comment]
@JuhaSointusalo Could you please fix this pull request? Thanks

**Comment by JuhaSointusalo** [comment]
@AenBleidd Thanks for reminding me. Should be fixed and ready to merge now.

**Comment by AenBleidd** [comment]
@JuhaSointusalo Thank you!
@davidpanderson Could you please review this and merge? Thanks

**Comment by davidpanderson** [comment]
I don't understand what this commit is trying to fix, or how; please explain.

Not sure why there's a new lookup_app_version() that doesn't take a platform arg.
A host could have 2 different app versions that have the same version, plan class etc.
but that differ in platform (e.g. Win x86 and Win x64)

**Comment by JuhaSointusalo** [comment]
A new manager can't suspend, resume or abort tasks running on old client. The application column is also blank. I don't remember any more when the backward compatibility was broken, 7.6.20 something maybe. I just tested and the breakage is at least between 7.6.33 and 7.0.27.

Old clients don't include platform in \<result\>s and really old clients don't include plan_class in \<result\>s. The clients however do include everything in \<app_version\>s. That's why there needs to be different functions that look up the app_version with the information the client provided.

If there are multiple app_versions that differ only in platform the manager may indeed select wrong app_version. This is unavoidable because the client is not sending enough information and in any case it's not worse than what old client and old manager did together.

When the first manager that wasn't entirely backward compatible was released there was a few questions about it in forums but since then nothing. So I'm not sure how much backward compatibility between client and manager really matters to anyone.

**Comment by AenBleidd** [comment]
@JuhaSointusalo Could you please remove indent changes from this PR and make it mergeable again? Thanks

**Comment by JuhaSointusalo** [comment]
I'll sort it out once Charlie is done with the OSX changes.

**Comment by AenBleidd** [comment]
@JuhaSointusalo Thank you

**Comment by CharlieFenton** [comment]
On Mar 1, 2017, at 12:29 PM, Juha Sointusalo <notifications@github.com> wrote:
> I'll sort it out once Charlie is done with the OSX changes.


Thanks for waiting, Juha. I am done replacing deprecated APIs for OSX.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, could you please update this pull request? Thanks

**Pull request merged**
