### PR TITLE
[CI] replace Travis and AppVeyor with Github Actions

### LINKED ISSUE #4123: Travis CI is no longer free
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

travis-ci.org will be shutdown by 2020-12-31
free plan will become free trial
building for macOS requires credits

Other alternatives: https://ropensci.org/technotes/2020/11/19/moving-away-travis/

I am not sure whether BOINC is affected or not, so I created this issue for a discussion

### PR DESCRIPTION
**Pull request by ChristianBeer**
**Description of the Change**
This consolidates the different CI builds on one platform that provides support for the major three operating systems we build on (Linux, Windows, MacOS). The nomenclature and syntax is a bit different but it has the same functionality.
This commit introduces the Linux and Windows based workflows. All the build artifacts can now be downloaded from [bintray](https://bintray.com/beta/#/boinc/boinc-ci?tab=files). The CI workflows run for every pull request, every merge into the master branch and every Sunday around 12:00 (GMT).
Every first Sunday in a month a cleanup Script is run to delete old artifacts from Bintray. Artifacts from closed/merged pull requests get deleted then. Artifacts from weekly builds and merges into the master branch older than 6 months get deleted too.

Fixes #4123

Co-authored-by: @AenBleidd

**Alternate Designs**
An alternative would have been to apply for a limited amount of credits every month to run Travis-CI. 

**Release Notes**
N/A

### CODE REVIEW

**Comment by ChristianBeer** [comment]
Codecov seems to act strange. The comment says coverage has decreased but the website says it is the same as before.

**Comment by AenBleidd** [comment]
@ChristianBeer, Codecov behaves strange for a while, it's a normal behavior of it. Once I want to investigate it and create a ticker fr Codecov team to fix.

**Review by AenBleidd — APPROVED** [review]

**Comment by ChristianBeer** [comment]
There was one problem with the Windows deployment. It was done to the "custom" package not the "pull_requests" package. My commit should have fixed it.

**Comment by ChristianBeer** [comment]
@AenBleidd The Android workflow does not seem to cache the dependencies. This needs to be investigated and fixed after this is merged. I propose to update my personal fork with master from here in January and do some tests in the fork. Right now it works but takes a long time.

**Comment by AenBleidd** [comment]
@ChristianBeer, from what I saw in the logs while working in this, cache is working fine, we do not rebuild curl and openssl, but it still takes a lot of time to rebuild BOINC client 4 time (and this step takes ~90% of build time). But in my case I'll take a look at it later

**Comment by AenBleidd** [comment]
@ChristianBeer, yep according to this log ( https://github.com/BOINC/boinc/runs/1606333835 ) curl and openssl were taken from cache and were not rebuilt. So everything looks fine

**Pull request merged**
