### PR TITLE
[WIP] Assorted fixes

### PR DESCRIPTION
**Pull request by JamesMolson**
Do not merge yet, still in progress.

This contains fixes for FreeBSD, NetBSD, MacOS, SunOS, and probably more.

### CODE REVIEW

**Comment by AenBleidd** [comment]
@JamesMolson, please use [this](https://github.blog/2019-02-14-introducing-draft-pull-requests/) article to create draft pull requests or at least add [WIP] marker to the title of your pull request. Thank you

**Comment by lfield** [comment]
@JamesMolson, Also please try to do atomic commits rather than rolling up many changes into one PR. The title should so be updated to so that it is more specific to the change that is being made. 
e.g _Fixes to build on FreeBSD_.

**Comment by JamesMolson** [comment]
@AenBleidd hmm that is a new feature.

Anyway, things are working a little better now in terms of building, feel, free to merge.

**Comment by AenBleidd** [comment]
Please create a separate pull request for every feature/bugfix commit. I can't approve such pull request with   commits that are about different features and issues.
E.g. f1cd1867f8b6f727feea0c2318ad041295a37531 is definitely should be in a separate pull request.
Also separate FreeBSD fixes from Mac fixes.
BTW, regarding AVX, could you please add AVX2 (as it done in Windows code) and AVX512 support (if you add last one to Windows code too would be really great)

**Comment by lfield** [comment]
I have spoken to James and will covert these commits into individual PRs. Will once they have been created this PR can be closed.

**Comment by lfield** [comment]
Closing in favour of PRs:
- #3215 
- #3217 
- #3218 
- #3219 
- #3220 
- #3221 
- #3222

**Pull request closed without merging**
