### PR TITLE
[osx][cmake] Add osx libs cmake

### PR DESCRIPTION
**Pull request by talregev**
Add osx libs cmake.

### CODE REVIEW

**Comment by AenBleidd** [comment]
Please make it 'Ready for review' when it's actually ready. Thanks in advance.

**Comment by talregev** [comment]
It ready.

**Comment by AenBleidd** [comment]
I see two added triplets, x64 and ARM64 but on ci I see only one flow: x64.
Are you sure it's ready?

**Comment by talregev** [comment]
> I see two added triplets, x64 and ARM64 but on ci I see only one flow: x64.
> Are you sure it's ready?

The ci compile 2 triplets.

**Comment by talregev** [comment]
Please run Linux ci again.

**Comment by AenBleidd** [comment]
Why do you build two archs within the same flow?

**Comment by talregev** [comment]
> Why do you build two archs within the same flow?

Please review closely and you will find it out.

**Comment by talregev** [comment]
> Why do you build two archs within the same flow?

This is a complete build. not separate it by configure and make. 
Also there isn't separate in mac for x64 and arm64 like windows does in the regular compile. 
Also we already done it on android. When we do a full build, we do all the arch together.

**Comment by AenBleidd** [comment]
> Also we already done it on android. When we do a full build, we do all the arch together.

We did it for Android for different reasons.

> Also the regular mac compile both x64 and arm64 in the same flow, and unify them to 'universal mode'

I see unification to universal binaries in your scripts. Is it smth you plan to add later?

**Comment by talregev** [comment]
> > Also we already done it on android. When we do a full build, we do all the arch together.
> 
> We did it for Android for different reasons.
> 
> > Also the regular mac compile both x64 and arm64 in the same flow, and unify them to 'universal mode'
> 
> I see unification to universal binaries in your scripts. Is it smth you plan to add later?

I didn't did universal binaries. I am not planning to do it later.

**Review by AenBleidd — APPROVED** [review]

**Comment by AenBleidd** [comment]
Ok, since this is just an experimental build and not is going to be used anywhere - I approve it

**Comment by talregev** [comment]
> Ok, since this is just an experimental build and not is going to be used anywhere - I approve it

My thoughts exactly. Also later we advanced in the experimental build, there maybe a point we will separate the build. 
Thank you for your approval.

**Pull request merged**
