### PR TITLE
Mac: Consolidate branding strings

### PR DESCRIPTION
**Pull request by CharlieFenton**
Mac: Consolidate branding strings in one source file and one header file shared among all files which use them; add checks for missing branding strings.

### CODE REVIEW

**Comment by CharlieFenton** [comment]
@armstrdj: I have tested this and found no problems, but please also test it yourself.

**Comment by armstrdj** [comment]
@CharlieFenton Did you add the new header file to the commit?

**Comment by CharlieFenton** [comment]
@armstrdj:Oops! Fixed. Thank you for bringing this to my attention.

**Comment by armstrdj** [comment]
@CharlieFenton I have tested this and found no issues.

**Comment by TheAspens** [comment]
@armstrdj and @CharlieFenton - are you both satisfied with this pull request?  If so I will merge it.

**Comment by CharlieFenton** [comment]
TheAspens Yes, please merge. Thank you.

**Comment by armstrdj** [comment]
@TheAspens yes I have tested and found no issues.

**Pull request merged**
