### PR TITLE
client: fix possible overflow in peak FLOPS calculation for OpenCL GPUs

### PR DESCRIPTION
**Pull request by davidpanderson**
... and generate a warning message if impossible values
Attempt to fix issue #2988

### CODE REVIEW

**Comment by RichardHaselgrove** [comment]
This problem has been traced to a bad value returned by the AMD OpenCL driver stack (confirmed by clinfo), and is thus outside our immediate control at source.

This patch attempts to catch insane values and replace them with failsafe values. Unfortunately, the artifact from e77a6c3b6cb8e127c984d6a59449b20a4bb8f18b has been tested by the reporting user, and didn't meet this objective.

My reading of the logic flow in the patched file is

```
435 if (is_NVIDIA(prop.vendor)) {
509 else if (is_AMD(prop.vendor)) {
567 else if (is_intel(prop.vendor)) {
590 else { //other vendor
616 David's patch
627 } endif
```
So far, I have only seen reports of the problem affecting AMD devices: the safety net could be applied in the line 509 code block, or could be applied globally outside this structure.

The effect on end users is that tasks are reported to have zero estimated runtime, and fail with error 197 EXIT_TIME_LIMIT_EXCEEDED. It only affects the minority of users who are running their devices at non-default clocks, but for that minority, it's critical.

**Comment by Uplinger** [comment]
Closing and reopening to trigger travis-ci

**Comment by RichardHaselgrove** [comment]
At last, I've got a report back from one of the affected users:

```
2/11/2019 4:54:29 PM |  | OpenCL: AMD/ATI GPU 0: AMD Radeon(TM) Vega 8 Graphics (driver version 2766.5 (PAL,HSAIL), device version OpenCL 2.0 AMD-APP (2766.5), 7206MB, 7206MB available, 100 GFLOPS peak)
2/11/2019 4:54:29 PM |  | [coproc] AMD OpenCL reported bad GPU peak FLOPS 43980464128000000.000000; using 100000000000.000000
2/11/2019 4:55:42 PM | Milkyway@Home | Aborting task de_modfit_84_bundle5_3s_NoContraintsWithDisk200_1_1548330302_5851041_0: exceeded elapsed time limit 19.99 (45115500.00G/2323910.58G)
2/11/2019 4:56:03 PM | Milkyway@Home | Aborting task de_modfit_80_bundle5_3s_NoContraintsWithDisk200_1_1548330302_5850766_0: exceeded elapsed time limit 18.10 (42060400.00G/2323910.58G)
```
Given the log times, I assume that the two MilkyWay tasks were allocated and downloaded when the old, faulty, client was in operation. He's probably down to a low daily quota, but I'll watch for the next round of tasks.

The format of the 'bad flops' message is clunky - I never know what we really do with a micro-flop - but it's a debug message, and we can live with it. Not a blocker.

**Comment by JuhaSointusalo** [comment]
I had tested Nvidia and Intel code earlier with debugger (couldn't figure out a better way). Good to have a real test report.

For the server side, there is also the C++ version of plan classes. But that has a "todo: get rid of this" comment and it's not on par with the XML version feature-wise anyway. So I guess updating the XML version is enough. I'm not sure if plan class code is the right place for the sanity check. Maybe after parsing scheduler request would have been better. But the location of the sanity check is not a huge issue so I'll merge this.

**Comment by JuhaSointusalo** [comment]
@davidpanderson

I was looking at the tasks from one of the affected users and noticed that he is still getting too low runtime estimates for Milkyway tasks even after he changed the client to the one from this PR. And then the importance of the server changes in this PR dawned on me. Without patching server it will recompute the peak flops using the bad input values from the client and ends up with bad peak flops and bad runtime estimates. So the server must be patched as well. Correct?

If that is correct then I guess @lfield has to do a server hotfix release.

**Comment by RichardHaselgrove** [comment]
The server patch component of this PR has now been deployed and tested on the SETI@Home Beta server: the test was successful. Tasks run on https://setiweb.ssl.berkeley.edu/beta/show_host_detail.php?hostid=87175 show evidence of the faulty driver, but have been allowed to run to completion.

**Pull request merged**
