### PR TITLE
[Android] Fix issue when 'Add Project' list shows projects that have …

### LINKED ISSUE #1581: Android - 'Add Project' list shows many projects that are not supported on Android
Updated my Android devices to V 7.4.53
The 'Add Project' list now shows 34 projects.

http://boinc.berkeley.edu/projects.php   shows only 13 projects supporting Android, namely

Asteroids@home
Citizen Science Grid
Collatz Conjecture
Einstein@home
Enigma@Home
GPUGrid.net
Moo! Wrapper
Rosetta@home
SETI@home
theSkyNet POGS
Universe@Home
World Community Grid
Yoyo@home

Could the Android client list be pruned to only show projects supporting Android ?

### PR DESCRIPTION
**Pull request by AenBleidd**
…no Android support

In f6d550484a0aef9ae80f8ff1c55823de5c3ec006 was added getBoincAltPlatform() that provides the corresponding 32-bit architecture string for 64-bit devics but produces empty string for 32-bit devices.
Added verification for empty string in getAttachableProjects() method to filter projects that have no Android support.

Fixes #1581

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
I'm not sure I have the same coding style but ok, I'll try it.
BTW, what exactly is wrong with these two lines?

**Comment by adamradocz** [comment]
The project has its own coding style. The issue is the spacing - currently, there's no space after the `if `and `for`.

**Comment by AenBleidd** [comment]
Command you mentioned doesn't work for me. Styling is fixed

**Comment by adamradocz** [comment]
BTW I think the `getBoincAltPlatform` function is wrong and your patch is unnecessary. 
I'll make a PR, so you can check it.

**Comment by TheAspens** [comment]
Closed and reopened to retrigger Travis CI

**Comment by AenBleidd** [comment]
> But I don't get what's the purpose of `getBoincAltPlatform` function. The 32bit platforms for 64bit CPUs should be handled by the `getBoincPlatform` too?

Sorry, looks like I missed your question.
The purpose of `getBoincAltPlatform` is to get 32bit platform name for 64bit CPUs. Maybe it is not the best name for this function but this is what it actually does. Without this function you can't get 32bit applications on 64bit OS. And it will be more complicated implementations to handle all this in one function `getBoincPlatform`. So personally I'm OK with current behavior.
You already approved this PR but then asked the question so I ask you to approve (or decline) this PR and merge it if everything looks fine for you too

**Pull request merged**
