### PR TITLE
Mac wrapper: build Universal M1 / x86_64 binary

### LINKED ISSUE #4890: Apple M1 Platform Support
**Describe the problem**
Most new Macs are running on Apple M1 silicon (ARM-based). This architecture is currently not supported by BOINC:
https://github.com/BOINC/boinc/blob/master/tools/project.xml

**Describe the solution you'd like**
Support Apple M1 platform (ARM-based) including the BOINC client / manager and the wrapper app.

### PR DESCRIPTION
**Pull request by CharlieFenton**
Fixes #4890

### CODE REVIEW

**Comment by CharlieFenton** [comment]
This PR is ready to be merged when CI checks pass.

**Comment by AenBleidd** [comment]
@CharlieFenton, I don't see this script called when building on CI. Could you please fix this?
If you need my assistance - please let me know

**Comment by CharlieFenton** [comment]
This is not part of building the client or Manager and is rarely updated. (This is the first update since 2015.) None of the items in the _samples_ directory are built using CI: condor, flutter, multi_thread, openclapp, vboxmonitor, vboxwrapper, vm_wrapper, wrapper, wrappture, etc. Other than vwoxwrapper and wrapper, I don't even know what most of these do or are used for.

**Comment by AenBleidd** [comment]
Ok, I'll then handle this separately in a different PR. Thank you.

**Review by AenBleidd — APPROVED** [review]

**Pull request merged**
