### PR TITLE
testCoverageEnabled true only in debug.

### PR DESCRIPTION
**Pull request by talregev**
> If you put it in release, this will make the APK / App Bundle debuggable, and Google Play Console will consider it's not signed. Removing this resolved the issue.

https://stackoverflow.com/a/56823288/550384

For compile signed bundle
#3566

### CODE REVIEW

**Comment by Isira-Seneviratne** [comment]
Hi,

You'll want to update the Travis YAML file to run `combinedTestReportDebug` instead of `combinedTestReportRelease`.

**Comment by talregev** [comment]
@Isira-Seneviratne Thank you! It do the trick.
It search code coverage in build definition files? 
I didn't change any code files.

**Comment by Isira-Seneviratne** [comment]
Yeah, there's a strange issue where the code coverage changes for no apparent reason.

I think @AenBleidd would know more about it.

**Comment by talregev** [comment]
If everything ok, and you approve, can you merge this changes?

**Comment by Isira-Seneviratne** [comment]
I can't do any merging, as I don't have write access to the repo.

**Comment by talregev** [comment]
ok. And you approve this changes? I mean if you agree to this changes.

**Comment by Isira-Seneviratne** [comment]
On Sat, May 2, 2020, 3:56 PM talregev <notifications@github.com> wrote:

> ok. And you approve this changes? I mean if you agree to this changes.
>

Since it's necessary for migrating to App Bundles, I approve.

**Comment by talregev** [comment]
> Since it's necessary for migrating to App Bundles, I approve.

Thank you.

**Pull request merged**
