### PR TITLE
[WIP] Early stage of websocket proxy development

### PR DESCRIPTION
**Pull request by nikolasgianna**
This is a first approach and attempt at creating a proxy to allow the BOINC client to understand commands issued via websockets. The proxy should run within the same executable so that the whole procedure is transparent to the volunteers. As it stands now this is a barely working prototype and should not be expected to function in any meaningful way. For that reason this pull request is not expected or intended to be merged. It is rather a way to start a conversation around the issue and to get more eyes on such an important piece of the potential future BOINC client. 

This is a small test page: https://lhcathomedev.cern.ch/lhcathome-dev/websock_test.html that will return the version of a running client that implements these changes. The communication is done solely through websockets.

Since Firefox expects Secure Websockets (because the javascript is served from an https server) in this stage you will have to create your own certificate and key with:
`openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout server.key -out server.pem`
and then add it by visiting https://localhost:8443 and following the prompts. 

Note: This is only tested on Linux and should not work on Windows or macOs

### CODE REVIEW

**Comment by TheAspens** [comment]
@nikolasgianna - can you put [WIP] at the front of your pull request?  That indicates to everyone that you are interested in them taking a look but that you do not want it merged.

**Comment by nikolasgianna** [comment]
There is already an older version of mongoose inside /samples/gfx_html/ . As far as I can see it is using the same license.

**Comment by nikolasgianna** [comment]
In the process of reviewing websocket libraries one that caught my attention (seems to be very widely used) and that seems to meet all the requirements is this: https://github.com/uNetworking/uWebSockets

Please review and if it is ok I can go on with using it instead of mongoose.

**Comment by TheAspens** [comment]
@nikolasgianna - I'm not a lawyer so my statements have no legal weight.  With that dislaimer aside, the license https://github.com/uNetworking/uWebSockets/blob/master/LICENSE appears to be the zlib license and it appears that the zlib license can be used within a LGPL licensed project https://en.wikipedia.org/wiki/Zlib_License

So I would say you could probably proceed with this library for the websocket server.

**Pull request closed without merging**
