### PR TITLE
client: include platform names in account manager request

### PR DESCRIPTION
**Pull request by davidpanderson**
This lets AMs like TBD make better meta-scheduling decisions

### CODE REVIEW

**Comment by tristanolive** [comment]
The travis build failed for probably no good reason... restarting...

**Comment by tristanolive** [comment]
Still no luck. The manager is taking over 45 minutes to build and is timing out. It only took 6 minutes when building for PR 2261. I'm not familiar enough with travis to know what its problem is, but seeing as how this is a client feature, it would seem to be irrelevant. 

Has anyone seen this sort of behavior from travis elsewhere?

**Comment by ChristianBeer** [comment]
It seems the OSX cache couldn't be retrieved in the last build, so it tried to build all dependencies from scratch which takes a long time. I restarted the OSX build again in the hope that the cache is retrieved.

Please note that the OSX build also builds the Client although it says `type=Manager`. The OSX build is not as flexible as the Linux build.

**Comment by tristanolive** [comment]
Thanks, Christian -- I didn't even notice the Linux vs OSX designation in the job list! [Build for 2270](https://travis-ci.org/BOINC/boinc/builds/313671336) just failed also in the same place, so we'll see if your restart of this one knocks it loose... it looks like it's fetching and building openssl, unfortunately.

**Comment by ChristianBeer** [comment]
Didn't work either but the build job before could retrieve the cache and it still seems intact. I restarted it again but it failed to load the cache again.

It also seems that the dependencies are build within the time limit but the actual BOINC builds takes too long afterward. I'm looking into how to error out the build after dependencies so the cache gets saved and the build will succeed on restart with the newly build cache.

**Comment by ChristianBeer** [comment]
One of the restarted builds succeeded. It seems to me that it also depends on how much other jobs are running on the Travis CI OSX build hosts. Less jobs means our build is faster and finishes within the limit. I restarted the other two builds and once the build in the master branch finishes there should be a valid cache available for future jobs.

There was maintenance on the OSX infrastructure by Travis CI two days ago which seems to have invalidated the OSX caches.

**Comment by ChristianBeer** [comment]
All timed out OSX builds have been restarted and finished without problems but almost triggered the 50 minute timeout again.

**Comment by tristanolive** [comment]
Hopefully those caches are back in business! This was a good learning experience, thanks for walking through it.

**Pull request merged**
