### PR TITLE
Strip HTML tags for the page title

### PR DESCRIPTION
**Pull request by sergeyklay**
**Description of the Change**
Strip HTML tags for the page title.

**Screenshots**
image

**Release Notes**
- Fixed title for the pages that were subject to localization

### CODE REVIEW

**Comment by davidpanderson** [comment]
Let's fix this by changing the call to page_head() in team_members.php.
That's the only call that passes HTML.

**Comment by sergeyklay** [comment]
@davidpanderson Should I leave it as is or change the call to page_head() in team_members.php instead?

**Comment by davidpanderson** [comment]
Please make that change.

**Comment by sergeyklay** [comment]
Done

**Pull request merged**
