### PR TITLE
Mac: upgrade to wxWidgets 3.2.2.1

### PR DESCRIPTION
**Pull request by CharlieFenton**
Upgrade BOINC Manager for Macintosh to use wxWidgets 3.2.2.1

### CODE REVIEW

**Comment by CharlieFenton** [comment]
@AenBleidd @davidpanderson Please merge this only if you feel we should make this change for the next release 7.22.1.

**Comment by AenBleidd** [comment]
I believe this is a good change. I'll review it and merge today.

**Comment by CharlieFenton** [comment]
One more tiny change ...

**Comment by CharlieFenton** [comment]
This PR is ready to be merged.

**Review by AenBleidd — APPROVED** [review]

**Pull request merged**
