### PR TITLE
Format build steps as plain text document

### LINKED ISSUE #3527: Move Mac build instructions to a plain text document
**Describe the problem**

PDF's and RTF's are somewhat cumbersome to work with compared to plain text documents, such as Markdown.

**Describe the solution you'd like**

Move the build steps to a plain text document.

### PR DESCRIPTION
**Pull request by mcandre**
Fixes #3527

**Description of the Change**

Move build steps from PDF and RTF stylized documents into more maintainable plain text (e.g. Markdown) document.

**Release Notes**

Format development documentation as plain text (Markdown)

### CODE REVIEW

**Comment by CharlieFenton** [comment]
I disagree. I believe you are referring to the Mac build instructions. RTD files are very easy to edit with the TextEdit app on Macs, and trivial to then save a copy as a PDF.

The reason I added the PDF version of mac_build/HowToBuildBOINC_XCode.pdf is so that updates to the build instructions will automatically be available via a link from [here](https://boinc.berkeley.edu/trac/wiki/MacBuild). Changing the format will break this.

**Comment by brianclinkenbeard** [comment]
@CharlieFenton You could similarly link to the build instructions with the Markdown document. Using the pull request file you can use [this link](https://github.com/BOINC/boinc/blob/336f1943b59e66d5be73d7df2117bd413de097b9/mac_build/HowToBuildBOINC_XCode.md) as a preview of what it might look like. Once it is merged you could link it the same way as the pdf: https://github.com/BOINC/boinc/blob/master/mac_build/HowToBuildBOINC_XCode.md

The advantage here of a markdown document is that it's more conducive to programming related documents and has code blocks that are better formatted. It also can be edited with any text editor.

**Comment by CharlieFenton** [comment]
> Format development documentation as plain text (Markdown)

>It also can be edited with any text editor.

I don't understand your point here. The original PR #3527 was about the build instructions for Macs. RTF documents are the default output of the TextEdit app, which is supplied on every Mac in `/Applications/Utilities/`. TextEdit is a WYSIWYG text editing tool and is one of the easiest tools for creating RTF files. And it will automatically convert the file to PDF by selecting either  _File/Export as PDF_ or `Print` from its `File` menu.

Both RTF and PDF files are far more widely used and more universally readable than Markdown.

**Comment by brianclinkenbeard** [comment]
> Both RTF and PDF files are far more widely used and more universally readable than Markdown.

For programming projects, this isn’t true. In fact, I have never seen an actively developed project other than BOINC with RTF build instructions. By contrast, nearly every project on GitHub/Gitlab/etc has build instructions in Markdown, either in the source tree or on a Wiki page.

Many developers can more efficiently edit files with text editors like Vim or Emacs than with a document editor. This is simply not possible with RTF. To see what I mean, open an RTF file with a standard text editor.

In addition, I think using something that is familiar is more welcoming to developers and easier to maintain, as @mcandre mentions. RTF files are not suited well for version control since they are more difficult to compare file diffs than with Markdown files.

**Comment by CharlieFenton** [comment]
> Many developers can more efficiently edit files with text editors like Vim or Emacs than with a document editor.

I doubt many Mac programmers use, or even know how to use, Vim or Emacs. The world of Apple (OS X / iOS) programming is very different from Linux / Gnu or MS Windows. I suspect very few OS X or iOS programmers have any in-depth knowledge of UNIX, even though both OS X and iOS are built on top of BSD UNIX.

**Comment by brianclinkenbeard** [comment]
> > Many developers can more efficiently edit files with text editors like Vim or Emacs than with a document editor.
> 
> 
> 
> I doubt many Mac programmers use, or even know how to use, Vim or Emacs. The world of Apple (OS X / iOS) programming is very different from Linux / Gnu or MS Windows. I suspect very few OS X or iOS programmers have any in-depth knowledge of UNIX, even though both OS X and iOS are built on top of BSD UNIX.

Take a look at the [Homebrew installs for Vim](https://formulae.brew.sh/formula/vim), or the popularity of Vim plugins for VSCode, Sublime Text, Atom, the XVim plugin for Xcode, etc. Emacs is certainly more used on Linux, but [Aquamacs](http://aquamacs.org) is somewhat popular and still actively developed.

Whether they are popular is somewhat irrelevant, since they can also be edited directly on GitHub with a built in preview and visual diff. This is more intuitive and in some ways better than a text editor, and even more universal.

It also doesn’t change that Markdown is still better suited for collaboration and maintenance. 

Everything considered, this is a fairly minor change, but build instructions are also part of people’s first impression of the project and have an impact on whether developers contribute.

**Comment by Ageless93** [comment]
You're ignoring what Charlie tells you: most Macintosh developers don't use what you propose. The text documents you are trying to change are build instructions for how to build BOINC on a  Macintosh. They will be download and used/read by developers running a Macintosh computer with OSX, as it makes no sense for a Macintosh developer to run Linux on his system.

**Comment by brianclinkenbeard** [comment]
@Ageless93 Please re-read what I wrote. Homebrew and all the software I mentioned are macOS software. I never mentioned running Linux. Editing Markdown can be done with **any** text editor (including TextEdit), the most intuitive of which is GitHub’s website, which runs within any web browser.

**Comment by RichardHaselgrove** [comment]
All of which is probably a generational thing. Different versions of operating systems include different tools. Different generations of programmers grow up with these different versions of tools. I got a special dispensation from Microsoft to distribute Windows Write (Windows 3 native tool) because WordPad (Windows 95 and later native tool) couldn't do what we had already programmed Windows Write to do. I preferred WordStar, but professional copy-typists (office secretaries) preferred WordPerfect. Things change. Life evolves.

**Comment by CharlieFenton** [comment]
As I wrote earlier:
> The reason I added the PDF version of mac_build/HowToBuildBOINC_XCode.pdf is so that updates to the build instructions will automatically be available via a link from [here](https://boinc.berkeley.edu/trac/wiki/MacBuild). 

Please take a look at the edit history for that Wiki page. You will see that I (along with others) maintained this document for _many years_ using Markdown. 

It was a huge pain to edit the Markdown for the Wiki page, and I never found it conducive to writing clear instructions; the distraction of entering all the Markdown tags interfered with concentrating on the content. For that reason, I always created the RTF file first via Apple's much easier to use WYSIWYG GUI TextEdit app, and then manually converted it to Markdown. I searched for software that would automate the conversion from RTF to Markdown, and found nothing that worked well enough. 

So I searched for a way to allow the frequently changing build instructions document to be automatically available on the Wiki, and discovered that it would work if the document was a PDF. Since Apple's TextEdit can automatically convert RTF files to PDF, that is what I chose.

> Whether they are popular is somewhat irrelevant

Not really. The build instructions aren't useful if the people for whom they are intended don't know how to find the tools to read them. The instructions do not assume any knowledge of GitHub; they are intended to be a very low-level cookbook, usable by people with limited software development experience. That is why everything is done with scripts; you don't even have to know how to use Xcode.

> All of which is probably a generational thing.

@RichardHaselgrove: Yes, I suspect that comes into play here. I made my living as a software engineer for 59 years,  including writing code for Apple, before retiring 5 years ago. I started programming Macs with a prototype of the first Mac II. I continue supporting BOINC as a volunteer because I care about it deeply. I suspect that @brianclinkenbeard has been programming Macs for only a few years.

I was not aware that GitHub offers a WYSIWYG markdown editor; so that would definitely help. Still, the target audience for this document, which includes people who are unaware of GitHub and have not yet installed Xcode, would have difficulty reading a Markdown document.

**Comment by CharlieFenton** [comment]
Since I recognize that @mcandre and @brianclinkenbeard have the best of intentions with this recommendation, I feel I should put my opposition in perspective. 

I've been wanting to step away from maintaining the Macintosh builds of BOINC for several years now, but I have continued to fix critical issues because no one with the requisite deep understanding of both the Mac and BOINC internals has been available to do so. For examples of what this has entailed, please read my comments in PR #2149, #2294, #2726 and #3369, (best understood if read in that order) which all are fixes to BOINC screensaver after OS 10.13, 10.14 and 10.15 each broke the previous version. Other changes included fixing critical problems with the installer, crashes of BOINC Manager when built under older versions of Xcode, crashes on earlier versions of OS X, etc.

The change requested in this PR and #3527 are far from critical and have a vanishingly low priority when compared to the changes I am willing to make and live with. This change would require me, at the least, to learn new text editing tools to be able to maintain and update the build instructions in a manner I consider efficient. I have neither the time nor the interest to do so.

 I explained in my previous comment why I stopped using Markdown on the Wiki; I might consider using it only if **Apple** provided a WYSIWYG Markdown editor as a **standard** part of OS X or Xcode. I looked at GITHub's [markdown documentation](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) and found that it, too requires manually entering all the formatting tags. 

While there are third party WYSIWYG Markdown editors, I feel no third party tools should be required to build BOINC (except for the config and make files in the third party libraries needed by BOINC code.)

I have no objection to revisiting this PR once there are sufficient Mac developers working on BOINC so that fixing critical problems no longer depends on me.

On the positive side, this discussion has helped me realize that, if I hope to get more Mac programmers involved in BOINC, I should create a set of issues describing important but less critical tasks that I would like to see other Mac programmers take on. I will do so in the next few days and add links them here.

**Comment by CharlieFenton** [comment]
Before I leave this thread, I want to note a few observations while they are fresh in my mind.
> You could similarly link to the build instructions with the Markdown document. Using the pull request file you can use [this link](https://github.com/BOINC/boinc/blob/336f1943b59e66d5be73d7df2117bd413de097b9/mac_build/HowToBuildBOINC_XCode.md) as a preview of what it would look like.

[1] While the link does display the properly formatted document, it shows it in a box inside other GitHub information. While usable, this is less than ideal, as it may confuse or intimidate a beginner. 

[2] That  is usable to view the build instructions for the master (development) branch, but perhaps the most important information is the second paragraph:

> Note: the information in this document changes from time to time for different versions of BOINC.  For any version of BOINC source files, the corresponding version of this document can be found in the source tree at: boinc/mac_build/HowToBuildBOINC_XCode.rtf

The purpose of displaying the the master branch build instructions is just to get the user started, so they can clone the source tree onto their computer. Then the user should read the instructions for the branch they are building from the source tree they have cloned onto their Mac.

If someone wants to build, for example, BOINC 7.14.3, they would clone the `client_release/7/7.14` branch and checkout the `client_release/7.14/7.14.3` tag. But they would have no convenient way to view the properly formatted `mac_build/HowToBuildBOINC_XCode.md` file which has the specific instructions for building that version from their local repository. I tried viewing it with Xcode; though the display approximates the correct formatting, it is not quite right, perhaps because GitHub uses its own version of the Markdown syntax. TextEdit and Safari show the raw, unformatted text, including the markdown tags. Preview won't open it at all. The RTF file displays correctly in Xcode and TextEdit; the PDF displays correctly in Xcode, TextEdit, Safari, and Preview.

While one could install third party apps which might display the document with formatting, they too would likely not understand GitHub's non-standard tags. And requiring the user to download an app just to read the build instructions goes against the intent of simplifying the build process by providing simple, low-level instructions. One should be able to build using only Apple's standard tools provided by OS X and Xcode.

[3] @brianclinkenbeard: could you please explain how you converted the RTF or PDF file into GitHub Markdown? Was there a tool that allows you to do this automatically, or did you need to enter all the Markdown tags manually? If the conversion can be automated, then it might make sense to have both RTF and Markdown versions of the document rather than RTF and PDF.

**Comment by adamradocz** [comment]
I strongly agree that the Wiki should have been created ages ago. If I want to look up something in any project, my first thing is to check its Wiki.

**Comment by AenBleidd** [comment]
Am I so old-fashioned? Because in the situation you describe, @adamradocz, I'm still looking for README file in source root 🤣

**Comment by adamradocz** [comment]
> Am I so old-fashioned? Because in the situation you describe, @adamradocz, I'm still looking for README file in source root 🤣

Yeah, that's the first step. :) But usually, the detailed info placed in the Wiki. E.g the Vagrant readme should be a Wiki page IMO.

**Comment by CharlieFenton** [comment]
@adamradocz & @AenBleidd" This discussion has been specifically about the Mac build instructions, which are in the source tree at macbuild/HowToBuildBOINC_XCode.rtf and accessible from the Wiki [here](https://boinc.berkeley.edu/trac/wiki/MacBuild).

Instructions for building other platforms are here for [Android](http://boinc.berkeley.edu/trac/wiki/AndroidBuildClient), [Windows](http://boinc.berkeley.edu/trac/wiki/BuildClientProcedure), Unix is [here](http://boinc.berkeley.edu/trac/wiki/SoftwarePrereqsUnix) and [here](http://boinc.berkeley.edu/trac/wiki/BuildSystem), partial info for Linux is [here](http://boinc.berkeley.edu/trac/wiki/PrepareLinuxBuildMachine). [This](http://boinc.berkeley.edu/trac/wiki/SoftwareBuilding) is a collection of links to some of these. I know the Mac instructions are current; I can't speak to whether or not the others are up to date.

So yes, instructions for Linux are missing; i don't know how applicable the Unix instructions are.

**Comment by RichardHaselgrove** [comment]
Another useful page is [CompileClient](http://boinc.berkeley.edu/trac/wiki/CompileClient) - brief notes for Linux, working instructions for Windows, and a link for Mac.

**Comment by AustinConlon** [comment]
> @Ageless93 Please re-read what I wrote. Homebrew and all the software I mentioned are macOS software. I never mentioned running Linux. Editing Markdown can be done with **any** text editor (including TextEdit), the most intuitive of which is GitHub’s website, which runs within any web browser.

I second this, I considered proofreading and editing the Mac build instructions (https://github.com/BOINC/boinc/blob/master/mac_build/HowToBuildBOINC_XCode.rtf) directly in the GitHub editor, but RTF files clearly do not fit with the interface.

**Comment by CharlieFenton** [comment]
@mcandre and @AustinConlon: **Thank you for wanting to contribute to BOINC.** I can suggest a number of tasks that would be especially helpful (see below), rather than suggesting extra work to fix something that does not need fixing. And, once you are up to speed on all the intricacies and special considerations involved, I would be delighted to have you and others take over the future maintenance of BOINC for the Mac. 

Once that has happened, I will gladly support your maintaining the build instructions in any form you feel appropriate. But as long as I am the only one doing the bulk of Mac development, I respectfully ask that you honor the way I prefer to work and not propose changes that add to my workload.

>I considered proofreading and editing the Mac build instructions ... directly in the GitHub editor, but RTF files clearly do not fit with the interface.

Since I am the author and maintainer of these build instructions, and have been for many years, it would have been polite and appropriate to express any concerns about this document to me before you took it upon yourselves to "proofread and edit" them. 

While you certainly may have fine suggestions for improvement, you also may not know my reasons for writing it the way I have, given that I have been the sole maintainer of BOINC's Mac-specific code and Mac builds.

The build instructions have evolved from files written long before GitHub existed. Editing RTF files on a Mac is at least as easy with TextEdit on a Mac as editing markdown files through GitHub's web interface. Exporting them from TextEdit to a PDF file (so they can be linked from the [BOINC wiki](https://boinc.berkeley.edu/trac/wiki/MacBuild)) is also trivial. 

Here are some examples of tasks you could undertake to help with Mac development for BOINC:

* The Mac accessibility code uses APIs and techniques which Apple deprecated as of OS 10.10. The current code is based on these Apple code sample [here](https://developer.apple.com/library/archive/samplecode/Sketch+Accessibility/Introduction/Intro.html) and [here](https://developer.apple.com/library/archive/samplecode/AccessibilityUIExamples/Introduction/Intro.html).

* Updating to the latest _wxWidgets_. (This is far from trivial for a number of reasons which may not be immediately apparent.)

 * _OpenGL_ and _GLUT_ are used by all projects that have graphics apps (primarily for the screensavers.)  Apple deprecated  _OpenGL_ and _GLUT_ as of OS 10.9. It is unreasonable to ask understaffed projects to rewrite their code, so we need to find compatible, free, open source, third-party _OpenGL_ and _GLUT_ libraries that BOINC can install if and when Apple actually removes them.

* Using Apple's Developer Transition Kit now, or a production _Apple Silicon_ (arm64) Mac when available, to test and debug BOINC's code to run natively on _Apple Silicon_ Macs. Of particular concern is the _OpenSSL_ library. I have taken this as far as posslible using Xcode 12 beta under macOS 11 beta on an x86_64 mac.

* Determine whether x86_64 project applications, and particularly project graphics apps, run properly when emulated by Apple's _Rosetta 2_ on _Apple Silicon_ Macs.

Please contact me for more information on any of these tasks.

**Comment by AustinConlon** [comment]
> Since I am the author and maintainer of these build instructions, and have been for many years, it would have been polite and appropriate to express any concerns about this document to me before you took it upon yourselves to "proofread and edit" them.

Hi Charlie,

It definitely wasn't my intention to step on your toes with the documentation or fundamentally change the instructions, by proofreading I meant just minor edits. I'm accustomed to the Swift project on GitHub where anyone can submit pull requests with documentation edits no matter how small. My thinking with that and with agreeing with this original issue posted is that it would encourage as many Mac developers as possible to contribute.

Your points are taken that there are bigger fish to fry.

**Comment by davidpanderson** [comment]
One thing would be to write a script to convert the Trac wiki to Github format: #2820 
I started this but didn't finish.

**Comment by mcandre** [comment]
The whole point of Markdown is to present a lightweight, easy to read format. It was deliberately designed as an alternative to HTML for that reason.

If you don't like reading Markdown, that's fine. You can go to the bother of pandoc'ing a PDF. But the source text should be made available in version control, ideally in Markdown, a very common format used to convey basic build instructions.

**Comment by AenBleidd** [comment]
Closing this without merging as the original ticket should be discussed further to make a better solution. Also, provided MD file is outdated in any case, so there is no reason to keep it open

**Pull request closed without merging**
