### PR TITLE
Manager: 'Add Project Wizard': disable 'Next' button on wrong credent…

### LINKED ISSUE #1048: When adding a project, failed username/password should not show Next, and should not place the failures on a stack.
**Reported by JacobKlein on 30 Mar 41246410 06:40 UTC**
When adding a project, if you do not use the correct email address or password, you get a dialog that says:[Failed.[[BR]([BR]]Login)]Check the email address and password, and try again.

The problem is that you are allowed to click Next.  You should not be allowed to click Next. You should be forced to click Back or Cancel or close the window.

As a side-effect, if you click Next, Try again, Fail, Next, try again, Fail... it places all of these failures on a stack, such that you can then click Back Back Back to see several failed login screens within the wizard.

Please do not allow "Next" on a failed login when adding a project.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1072

### PR DESCRIPTION
**Pull request by AenBleidd**
…ials

Fixes #1048.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
This fixes #1048

**Comment by AenBleidd** [comment]
@Ageless93, @ChristianBeer, could you please review this? Thanks

**Comment by CharlieFenton** [comment]
Line 554 of clientgui/wizardex.cpp has `m_btnNext->SetDefault();` so the disable button will be set as the default button, which is incorrect. You should also change the default button to the 'Back' button.

**Comment by AenBleidd** [comment]
@CharlieFenton, could you please review this? Thanks

**Comment by CharlieFenton** [comment]
I have one minor comment: the commit message is slightly misleading. It doesn't _enable_ the back button, it makes it the _default_. But that is not a significant issue, so I will go ahead and merge this.

**Pull request merged**
