### PR TITLE
[WIP] 4261

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
(please don't merge! its to trigger CI tests for #4252)

### CODE REVIEW

**Comment by talregev** [comment]
You can change the title with prefix of [WIP], also you can mark this PR as a draft. It still check your PR.

**Comment by talregev** [comment]
Please be aware when you add the parameter with env params, it recognize it as empty because it not define elsewhere. (for example `${prefix}`)  I think you better you replace the env param with the actual value. (instead of `${prefix}`, you can type `/usr`).

**Comment by LocutusOfBorg** [comment]
ok to trigger the issue just add "--disable-apps", its now fully reproducible.

**Comment by LocutusOfBorg** [comment]
@talregev I hope this clears things?

**Comment by talregev** [comment]
I will see the result in the ci. If it fail, it clear things. 
Thank you for your time to reproduce the bug.

**Comment by LocutusOfBorg** [comment]
Thanks to you!
I admit I'm more a cmake fan, so I find difficult to provide patches! :)
In any case with --enable apps:
https://github.com/BOINC/boinc/runs/2106851112
```
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
```

without it:
https://github.com/BOINC/boinc/runs/2106808243
```
checking if gcc supports -c -o file.o... (cached) yes
./configure: line 14691: : supported targets:.* elf: command not found
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... no
checking dynamic linker characteristics... GNU/Linux ld.so
```
Basically it fallsback to static libraries due to this

**Comment by LocutusOfBorg** [comment]
The --disable-apps is probably useless, but I wanted to prove my point, yes we can simply remove it of course :) just I don't want to rely on default values when I check where is the culprit of an issue!

**Comment by talregev** [comment]
Because in my PR, I try with `--enable-apps` and without it. Maybe when you put --disable-apps it doing something unexpecting.

**Comment by talregev** [comment]
I try now in my PR with `--disable-apps`. I will see the result also in my PR.
Also I am cmake fan, so I understand your pain.

**Comment by LocutusOfBorg** [comment]
>Because in my PR, I try with --enable-apps and without it. Maybe when you put --disable-apps it doing something unexpecting.

you know that your build fails, right?
If you look at your build, it just discards building shared libraries because that check above fails.
https://github.com/BOINC/boinc/runs/2103270750

```
g++ -g -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -DAPP_GRAPHICS -I../.. -I../../lib -I../../api -I../../zip -I/usr/include/freetype2 -L /usr/X11R6/lib -L.   -o uc2 uc2.o libstdc++.a -pthread \
../../api/libboinc_api.a \
../../lib/libboinc.a
g++ -g -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -DAPP_GRAPHICS -I../.. -I../../lib -I../../api -I../../zip -I/usr/include/freetype2 -L /usr/X11R6/lib -L.   -c -o ucn.o ucn.cpp
g++ -g -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -DAPP_GRAPHICS -I../.. -I../../lib -I../../api -I../../zip -I/usr/include/freetype2 -L /usr/X11R6/lib -L.   -o ucn ucn.o libstdc++.a -pthread \
../../api/libboinc_api.a \
../../lib/libboinc.a
make[3]: Leaving directory '/home/runner/work/boinc/boinc/samples/example_app'
Making all in multi_thread
```

Its creating static libraries anyway.
If the check succeeds, the make install step should fail...

**Comment by talregev** [comment]
> you know that your build fails, right?

My build fail without `--enable-apps`? I will test it again.

**Comment by LocutusOfBorg** [comment]
yes it does!

I mean, the configure check for "shared libraries" fails, so it just fallsback to static libraries.

cfr my build
https://github.com/BOINC/boinc/runs/2106571910

**Comment by talregev** [comment]
I really don't understand. I miss something what you trying to say. 

> g++ -g -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -DAPP_GRAPHICS -I../.. -I../../lib -I../../api -I../../zip -I/usr/include/freetype2 -L /usr/X11R6/lib -L.   -o uc2 uc2.o libstdc++.a -pthread \
> ../../api/libboinc_api.a \
> ../../lib/libboinc.a
> g++ -g -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -DAPP_GRAPHICS -I../.. -I../../lib -I../../api -I../../zip -I/usr/include/freetype2 -L /usr/X11R6/lib -L.   -c -o ucn.o ucn.cpp
> g++ -g -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -fno-common -DAPP_GRAPHICS -I../.. -I../../lib -I../../api -I../../zip -I/usr/include/freetype2 -L /usr/X11R6/lib -L.   -o ucn ucn.o libstdc++.a -pthread \
> ../../api/libboinc_api.a \
> ../../lib/libboinc.a
> make[3]: Leaving directory '/home/runner/work/boinc/boinc/samples/example_app'

What are you showing me here is part of --enable-apps. What happen if you remove it. it compile the client with static?
some of the makefile of the apps, are explicitly tell to compiler to use .a library. I change it in my other PR.

**Comment by talregev** [comment]
@LocutusOfBorg Do you mind to talk with me on discord of boinc?
I can send you a link here if you don't find. It faster that way.

**Pull request closed without merging**
