### PR TITLE
[Android][Scripts] armv6 support

### PR DESCRIPTION
**Pull request by talregev**
armv6 support

### CODE REVIEW

**Comment by talregev** [comment]
armv6

**Comment by talregev** [comment]
Screenshot_2020-07-11-08-38-45
Screenshot_2020-07-11-08-39-38
Screenshot_2020-07-11-08-40-40

**Comment by AenBleidd** [comment]
Please remove this commit: 16134748ac4cecb3ea87787e638a7df3d2003d62

**Comment by talregev** [comment]
@AenBleidd Removed.

**Comment by truboxl** [comment]
Here's my take on this.

Generally speaking if no project wants to add support for Android armv6, having a BOINC client for it is a waste of time.
Also all, Android 32bit has an expire date in approx. 18 years from now aka Year 2038 bug.
https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md

Its unlikely Google will fix this and even so, OEM will not go back creating updates for version 6.x and below Android phones.

**Comment by talregev** [comment]
@AenBleidd Fix conflicts with master.

**Comment by AenBleidd** [comment]
After careful consideration I decided to close this PR.
Main reason: we want to target newer devices more (the same as Projects do). There are too few ARMv6 based devices nowadays and they are too slow in comparison with newest ARM CPUs.

**Pull request closed without merging**
