### PR TITLE
- Tag for 7.6.34 release

### PR DESCRIPTION
**Pull request by Claggy3**
client_release/7.6/7.6.34

### CODE REVIEW

**Comment by CharlieFenton** [comment]
Hi Claggy,

If I understand correctly, Rom always copied / merged the changes from the GIT Head / Trunk since the previous tag / release to the 7/6 branch before tagging, otherwise those changes won't be included in the release. I suspect the porting can be a fairly laborious task, though I don't know GIT well enough to say so for sure; there may be a shortcut to accomplish it. At this point, very few of the changes in Head have been ported to the 7.6 branch.

Is that what you intended? I've copied Rom so he can clarify or elaborate if needed.

Cheers,
--Charlie

**Comment by ChristianBeer** [comment]
This is the list of commits that were added to branch client_release/7/7.6 since the tag for 7.6.33 (omitted localization updates, top is newest):
```
980b8c8899 Fix Windows build by including needed headers.
891fc2d455 remove dependence of boinc_api.h on str_replace.h
7c5d19e962 client: prioritize network (including GUI RPC) over async file ops
6e086d7a88 lib: fix Win compile warning
7fe5c0d386 remove dependency of coproc.h on str_replace.h
c7ea06eeb1 Unix build: add str_replace.h to list of installed .h files
01311b1a87 client: fix bug that could cause idle CPUs/GPUs.
e5bf00ce61 client: win compile fix
b3654451b8 client (Win): add config option to not do proxy autodetect
7f17ea1380 client: task properties tweak
d866d139aa client: Win typo fix
28dbe1d6ff client: fix problems w/ tempfile generation for async file operations
94c16ebd49 client: change temp file prefixes to 5 chars
66b9ed1de9 client: fix minor memory leak
66956a5e74 client: fix bug where concurrent async file operations use same temp file
c108e5bcc1 Fix even more file permissions
c1c45d4b4e Fix permissions on *.po files.
3cbb5d5ae9 Revert "Mac: Update to build with openssl 1.1.0, c-ares 1.11.0 and curl 7.50.2."
084d11da00 Mac: Minor clean up of Xcode project from previous commit
37789e681b Mac: Update to build with openssl 1.1.0, c-ares 1.11.0 and curl 7.50.2.
3de66ee42a WINBUILD: Update version to 7.6.33
```

My question is also: What is the intend of this request? Build a version from September last year? Fix a specific problem in 7.6.33 with a new release? I would appreciate a bit more discussion on boinc_dev in this matter.

**Comment by AenBleidd** [comment]
Hello all,
By the way, what is the workflow of merging into release branch? There were
made many fixes and were implemented many new features into trunk but they
are not released yet. Who decides when and what need to be copied?
Thanks

Best regards,
Vitalii

Sent via Android

13 февр. 2017 г. 9:24 пользователь "Christian Beer" <
notifications@github.com> написал:

This is the list of commits that were added to branch client_release/7/7.6
since the tag for 7.6.33 (omitted localization updates, top is newest):

980b8c8899 Fix Windows build by including needed headers.
891fc2d455 remove dependence of boinc_api.h on str_replace.h
7c5d19e962 client: prioritize network (including GUI RPC) over async file ops
6e086d7a88 lib: fix Win compile warning
7fe5c0d386 remove dependency of coproc.h on str_replace.h
c7ea06eeb1 Unix build: add str_replace.h to list of installed .h files
01311b1a87 client: fix bug that could cause idle CPUs/GPUs.
e5bf00ce61 client: win compile fix
b3654451b8 client (Win): add config option to not do proxy autodetect
7f17ea1380 client: task properties tweak
d866d139aa client: Win typo fix
28dbe1d6ff client: fix problems w/ tempfile generation for async file operations
94c16ebd49 client: change temp file prefixes to 5 chars
66b9ed1de9 client: fix minor memory leak
66956a5e74 client: fix bug where concurrent async file operations use
same temp file
c108e5bcc1 Fix even more file permissions
c1c45d4b4e Fix permissions on *.po files.
3cbb5d5ae9 Revert "Mac: Update to build with openssl 1.1.0, c-ares
1.11.0 and curl 7.50.2."
084d11da00 Mac: Minor clean up of Xcode project from previous commit
37789e681b Mac: Update to build with openssl 1.1.0, c-ares 1.11.0 and
curl 7.50.2.
3de66ee42a WINBUILD: Update version to 7.6.33

My question is also: What is the intend of this request? Build a version
from September last year? Fix a specific problem in 7.6.33 with a new
release? I would appreciate a bit more discussion on boinc_dev in this
matter.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BOINC/boinc/pull/1784#issuecomment-279311944>, or mute
the thread

**Comment by Claggy3** [comment]
It's a stepping stone to getting a more recent Boinc 7.6 released, at one point they said they were going to do more frequent tags,
that didn't really happen, having a mid point since Boinc 7.6.33 was tagged in June 16 minimises the number of commits  that might be probmatic. and gives a fallback version if there are later commits that cause trouble.

**Comment by ChristianBeer** [comment]
Releasing a new client version is a multi-step process. At the start there is the version change commit and a git lightweight tag on that commit but then someone has to build official binaries for all platforms and package them into the respective installer bundles.

Technically what you submitted is the first step, someone else would need to create the git tag and build the official installers from that. Then begins the testing of these packages. Then this someone (usually called Release Manager) adds commits from master to the release branch and creates a new version and so on.

So unless there is a Release Manager who actually prepares and does a release, I don't see a reason to do the version change or tagging.

Also from a technical perspective this should all be done from within the BOINC repository because every PR always introduces a merge commit which should be avoided in the release branch (because it is very confusing later on).

**Comment by ChristianBeer** [comment]
I'm closing this because of the reasons stated above.

**Pull request closed without merging**
