### PR TITLE
[CI][OSX] Specify to build FreeType library without brotli support

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@CharlieFenton, please review

**Review by CharlieFenton — COMMENTED** [review]
The code looks correct by inspection, but you have not included any changes to BuildMacBOINC-CI.sh that allow CI to build the ss_app target. So I can't tell whether the change actually fixes the problem of missing symbols in the linker.

Please add that so I can confirm that the change actually works as intended.

**Review by CharlieFenton — APPROVED** [review]
I see you have shown this fixes the problem in #4836, so I approve this request. Don't forget to also update BuildMacBOINC-CI.sh either in this PR or a separate one.

**Comment by AenBleidd** [comment]
@CharlieFenton, thanks for the review. I'll update BuildMacBOINC-CI.sh in a second PR to not mix the changes

**Pull request merged**
