### PR TITLE
[Android] Alter some strings to use placeholders.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
**Description of the Change**
Make use of placeholders in some string resources.

**Release Notes**
N/A

### CODE REVIEW

**Comment by Ageless93** [comment]
One request, if there are new strings that these will be pushed to Transifex ahead of full testing the new Android client, so that us translators can translate these to our languages and these can be included in the new version.

**Comment by Isira-Seneviratne** [comment]
> 
> 
> One request, if there are new strings that these will be pushed to Transifex ahead of full testing the new Android client, so that us translators can translate these to our languages and these can be included in the new version.

There aren't any new strings, but some existing ones have been modified.

**Comment by Ageless93** [comment]
Even if existing ones have been modified, they need to be translated again as the meaning may have changed.

**Comment by Isira-Seneviratne** [comment]
> 
> 
> Even if existing ones have been modified, they need to be translated again as the meaning may have changed.

So how should the changes be pushed to Transifex?

**Comment by AenBleidd** [comment]
In suitable time I'll ask David to do this

**Pull request merged**
