### PR TITLE
client: fix BSD build (from Larry Rosenman)

### PR DESCRIPTION
**Pull request by davidpanderson**

### CODE REVIEW

**Comment by lrosenman** [comment]
This also addresses some of the issues in #1961

**Comment by TheAspens** [comment]
Although I cannot test the change, the code isolates the changes to BSD and it passed the build tests, so I'm going to proceed with merging this request.

**Comment by TheAspens** [comment]
Thanks @lrosenman  for contributing!

**Comment by lrosenman** [comment]
For the record with these patches in, my user that was segfaulting reports correct operation.  Thanks for merging.

**Pull request merged**
