### PR TITLE
Delete unnecessary checks before calls of the function “free”

### PR DESCRIPTION
**Pull request by elfring**
**Description of the Change**
[The function “free”](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") is documented in the way that no action shall occur for a passed null pointer.
:thought_balloon: Redundant safety checks can be avoided.

**Release Notes**
An analysis by the means of the Coccinelle software pointed the potential out to simplify some source code places.
Thus extra null pointer checks could be omitted in some function implementations.

### CODE REVIEW

**Comment by AenBleidd** [comment]
Unfortunately, I can't accept this PR. The reason is the same as 7 years ago: https://github.com/BOINC/boinc/issues/1721#issuecomment-265589820

**Comment by elfring** [comment]
:crystal_ball: Would you still like to support programming interfaces for the function “free” which are not standard compliant?

**Comment by AenBleidd** [comment]
> 🔮 Would you still like to support programming interfaces for the function “free” which are not standard compliant?

If everything works currently without issues - then why not?

How this PR improves anything?
Does it make code faster - I doubt.
Does it improves user experience - definitely no.
Does it improves code readability - also no, because the purpose of these checks is quite obvious.

So why to spend time doing PRs that will fix nothing and improve nothing instead of fixing real existing issues?
We have 506 open tickets. Are you sure there is no any single ticket that you could fix and really improve the BOINC?

**Comment by elfring** [comment]
>If everything works currently without issues - then why not?

I assume that the desire for benefits from standard compliant programming interfaces can grow.


>How this PR improves anything?

I tend to interpret the presented change possibilities in this way.


>Does it make code faster? - I doubt.

A bit less source code can influence run time characteristics also in desirable directions.


>Does it improves user experience? - definitely no.

This was not directly the intention for the shown transformation.


>Does it improves code readability? - also no, because the purpose of these checks is quite obvious.

The C++ programming language supports improved coding styles, doesn't it?

**Comment by AenBleidd** [comment]
> I assume that the desire for benefits from standard compliant programming interfaces can grow.

We support building BOINC for different platforms on different OSs. We can't verify that every library on all these OSs are complaint.

> A bit less source code can influence run time characteristics also in desirable directions.

I highly doubt there will be any significant performance improvements.

> The C++ programming language supports improved coding styles, doesn't it?

True, but it also doesn't force you to not do any additional checks if you want to be sure your code is safe and stable.

The solution you propose is fine, but it doesn't fix anything and improve nothing. At the same time your change might break some builds we're not aware about. And we have no possibility to test upfront on every platform we currently support.

If you want to improve the code and fix code issues that might have impact - I can grant you access to our Coverity project.

Otherwise before opening any PR, please open the corresponding ticket to start discussion, and then you will save your time by not implementing something that will be rejecting, and our time by eliminating such a discussions.

Thank you in advance.

**Comment by elfring** [comment]
>We can't verify that every library on all these OSs are complaint.

:thought_balloon: I imagine that software build systems can be designed in the way that such development concerns would be handled better.


>I highly doubt there will be any significant performance improvements.

:crystal_ball: Will interests grow so that corresponding measurements will become more attractive?

**Comment by AenBleidd** [comment]
> Will interests grow so that corresponding measurements will become more attractive?

If you want to do such measurements - sure, go ahead.
I specifically checked every change in this PR: there is no a single change here that affects a function that is called very often to make any performance impact.

**Pull request closed without merging**
