### PR TITLE
Client: use cuDeviceTotalMem_v2() if available to get >4GB mem size for NVIDIA GPUs

### LINKED ISSUE #1773: Newer Nvidia GPUs with more than 4GB memory, report max 4GB memory under CUDA
As reported on the [BOINC forums](https://boinc.berkeley.edu/dev/forum_thread.php?id=11430), with newer Nvidia GPUs with more than 4 gigabyte video memory, BOINC reports they have a max of 4096MB for CUDA. OpenCL detects the memory correctly. 

Checking https://github.com/BOINC/boinc/blob/master/client/gpu_nvidia.cpp, line 195, total memory is checked with an int. An int is 32bit, thus the maximum memory it can address is 4GB. In this case I think it needs a long long int here (referencing http://en.cppreference.com/w/cpp/language/types) to be able to detect over 4GB of memory (64bit).

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #1773

**Description of the Change**

**Alternate Designs**

**Release Notes**

### CODE REVIEW

**Comment by AenBleidd** [comment]
Looks like this fix isn't exactly correct because `p_cuDeviceTotalMem_v2` is declared for Windows only but is used for Android and linux too and thus is failing. Is this patch for Windows only?

**Comment by KeithMyers** [comment]
I thought the checkmarks meant it completed a build artifact successfully.
But I see it didn't for the Linux amd64 artifact with the V2 function declaration name.
So I guess David's simplification of Ville's original code was not complete.
If you use the original code, it compiles fine.

**Comment by RichardHaselgrove** [comment]
I see

> Artifact name is valid!
> Container for artifact "linux_client-vcpkg_bd320db3f9b[16](https://github.com/BOINC/boinc/runs/6735902081?check_suite_focus=true#step:28:17)0538f43a4eaf438da729ded4a74" successfully created. Starting upload of file(s)
> Total size of all the files uploaded is 3428396 bytes
> File upload process has finished. Finalizing the artifact upload
> Artifact has been finalized. All files have been successfully uploaded!

If somebody can give me a guide for where it's been uploaded **to**, I'll give it a test.

**Comment by RichardHaselgrove** [comment]
Never mind, I've found both

> linux_client-vcpkg_bd320db3f9b160538f43a4eaf438da729ded4a74.zip
> win_client_x64_bd320db3f9b160538f43a4eaf438da729ded4a74.zip

and downloaded them to their respective platforms. I think we can take it from the CI tests that the code is now syntactically correct: I'll be on the lookout for logic bombs that may have crept into the repository alongside the intended changes, as happened with the early attempts at releasing v7.16

**Comment by RichardHaselgrove** [comment]
First problem: it appears not to work under Linux.

> Sat 04 Jun 2022 08:14:29 BST |  | Starting BOINC client version 7.19.0 for x86_64-pc-linux-gnu
> Sat 04 Jun 2022 08:14:30 BST |  | CUDA: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 470.99, CUDA version 11.4, compute capability 7.5, 4096MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 08:14:30 BST |  | CUDA: NVIDIA GPU 1: NVIDIA GeForce GTX 1660 Ti (driver version 470.99, CUDA version 11.4, compute capability 7.5, 4096MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 08:14:30 BST |  | OpenCL: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 470.129.06, device version OpenCL 3.0 CUDA, 5942MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 08:14:30 BST |  | OpenCL: NVIDIA GPU 1: NVIDIA GeForce GTX 1660 Ti (driver version 470.129.06, device version OpenCL 3.0 CUDA, 5945MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 08:14:30 BST |  | Version change (7.18.1 -> 7.19.0)

Sat 04 Jun 2022 08:14:30 BST |  | OS: Linux Linuxmint: Linux Mint 20.3 [5.4.0-113-generic|libc 2.31]

**Comment by RichardHaselgrove** [comment]
But it does under Windows:

> 04/06/2022 08:23:08 |  | CUDA: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 472.12, CUDA version 11.4, compute capability 7.5, 6144MB, 3032MB available, 5622 GFLOPS peak)
> 04/06/2022 08:23:08 |  | CUDA: NVIDIA GPU 1: NVIDIA GeForce GTX 1650 SUPER (driver version 472.12, CUDA version 11.4, compute capability 7.5, 4096MB, 3034MB available, 4531 GFLOPS peak)
> 04/06/2022 08:23:08 |  | OpenCL: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 472.12, device version OpenCL 3.0 CUDA, 6144MB, 3032MB available, 5622 GFLOPS peak)
> 04/06/2022 08:23:08 |  | OpenCL: NVIDIA GPU 1: NVIDIA GeForce GTX 1650 SUPER (driver version 472.12, device version OpenCL 3.0 CUDA, 4096MB, 3034MB available, 4531 GFLOPS peak)

04/06/2022 08:23:08 |  | OS: Microsoft Windows 7: Professional x64 Edition, Service Pack 1, (06.01.7601.00)

though I'm a little worried about the 'available' figure.Machine was lightly loaded at startup (all GPU task suspended), GPUs only in use for screen driving. Perhaps someone from GPUUG could comment?

**Comment by RichardHaselgrove** [comment]
I suspect we have to add another _v2 variant after

https://github.com/BOINC/boinc/blob/master/client/gpu_nvidia.cpp#L228

**Comment by RichardHaselgrove** [comment]
Ah - that's in the bd320db3f9b160538f43a4eaf438da729ded4a74 commit. It may compile, but it doesn't seem to work.

**Comment by KeithMyers** [comment]
I pose the question . . . why not just use Ville's code as-is?

**Comment by RichardHaselgrove** [comment]
> I pose the question . . . why not just use Ville's code as-is?

Because it's not clear that he has complied with the terms of the GNU Lesser General Public License in preparing it.

**Comment by RichardHaselgrove** [comment]
Thanks - I'll wait for CI to finish, and load the new artifact on my Linux testbed.

**Comment by KeithMyers** [comment]
Richard can you give me a clue where to find the uploaded artifacts.

**Comment by RichardHaselgrove** [comment]
Scroll down to the very bottom of the checks list. Click on 'details' for one or other of the "Test Reports (pull request)" lines.

On the next page, look at the left-hand column. Below the highlighted entry, select "On: pull_request" for the OS you want to test. The list of artifacts should  be shown in the bottom half of the right-hand column. 

Click on the filename for your selected variant. I'm going for linux_client-vcpkg_4a55c58d749ba55303b66ed98b777141d305e2d4

**Comment by RichardHaselgrove** [comment]
And it worked:

> Sat 04 Jun 2022 19:50:11 BST |  | CUDA: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 470.99, CUDA version 11.4, compute capability 7.5, 5942MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 19:50:11 BST |  | CUDA: NVIDIA GPU 1: NVIDIA GeForce GTX 1660 Ti (driver version 470.99, CUDA version 11.4, compute capability 7.5, 5945MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 19:50:11 BST |  | OpenCL: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 470.129.06, device version OpenCL 3.0 CUDA, 5942MB, 3972MB available, 5530 GFLOPS peak)
> Sat 04 Jun 2022 19:50:11 BST |  | OpenCL: NVIDIA GPU 1: NVIDIA GeForce GTX 1660 Ti (driver version 470.129.06, device version OpenCL 3.0 CUDA, 5945MB, 3972MB available, 5530 GFLOPS peak)

CUDA memory size report now matches OpenCL report.

**Comment by KeithMyers** [comment]
Thanks. I was looking in the wrong place.  Right at the top in Summary.

Looks like David isn't bothering to check for 32 bit systems.

Happy to see the code is mostly working.  The reported available memory is wrong though.  Looks like it is only reporting 32 bits of memory.

This is David's client report.

04-Jun-2022 12:07:06 [---] CUDA: NVIDIA GPU 0: NVIDIA GeForce RTX 2080 (driver version 510.73, CUDA version 11.6, compute capability 7.5, 7982MB, **3966MB available**, 10598 GFLOPS peak)
04-Jun-2022 12:07:06 [---] CUDA: NVIDIA GPU 1: NVIDIA GeForce RTX 2080 (driver version 510.73, CUDA version 11.6, compute capability 7.5, 7979MB, **3966MB available**, 10598 GFLOPS peak)
04-Jun-2022 12:07:06 [---] CUDA: NVIDIA GPU 2: NVIDIA GeForce RTX 2080 (driver version 510.73, CUDA version 11.6, compute capability 7.5, 7982MB, **3966MB available**, 10598 GFLOPS peak)
04-Jun-2022 12:07:06 [---] OpenCL: NVIDIA GPU 0: NVIDIA GeForce RTX 2080 (driver version 510.73.05, device version OpenCL 3.0 CUDA, 7982MB, 3966MB available, 10598 GFLOPS peak)
04-Jun-2022 12:07:06 [---] OpenCL: NVIDIA GPU 1: NVIDIA GeForce RTX 2080 (driver version 510.73.05, device version OpenCL 3.0 CUDA, 7979MB, 3966MB available, 10598 GFLOPS peak)
04-Jun-2022 12:07:06 [---] OpenCL: NVIDIA GPU 2: NVIDIA GeForce RTX 2080 (driver version 510.73.05, device version OpenCL 3.0 CUDA, 7982MB, 3966MB available, 10598 GFLOPS peak)

And this is the report from Ville's client

03-Jun-2022 09:51:34 [---] Data directory: /home/keith/Desktop/BOINC
03-Jun-2022 09:51:35 [---] CUDA: NVIDIA GPU 0: NVIDIA GeForce RTX 2080 (driver version 510.73, CUDA version 11.6, compute capability 7.5, 7982MB, **7755MB available**, 10598 GFLOPS peak)
03-Jun-2022 09:51:35 [---] CUDA: NVIDIA GPU 1: NVIDIA GeForce RTX 2080 (driver version 510.73, CUDA version 11.6, compute capability 7.5, 7979MB, **7574MB available**, 10598 GFLOPS peak)
03-Jun-2022 09:51:35 [---] CUDA: NVIDIA GPU 2: NVIDIA GeForce RTX 2080 (driver version 510.73, CUDA version 11.6, compute capability 7.5, 7982MB, **7755MB available**, 10598 GFLOPS peak)
03-Jun-2022 09:51:35 [---] OpenCL: NVIDIA GPU 0: NVIDIA GeForce RTX 2080 (driver version 510.73.05, device version OpenCL 3.0 CUDA, 7982MB, 7755MB available, 10598 GFLOPS peak)
03-Jun-2022 09:51:35 [---] OpenCL: NVIDIA GPU 1: NVIDIA GeForce RTX 2080 (driver version 510.73.05, device version OpenCL 3.0 CUDA, 7979MB, 7574MB available, 10598 GFLOPS peak)
03-Jun-2022 09:51:35 [---] OpenCL: NVIDIA GPU 2: NVIDIA GeForce RTX 2080 (driver version 510.73.05, device version OpenCL 3.0 CUDA, 7982MB, 7755MB available, 10598 GFLOPS peak)

**Comment by RichardHaselgrove** [comment]
Ville's code, quoted by @Ageless93 at https://github.com/BOINC/boinc/issues/1773#issuecomment-602082731, references similar _v2 versions of cuCtxCreate, cuCtxDestroy, and cuMemGetInfo. 

Could leveraging those calls, in the same way as this PR does with cuDeviceTotalMem, cure the available memory report as well?

**Comment by KeithMyers** [comment]
Probably. Ville had the same issue with the available memory on his first iteration.  But we don't know the state of his code at that point and then later what was added to fix the available memory reporting so that it reported via 64 bit memory calls.

He just dropped the clients on us with no view behind the scenes of his development journey.

Juan was in closer contact with him as he was the outlet for releasing the new clients and new code modifications.

But sadly Juan has also dropped from BOINC.  No sign of him either since Seti finished and the pandemic hammered Panama and Brazil where he hailed from.

**Comment by KeithMyers** [comment]
I think you are spot on in this post of yours back on #1773
[https://github.com/BOINC/boinc/issues/1773#issuecomment-602092419](url)

> The theory is simple: if _v2 versions of cuDeviceTotalMem and **cuMemGetInfo** exist in the active library, use them

**Comment by RichardHaselgrove** [comment]
And that ls exactly what @davidpanderson has done in this PR - though so far only for cuDeviceTotalMem. If the _v2 versions **don't** exist, fall back to the originals. Ville didn't maintain that legacy compatibility, which is another reason for not using his code as it stands.

**Comment by RichardHaselgrove** [comment]
@AenBleidd - a curious side note about compiler efficiency.
My normal BOINC client for Linux comes from Gianfranco Costamagna's 'advance release' PPA, and identifies as a shared library of 1.0 MB.
The vcpkg CI builds I've chosen for testing also identify as shared libraries, but occupy 10.3 MB. They're flagged as development builds, but not debug builds.

Not complaining, just remarking. It just grates on those of us who started by having to watch every byte when programming for floppy disks!

**Comment by KeithMyers** [comment]
OK. This is what I think needs to be added.

216 +   CUDA_GDM cuMemGetInfo_v2 = NULL;

231 +   int (*p_cuMemGetInfo_v2)(size_t*, int);

265 +    p_cuMemGetInfo_v2 = (CUDA_GDM)GetProcAddress(cudalib, "cuMemGetInfo_v2");

419  +    if (p_cuMemGetInfo_v2) {
420  +        (*p_cuMemGetInfo_v2)(&global_mem, device);
421  +     } else {
422  +         (*p_cuMemGetInfo)(&global_mem, device);
423  +      }

**Comment by KeithMyers** [comment]
What normally pops out of the compilers are executables with all the debug symbols included.

That is what makes them big and fat.

But you can strip the debug symbols out during the compile by adding the strip flag -s to the gcc statement.

Or strip the debug symbols out later from the executable with
strip --strip-debug filename

I normally just strip the symbols out afterwards and change the boinc client executable from 10.3MB to 1.9MB

**Comment by AenBleidd** [comment]
> @AenBleidd - a curious side note about compiler efficiency. My normal BOINC client for Linux comes from Gianfranco Costamagna's 'advance release' PPA, and identifies as a shared library of 1.0 MB. The vcpkg CI builds I've chosen for testing also identify as shared libraries, but occupy 10.3 MB. They're flagged as development builds, but not debug builds.
> 
> Not complaining, just remarking. It just grates on those of us who started by having to watch every byte when programming for floppy disks!

Build artifacts on CI are not exactly 'release' and contains debug symbols and should be used for testing purposes only. Please remember that we're not using our CI for release builds

**Comment by davidpanderson** [comment]
Oops!  available mem > 4GB should work now too.

**Review by AenBleidd — APPROVED** [review]

**Comment by AenBleidd** [comment]
Code itself looks ok to me but it still need to be tested.
@KeithMyers, could you please repeat your testing? Thanks in advance

**Comment by KeithMyers** [comment]
> Code itself looks ok to me but it still need to be tested. @KeithMyers, could you please repeat your testing? Thanks in advance

OK, that looks like David's last code-fix was the trick.  I just built the boinc-dpa_cuda_mem client in Ubuntu 20.04 LTS and the client is finally reporting 64 bit memory for the TotalMem and the AvailableMem.

05-Jun-2022 17:37:16 [---] Data directory: /home/keith/Downloads/boinc-dpa_cuda_mem/client
05-Jun-2022 17:37:17 [---] CUDA: NVIDIA GPU 0: NVIDIA GeForce RTX 2080 (driver version 470.99, CUDA version 11.4, compute capability 7.5, 7982MB, 7982MB available, 10598 GFLOPS peak)
05-Jun-2022 17:37:17 [---] CUDA: NVIDIA GPU 1: NVIDIA GeForce RTX 2080 (driver version 470.99, CUDA version 11.4, compute capability 7.5, 7979MB, 7979MB available, 10598 GFLOPS peak)
05-Jun-2022 17:37:17 [---] CUDA: NVIDIA GPU 2: NVIDIA GeForce RTX 2080 (driver version 470.99, CUDA version 11.4, compute capability 7.5, 7982MB, 7982MB available, 10598 GFLOPS peak)
05-Jun-2022 17:37:17 [---] OpenCL: NVIDIA GPU 0: NVIDIA GeForce RTX 2080 (driver version 470.129.06, device version OpenCL 3.0 CUDA, 7982MB, 7982MB available, 10598 GFLOPS peak)
05-Jun-2022 17:37:17 [---] OpenCL: NVIDIA GPU 1: NVIDIA GeForce RTX 2080 (driver version 470.129.06, device version OpenCL 3.0 CUDA, 7979MB, 7979MB available, 10598 GFLOPS peak)
05-Jun-2022 17:37:17 [---] OpenCL: NVIDIA GPU 2: NVIDIA GeForce RTX 2080 (driver version 470.129.06, device version OpenCL 3.0 CUDA, 7982MB, 7982MB available, 10598 GFLOPS peak)

So I am satisfied with the PR and it can be merged into Master and close #1773 and #4757.

**Comment by RichardHaselgrove** [comment]
I tested the non-vcpkg Linux version as well, for completeness (I doubt the Linux distros will be using vcpkg). That worked as well:

> Mon 06 Jun 2022 08:40:43 BST |  | CUDA: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 SUPER (driver version 470.99, CUDA version 11.4, compute capability 7.5, 5942MB, 5942MB available, 5153 GFLOPS peak)
> Mon 06 Jun 2022 08:40:43 BST |  | CUDA: NVIDIA GPU 1: NVIDIA GeForce GTX 1660 SUPER (driver version 470.99, CUDA version 11.4, compute capability 7.5, 5945MB, 5945MB available, 5153 GFLOPS peak)
> Mon 06 Jun 2022 08:40:43 BST |  | OpenCL: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 SUPER (driver version 470.129.06, device version OpenCL 3.0 CUDA, 5942MB, 5942MB available, 5153 GFLOPS peak)
> Mon 06 Jun 2022 08:40:43 BST |  | OpenCL: NVIDIA GPU 1: NVIDIA GeForce GTX 1660 SUPER (driver version 470.129.06, device version OpenCL 3.0 CUDA, 5945MB, 5945MB available, 5153 GFLOPS peak)

I'll do Windows a little later.

**Comment by RichardHaselgrove** [comment]
Windows looks OK too.

> 06/06/2022 10:58:34 |  | CUDA: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 472.12, CUDA version 11.4, compute capability 7.5, 6144MB, 6144MB available, 5622 GFLOPS peak)
06/06/2022 10:58:34 |  | CUDA: NVIDIA GPU 1: NVIDIA GeForce GTX 1650 SUPER (driver version 472.12, CUDA version 11.4, compute capability 7.5, 4096MB, 4096MB available, 4531 GFLOPS peak)
06/06/2022 10:58:34 |  | OpenCL: NVIDIA GPU 0: NVIDIA GeForce GTX 1660 Ti (driver version 472.12, device version OpenCL 3.0 CUDA, 6144MB, 6144MB available, 5622 GFLOPS peak)
06/06/2022 10:58:34 |  | OpenCL: NVIDIA GPU 1: NVIDIA GeForce GTX 1650 SUPER (driver version 472.12, device version OpenCL 3.0 CUDA, 4096MB, 4096MB available, 4531 GFLOPS peak)

**Pull request merged**
