### PR TITLE
[Windows Installer] Prevent handle leaks

### LINKED ISSUE #4178: Handle leak in launcher code
Successful calls to `CreateProcess` and `CreateProcessAsUser` return a thread and process handle to the caller via the `ProcInfo` parameter. These need to be explicitly closed otherwise they will be leaked. 

https://github.com/BOINC/boinc/blob/03b2e00990b54caab9a2d725104f1f69b469b505/clientsetup/win/launcher.cpp#L245

https://github.com/BOINC/boinc/blob/03b2e00990b54caab9a2d725104f1f69b469b505/clientsetup/win/launcher.cpp#L278

See remarks here:
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-process_information

### PR DESCRIPTION
**Pull request by BrianNixon**
Fixes #4178

### CODE REVIEW

**Comment by talregev** [comment]
Is it interesting you to do this research?

**Comment by BrianNixon** [comment]
> Is it interesting you to do this research?

At the moment I don’t know enough about installers, or BOINC’s setup needs, to be able to take on that task.

I just picked an easy ‘Newbie’ bug to fix…

**Comment by talregev** [comment]
> > Is it interesting you to do this research?
> 
> At the moment I don’t know enough about installers, or BOINC’s setup needs, to be able to take on that task.
> 
> I just picked an easy ‘Newbie’ bug to fix…

Let me know when you feel ready. Thank you for your fix!

**Review by AenBleidd — APPROVED** [review]
Looks good to me

**Comment by talregev** [comment]
> > As you pointed out in the issue you don't have time for that. So stop blocking others for helping the boinc community.
> 
> I don't stop anybody. I'm just saying that this is a complex task, and it's probably better if I do this. If somebody else has experience - they are always welcome to contribute.

If you say it probably should done by me, it blocking people from learning and give the information for windows installer.

**Comment by AenBleidd** [comment]
> If you say it probably should done by me, it blocking people from learning and give the information for windows installer.

At first, this is not a correct place for such a discussion.
Second, I expressed my opinion, because this is really something that could be more effectively done by me rather than by someone who just starts to learn BOINC codebase. But I still don't block anyone from doing that.

**Pull request merged**
