### PR TITLE
client: if using a dynamic AM and have idle resources, tell the AM

### PR DESCRIPTION
**Pull request by davidpanderson**
Currently, this affects only clients using Science United

### CODE REVIEW

**Comment by TheAspens** [comment]
David,

So far during testing I have done the following: 

Attach to BAM
BAM attaches me to a project (WCG)
Disconnect from BAM
Remove project

When I remove the project the BOINC Manager crashes.  I"m going to test with the build from the master branch and see if I see the same behavior.  Here is the stack trace: 

[knreed@oc7811586721 boinc]$ ./boincmgr 
*** Error in `./boincmgr': corrupted double-linked list: 0x00000000016a7fc0 ***
======= Backtrace: =========
/usr/lib64/libc.so.6(+0x7b9e3)[0x7f861f3419e3]
/usr/lib64/libc.so.6(+0x7d3a5)[0x7f861f3433a5]
/usr/lib64/libc.so.6(__libc_calloc+0xb4)[0x7f861f346b64]
/usr/lib64/libglib-2.0.so.0(g_malloc0+0x16)[0x7f861fef8b16]
/usr/lib64/libgtk-3.so.0(+0x182a43)[0x7f86219b0a43]
/usr/lib64/libgtk-3.so.0(+0x196823)[0x7f86219c4823]
/usr/lib64/libgtk-3.so.0(+0x18500d)[0x7f86219b300d]
/usr/lib64/libgtk-3.so.0(+0x183fa5)[0x7f86219b1fa5]
/usr/lib64/libgtk-3.so.0(+0x183f77)[0x7f86219b1f77]
/usr/lib64/libgtk-3.so.0(+0x184176)[0x7f86219b2176]
/usr/lib64/libgtk-3.so.0(+0x2e5dc0)[0x7f8621b13dc0]
/usr/lib64/libgtk-3.so.0(+0x392b92)[0x7f8621bc0b92]
/usr/lib64/libgtk-3.so.0(gtk_widget_realize+0x178)[0x7f8621bc0dd8]
/usr/lib64/libgtk-3.so.0(gtk_widget_set_parent+0x2d8)[0x7f8621bc57a8]
/usr/lib64/libgtk-3.so.0(gtk_fixed_put+0xc3)[0x7f8621a07463]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(_ZN7wxPizza3putEP10_GtkWidgetiiii+0x5b)[0x7f86248fcbcb]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(_ZN11wxStaticBox6CreateEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizelS4_+0x126)[0x7f86249691c6]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(_ZN11wxStaticBoxC2EP8wxWindowiRK8wxStringRK7wxPointRK6wxSizelS4_+0x61)[0x7f86249692b1]
./boincmgr[0x487865]
./boincmgr[0x46a95f]
./boincmgr[0x52f4c6]
./boincmgr[0x530a3b]
/usr/lib64/libwx_baseu-3.0.so.0(_ZNK16wxAppConsoleBase16CallEventHandlerEP12wxEvtHandlerR14wxEventFunctorR7wxEvent+0x3e)[0x7f8623dd262e]
/usr/lib64/libwx_baseu-3.0.so.0(_ZN12wxEvtHandler23ProcessEventIfMatchesIdERK21wxEventTableEntryBasePS_R7wxEvent+0x52)[0x7f8623f50d42]
/usr/lib64/libwx_baseu-3.0.so.0(_ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler+0x83)[0x7f8623f50df3]
/usr/lib64/libwx_baseu-3.0.so.0(_ZN12wxEvtHandler11TryHereOnlyER7wxEvent+0x3d)[0x7f8623f5114d]
/usr/lib64/libwx_baseu-3.0.so.0(_ZN12wxEvtHandler19ProcessEventLocallyER7wxEvent+0x33)[0x7f8623f511c3]
/usr/lib64/libwx_baseu-3.0.so.0(_ZN12wxEvtHandler12ProcessEventER7wxEvent+0x45)[0x7f8623f51225]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(_ZN12wxWindowBase8TryAfterER7wxEvent+0x68)[0x7f8624a628d8]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(_ZN24wxScrollHelperEvtHandler12ProcessEventER7wxEvent+0x1b)[0x7f8624ab297b]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(_ZN12wxWindowBase8TryAfterER7wxEvent+0x68)[0x7f8624a628d8]
/usr/lib64/libwx_baseu-3.0.so.0(_ZN12wxEvtHandler18SafelyProcessEventER7wxEvent+0x7)[0x7f8623f50fb7]
/usr/lib64/libwx_gtk3u_core-3.0.so.0(+0x2d2889)[0x7f8624932889]
/usr/lib64/libgobject-2.0.so.0(+0xfb97)[0x7f86201cab97]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0x477)[0x7f86201e4157]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit+0x8f)[0x7f86201e4ddf]
/usr/lib64/libgtk-3.so.0(+0x12e99d)[0x7f862195c99d]
/usr/lib64/libgtk-3.so.0(+0x12ea03)[0x7f862195ca03]
/usr/lib64/libgobject-2.0.so.0(g_closure_invoke+0x138)[0x7f86201ca968]
/usr/lib64/libgobject-2.0.so.0(+0x212a7)[0x7f86201dc2a7]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0xe11)[0x7f86201e4af1]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit+0x8f)[0x7f86201e4ddf]
/usr/lib64/libgtk-3.so.0(+0x12cd80)[0x7f862195ad80]
/usr/lib64/libffi.so.6(ffi_call_unix64+0x4c)[0x7f8617bdfdcc]
/usr/lib64/libffi.so.6(ffi_call+0x1f5)[0x7f8617bdf6f5]
/usr/lib64/libgobject-2.0.so.0(g_cclosure_marshal_generic_va+0x2f5)[0x7f86201cb605]
/usr/lib64/libgobject-2.0.so.0(+0xfb97)[0x7f86201cab97]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0x477)[0x7f86201e4157]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit+0x8f)[0x7f86201e4ddf]
/usr/lib64/libgtk-3.so.0(+0x1ea8e1)[0x7f8621a188e1]
/usr/lib64/libgobject-2.0.so.0(g_cclosure_marshal_VOID__BOXEDv+0xa0)[0x7f86201cd9a0]
/usr/lib64/libgobject-2.0.so.0(+0xfb97)[0x7f86201cab97]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0x477)[0x7f86201e4157]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit+0x8f)[0x7f86201e4ddf]
/usr/lib64/libgtk-3.so.0(+0x1e7a8e)[0x7f8621a15a8e]
/usr/lib64/libgtk-3.so.0(+0x1e905b)[0x7f8621a1705b]
/usr/lib64/libgtk-3.so.0(+0x1ebf6e)[0x7f8621a19f6e]
/usr/lib64/libgtk-3.so.0(gtk_event_controller_handle_event+0x8f)[0x7f86219e675f]
/usr/lib64/libgtk-3.so.0(+0x3815fb)[0x7f8621baf5fb]
/usr/lib64/libgtk-3.so.0(+0x2341b5)[0x7f8621a621b5]
/usr/lib64/libgobject-2.0.so.0(g_closure_invoke+0x138)[0x7f86201ca968]
/usr/lib64/libgobject-2.0.so.0(+0x2183b)[0x7f86201dc83b]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0xafc)[0x7f86201e47dc]

**Comment by TheAspens** [comment]
I do not get the crash when I am test with the version built from the master branch so this appears to something new with the code in this branch.

**Comment by davidpanderson** [comment]
Works for me w/ master branch also

**Comment by TheAspens** [comment]
Are you able to reproduce the crash or do you need more info?

**Comment by davidpanderson** [comment]
Haven't tried it with 7.10

**Comment by davidpanderson** [comment]
I couldn't repro this in the dpa_am branch after repeated tries.
Have you repeated it?
What project(s) are you using in BAM?

**Comment by davidpanderson** [comment]
This may be an intermittent race-condition type bug that happens when you
delete a project,
or maybe delete the last project.

**Comment by TheAspens** [comment]
I got it twice, but let me rebuild and reconfirm and see if I can find anything else that would be suggestive.  I'll turn on some logging flags as well to see if that points to anything.

**Comment by TheAspens** [comment]
I wasn't able to reproduce this evening so not sure what that was.  I will finish testing this tomorrow.

**Comment by davidpanderson** [comment]
I suspect it's a race condition that's always been there.

**Comment by TheAspens** [comment]
I heard back from Willy and it is a BAM thing unrelated to this change.

**Pull request merged**
