### PR TITLE
Mac CI: Verify cached library versions match those in Xcode project

### PR DESCRIPTION
**Pull request by CharlieFenton**
Mac: Verify dependent library versions cached by CI match those in the Xcode project by comparing the directory names in dependencyNames.sh with those in the Xcode project search paths.

### CODE REVIEW

**Comment by CharlieFenton** [comment]
I'm closing this PR and have created a cleaner one PR #5196 because in experimenting to get this working I made so many commits. I feel that it is important to remember that when anyone downloads the BOINC source repository, GIT stores all past commits throughout the history on that computer. 

I believe this is good practice and considerate of other developers. So I suggest to everyone: if you have made many experimental commits, please create a streamlined PR with minimal commits and merge that, instead of bloating everyone's local repositories. 

And always remember to delete your feature branch after it has been merged or closed; GitHub gently encourages you to do that by saying that the branch may be safely deleted.

**Comment by AenBleidd** [comment]
@CharlieFenton,

> And always remember to delete your feature branch after it has been merged or closed; GitHub gently encourages you to do that by saying that the branch may be safely deleted.

I'll take a care about this and close all merged branches.

**Comment by davidpanderson** [comment]
I don't think I've ever deleted a branch; I figured I might want to go back and look at the changes later.
I realize there's a huge clutter of dpa_* branches.
Should I delete them?

BTW, I don't think repo size is an issue.  A typical branch delta is maybe a few Kbytes.

**Comment by davidpanderson** [comment]
Before we delete anything: what do we lose when we delete a branch?

**Comment by CharlieFenton** [comment]
> BTW, I don't think repo size is an issue. A typical branch delta is maybe a few Kbytes.

On my Mac, the .git hidden directory in the master repository is currently 308MB. That's almost a third GB. Whether that is significant in this age of terabyte drives is a matter of opinion.

I keep separate copies of each release source tree, so it adds up. (I know I could just use Git to check out each release by its tag, but that changes the modification dates on all the files. I often find the modification dates useful for quick checks.)

**Comment by AenBleidd** [comment]
> Before we delete anything: what do we lose when we delete a branch?

Nothing. All your commits are copied upstream to master, so you literally lost nothing

**Pull request closed without merging**
