### PR TITLE
[WIP] Compile boinc with dynamic libs in ci

### PR DESCRIPTION
**Pull request by talregev**
Dynamic in ci
Investigating issue in Ubuntu and Debian in installation process #4252

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
It already failed :)

```
./configure: line 14691: : supported targets:.* elf: command not found
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
```

**Comment by LocutusOfBorg** [comment]
Now just wait for the build and you will see that its happily just building static libraries and not shared ones

**Comment by talregev** [comment]
@LocutusOfBorg Do you mind to talk over discord channel? (app or website).

**Comment by talregev** [comment]
@LocutusOfBorg 
I will write here my thoughts:
1. First thing, the problem you show me at opencl PR with your logs from Ubuntu/Debian installation process, doesn't seems to connect to share or statics libs. I think it connected to autoconf tool, sometimes doing problems when switching between configs. When it happen, I usually delete 2 makefiles. one in `boinc` directory, and another in `m4` directory. 
2. When you compile apps, in some apps it doesn't matter if it dynamic or static, the makefile will always compile with the static library (*.a) because the makefile config to do.
3. Even when the boinc creates a static library instead of shared ones (when we put dynamic flags in the config), it not connected to my PR. If it does, it an old problem. So undo my PR will not solve static libs instead of shared ones. (maybe it create both?).

So anyway I think your problem is different, and we taking it to the wrong direction, that why I wanted to talk over discord. 
If you really want to solve your problem on your side, please consider my thoughts.
Also it more convenient to write on my PR, because if I want to do tests, or change things, I can change here.
I prefer to talk over discord, but we can stay here if you prefer so.

**Comment by talregev** [comment]
I propose a fix: #4268.
I am closing this PR

**Pull request closed without merging**
