### PR TITLE
Update project list in Win installer directory,

### PR DESCRIPTION
**Pull request by davidpanderson**
and make a copy in client/ for other platforms.
Eventually (once I figure out how) remove the Win copy.

Richard, please apply to the 7.10 branch

### CODE REVIEW

**Comment by CharlieFenton** [comment]
The script which builds the Mac installer gets this from win_build/installerv2/redist/all_projects_list.xml in the current branch / tag. 

Since I've already built and uploaded the version 7.9.1 installer for the Mac, that installer still has the version that was at _win_build/installerv2/redist/all_projects_list.xml_ on Feb 12 at 12:01am in the 7.9.1 tag. My next build will have the new one, but **ONLY** if it is copied / cherry-picked to the _client/client_release 7/7.10_ branch **first**. If we need this done before the first round of alpha testing, that means we need to change the version number to 7.9.2 **after** _win_build/installerv2/redist/all_projects_list.xml_ has been updated in the _client/client_release 7/7.10_ branch, so I can build and upload a new release.

**Comment by brevilo** [comment]
Erm, why does the `platform` include every single plan class? Is that a new feature? That doesn't make sense to me at all as that's project-internal knowledge that might change relatively often (compared to the actual supported platforms). We must not depend on new client releases when we create new plan classes.

I need @bema-ligo to sign off on this as well: on the plan class inclusion as such and, if that's ok, on the completeness/correctness of the list itself.

**Comment by RichardHaselgrove** [comment]
IIRC, the plan classes are required because the same list also drives http://boinc.berkeley.edu/projects.php, and the 'supported platforms' icons (and hardware accelerators) are driven from the list. Again, IIRC, the plan class list is pulled automatically from project servers, and "ought" to be up-to-date. The individual plan class names wouldn't be important in that scenario - just the platform and device components.

**Comment by bema-ligo** [comment]
A static list of plan classes at least for Einstein@Home is outdated once the client is published. In the last 12 months we published about 10 new applications, most of these with their own set of plan classes. If necessary at all, a *current* set of plan classes should be retrieved via the web RPC call, not from a static list that is updated every few years.
Plan class names (at least at our end) are completely arbitrary. Our CPU applications are mostly complied to use AVX when available and fall back to SSE if not. Thus the plan classes are set to require SSE, and most of them don't even show that in the names.

**Comment by bema-ligo** [comment]
On top of that, the fact that an application and app version with a plan class with a certain name exists on a project doesn't mean that the project has actually 'work' for it. We do have a an 32Bit application version for CUDA, but had no work for that application for, I think, more than a year.

**Comment by brevilo** [comment]
> the 'supported platforms' icons (and hardware accelerators) are driven from the list

This seems to be the root cause. I think BOINC lacks a concept for "platform extensions" that allow to add CUDA or OpenCL support to the existing platforms. Plan classes in comparison are internal scheduling identifiers that shouldn't be used for cross-cutting feature tags like the former (missing) concept.

**Comment by RichardHaselgrove** [comment]
Having more time available today, I've had a look through these changes in more detail. Many (all I've looked at) are already active in the version of all_projects_list.xml downloaded by boinc clients every 14 days from http://boinc.berkeley.edu/projects.php. Thus, existing users of boinc v7.8.3 are already invited to attach to the insecure Einstein url, and to use the Science United account manager.

I think the first step is to review and tidy up the online page, and then to use an all projects list generated from the clean online page in our installations.

**Comment by brevilo** [comment]
> insecure Einstein url

It's not just insecure, it's also wrong. The users don't have to be worried, though, as they're being redirected to the secure correct URL automatically - well if BOINC properly follows redirects that is.

**Comment by bema-ligo** [comment]
I vaguely remember problems when the "project URL" differs from the actual "master URL". The latter is defined by the project and fetced from there (i.e. after redirects), but I'm not sure where the clients gets / remembers the "project URL" from.

**Comment by Ageless93** [comment]
From a system that posted in the BOINC forums:
2/11/2018 6:18:59 PM | https://einsteinathome.org/ | Master file download succeeded
2/11/2018 6:19:04 PM | https://einsteinathome.org/ | Sending scheduler request: Project initialization.
2/11/2018 6:19:04 PM | https://einsteinathome.org/ | Requesting new tasks for CPU and NVIDIA GPU
2/11/2018 6:19:10 PM | Einstein@Home | Scheduler request completed: got 1 new tasks
2/11/2018 6:19:10 PM | Einstein@Home | This project is using an old URL. When convenient, remove the project, then add http://einstein.phys.uwm.edu/

**Comment by RichardHaselgrove** [comment]
By contrast, an old machine attached to Einstein with

> <master_url>http://einstein.phys.uwm.edu/</master_url>
<scheduler_url>https://scheduler.einsteinathome.org/EinsteinAtHome_cgi/cgi</scheduler_url>

(both stored in client_state.xml)

gets

> 16/02/2018 16:57:44 | Einstein@Home | update requested by user
16/02/2018 16:57:47 | Einstein@Home | Sending scheduler request: Requested by user.
16/02/2018 16:57:49 | Einstein@Home | Scheduler request completed
16/02/2018 16:57:49 | Einstein@Home | Project requested delay of 60 seconds

without further complaint

**Comment by RichardHaselgrove** [comment]
In contrast to the user Jord quoted, I've just detached that old machine and re-attached using a non-updated (see #2352) v7.8.3 project list:

> 16/02/2018 17:37:11 | Einstein@Home | Resetting project
16/02/2018 17:37:12 | Einstein@Home | Detaching from project
16/02/2018 17:37:33 |  | Fetching configuration file from https://einsteinathome.org/get_project_config.php
16/02/2018 17:37:53 | Einstein@Home | sched RPC pending: Project initialization
16/02/2018 17:37:56 | Einstein@Home | Master file download succeeded
16/02/2018 17:38:02 | Einstein@Home | sched RPC pending: Project initialization
16/02/2018 17:38:02 | Einstein@Home | Sending scheduler request: Project initialization.
16/02/2018 17:38:02 | Einstein@Home | Requesting new tasks for CPU and NVIDIA GPU
16/02/2018 17:38:04 | Einstein@Home | Scheduler request completed: got 1 new tasks

with *no* warning about an old url. Maybe they're working on it.

But then again, manually fetching https://einsteinathome.org/get_project_config.php in a browser (Windows 7, 32 bit, Chrome) gets you

> <project_config>
<name>Einstein@Home</name>
<master_url>http://einstein.phys.uwm.edu/</master_url>
<web_rpc_url_base>https://einstein.phys.uwm.edu/</web_rpc_url_base>
<web_stopped>0</web_stopped>
<min_passwd_length>6</min_passwd_length>
<sched_stopped>0</sched_stopped>
<min_client_version>50800</min_client_version>
...

**Comment by RichardHaselgrove** [comment]
Ah - looking at the source of the lines Jord quoted (https://boinc.berkeley.edu/dev/forum_thread.php?id=12302&postid=84757#84757), I see

> 2/11/2018 6:14:41 PM | | Starting BOINC client version 7.6.33 for windows_x86_64
> 2/11/2018 6:14:41 PM | | This computer is not attached to any projects
> 2/11/2018 6:14:41 PM | | Visit http://boinc.berkeley.edu for instructions
> 2/11/2018 6:15:05 PM | | Fetching configuration file from https://www.grcpool.com/get_project_config.php
> 2/11/2018 6:16:24 PM | | Contacting account manager at https://www.grcpool.com/
> 2/11/2018 6:16:24 PM | | Account manager contact succeeded

The non-standard attach may have something to do with it.

**Comment by Ageless93** [comment]
Yes, I saw he was using grcpool, but don't think that is the problem here. Even though he uses an account manager, it appears his BOINC (Manager) is still comparing URLs against the all_project_list.xml file, because the projects list at https://grcpool.com/project shows https://einsteinathome.org/ for Einstein@Home.

**Comment by RichardHaselgrove** [comment]
For the moment, view-source:https://www.grcpool.com/get_project_config.php is just giving me

> <project_config>
    <name>grcpool.com</name>
    <min_passwd_length>8</min_passwd_length>
    <account_manager/>
    <uses_username/>
    <client_account_creation_disabled/>
</project_config>

I'll try again when they're online. Or maybe I would have had to have created an account, and selected Einstein as one of my projects, to see what master url they send me for Einstein? Maybe not - I've never bothered to learn how an account manager works, and I don't really feel the urge to learn now.

**Comment by ChristianBeer** [comment]
There should be a thread on the einstein forum about the URL change. The gist is that the Client behaves different when attaching via BOINC Manager or via an Account Manager. The BOINC Manager takes the URL entered by the user and retrieves the `get_project_config.php` output from there. This contains the master URL that is used to connect. That's why `https://einsteinathome.org/` works when used via BOINC Manager. If that same URL is used from an Account Manager it is used as master URL directly and the project config is not retrieved. That's why BAM needed to switch back to
`http://einstein.phys.uwm.edu/` several times in the past.

**Comment by RichardHaselgrove** [comment]
@ChristianBeer - that matches what I'd been working out for myself: there is a difference between the public 'join' url, and the private 'master' url: and it feels as if the AM is sending the 'join' when it should be sending the 'master'.

Nevertheless, for the purposes of this thread: all_projects_list.xml should contain the 'join' url, and the project has requested that this be in https format - and currently it isn't.

@davidpanderson - could you rectify this, please?

**Comment by davidpanderson** [comment]
I botched this - starting over

**Comment by RichardHaselgrove** [comment]
I'll double-check the Einstein commit in the morning, in the expectation I'll be able to approve it and tag for a v7.9.2 build. It's approaching midnight here.

But can you remove the Drupal work from this PR, please, and make it a separate atomic PR?

**Comment by RichardHaselgrove** [comment]
OK, I'll leave you to it - bedtime, and comments still stand.

**Comment by davidpanderson** [comment]
E@h's get_project_config.php returns an http:// URL

On Fri, Feb 16, 2018 at 3:22 PM, RichardHaselgrove <notifications@github.com

**Comment by RichardHaselgrove** [comment]
Which url? Einstein's 'Join' url (required in the XML) is https://einsteinathome.org (see https://einsteinathome.org/join)
Their 'master' url (fetched by get_project_config.php) is http://einstein.phys.uwm.edu/

Don't ask me why, but it's their project, their choice.

**Comment by brevilo** [comment]
> Don't ask me why, but it's their project, their choice.

The reason is that, to our knowledge, one can't just change a project's master URL as it can/will break stuff in BOINC (I don't remember the details). If that's not true anyway we'd be happy to update the master URL as well.

**Pull request closed without merging**
