### PR TITLE
Update deprecated Python syntax and func references

### PR DESCRIPTION
**Pull request by hristog**
**Relevant Issue #**
N/A

**Description of the Change**
This updates some deprecated Python v2 syntax and function references (particularly, `apply`; see https://docs.python.org/2/library/functions.html#non-essential-built-in-functions).

The justification is enabling better readabilty and clarity, as well as making strides towards updating the codebase to be in a state that'd be easily portable to Python v3.

**Alternate Designs**
N/A

**Release Notes**
N/A

### CODE REVIEW

**Comment by TheAspens** [comment]
@hristog - PR #4303 enabled support for both python2 and python3.  Is there anything in this PR that should be retained or can it be closed?

**Comment by hristog** [comment]
Hi @TheAspens, thanks for checking!

Yes, I confirm the proposed changes implemented in #3722 are distinct from #4043, #3259 and #4070, and can be retained.
I couldn't find #4303 which you've referenced - I suppose the PR ID had a typo in it.

**Comment by hristog** [comment]
I confirm I've now merged the latest `master` into my branch (and pushed, which has updated this PR as well), and I'm awaiting the completion of the code checks.

**Comment by hristog** [comment]
@TheAspens, I can see that all 4 automated checks have passed successfully.
Do you need me to do any further changes, related to this PR?

**Comment by TheAspens** [comment]
My apologies for the delay.  I've tested setting up a new project and performing basic functions on it and it all looks good.  Thanks for the contribution.

**Comment by hristog** [comment]
No problem at all. Thanks for confirming!

**Pull request merged**
