### PR TITLE
[wasm] Add debug information

### PR DESCRIPTION
**Pull request by talregev**
Add debug information.

### CODE REVIEW

**Comment by talregev** [comment]
Debug information at chrome, to debug with cpp and header files: 

image

**Comment by talregev** [comment]
@AenBleidd There is something wrong in our ci?

**Comment by AenBleidd** [comment]
@talregev, looks like some issues ob GitHub itself

**Comment by talregev** [comment]
> @talregev, looks like some issues ob GitHub itself

ok. Let's wait on this PR.

**Comment by talregev** [comment]
I made changes since the last screenshot. now is working better and map to all client and lib files correctly. 
image

@AenBleidd Ready for review.

**Pull request merged**
