### PR TITLE
Manager: don't crash when alt-space is pressed

### LINKED ISSUE #4186: Minor GUI manager crash
**Describe the bug**
Yawned mid alt-tab and accidently hit space while holding down the alt-key and noticed the manager window went poof.

**Steps To Reproduce**
1. In simple or advanced view, press on the keyboard Alt-space
2. Manager closes, but tasks continue to run.

**Expected behavior**
That it not crash, or, more proper, opens the titlebar menu (rightclick the title bar) as alt-space is a common shortcut to get to that menu.

**Screenshots**

**System Information**
 - OS: Windows 10 1909 (18363.1316)
 - BOINC Version: Manager 7.16.11 (x64)

**Additional context**
[stderrgui.txt](https://github.com/BOINC/boinc/files/5988327/stderrgui.txt)
Managed to find the log files, cleaned them then triggered the crash and uploaded the only one that contained anything, hopefully that call stack helps find the cause.

### PR DESCRIPTION
**Pull request by davidpanderson**
Fixes #4186

### CODE REVIEW

**Comment by AenBleidd** [comment]
@RichardHaselgrove, could you please verify this?
You can find artifacts here: https://github.com/BOINC/boinc/suites/2054202143/artifacts/41415177

**Review by AenBleidd — APPROVED** [review]

**Comment by RichardHaselgrove** [comment]
Will do. Let me wake up a bit first.

**Comment by RichardHaselgrove** [comment]
Yup, that seems to work OK. Tested (so far) on a Windows 7 machine running a stock v7.16.11 installation - original bug report confirmed. I can repeat on Windows 10 if needed, and I have a full debug log for the crash.

With the artifact build (only accessible if you're logged in to GitHub, BTW), the planned Alt-tab operation works normally, and Alt-space drops down the windows control menu (in both Advanced and Simple view):

image
Not sure if that's the formal expected result, but it's safe and good enough.

**Comment by RichardHaselgrove** [comment]
Confirmed - that is the expected behaviour, according to Microsoft documentation. Useful: I sometimes need to access the 'Move' command when I need to move a Window off a headless display adapter.

**Pull request merged**
