### PR TITLE
update_versions: add --noconfirm option

### PR DESCRIPTION
**Pull request by davidpanderson**

### CODE REVIEW

**Comment by AenBleidd** [comment]
@davidpanderson, for some reason server integration tests is failing trying to connect to the server running in docker container.
I assume this happens because server instance was not created properly.
Could you please check this somehow and fix?

**Comment by davidpanderson** [comment]
I'm seeing the following, which looks like a server is down:


4964> Task :app:javaPreCompileArmv6_debug FAILED
4965FAILURE: Build failed with an exception.
4966
4967* What went wrong:
4968Execution failed for task ':app:javaPreCompileArmv6_debug'.
4969> Could not resolve all files for configuration
':app:_agp_internal_javaPreCompileArmv6_debug_kaptClasspath'.
4970 > Could not resolve com.google.dagger:dagger-compiler:2.44.
4971 Required by:
4972 project :app
4973 > Could not resolve com.google.dagger:dagger-compiler:2.44.
4974 > Could not get resource
'https://repo.maven.apache.org/maven2/com/google/dagger/dagger-compiler/2.44/dagger-compiler-2.44.pom'.
4975 > Could not GET
'https://repo.maven.apache.org/maven2/com/google/dagger/dagger-compiler/2.44/dagger-compiler-2.44.pom'.
4976 > Connect to repo.maven.apache.org:443
[repo.maven.apache.org/146.75.28.215] failed: Connect timed out
4977
4978* Try:
4979> Run with --stacktrace option to get the stack trace.
4980> Run with --info or --debug option to get more log output.
4981> Run with --scan to get full insights.
4982
4983* Get more help at https://help.gradle.org
4984
4985BUILD FAILED in 2m 40s
498616 actionable tasks: 15 executed, 1 up-to-date
4987Error: Process completed with exit code 1.
Build libs
0s
Build apps
0s
Build manager with vcpkg
0s
Build libs with vcpkg
0s
Build apps with vcpkg
0s
Build libs with cmake
0s
Prepare logs on failure
0s
Upload logs on failure
0s
Prepare artifacts for deploy
0s
Upload generic artifacts
0s
Upload xiaomi manager
0s
Upload armv6 only manager
0s
Upload JUnit Tests Results
0s
Upload coverage report
0s
Post Cache dependencies
0s
Post Setup Java
0s
Post Run ***@***.***
0s
Complete job
0s
update_versions: add --noconfirm option · ***@***.***

**Comment by AenBleidd** [comment]
Not sure this is really related: I tried to rerun and it always fails on this PR and never fails on any other without this change.
I can dig to find the exact reason

**Comment by davidpanderson** [comment]
That's odd - the automated build AFAIK doesn't involve this file.

**Comment by AenBleidd** [comment]
It's done while building BOINC server via docker: https://github.com/marius311/boinc-server-docker/blob/28df02f75c07650c53a7c5f0a389118f48698fda/images/makeproject/makeproject-step2.sh#L63

**Comment by davidpanderson** [comment]
Oops!!  I accidentally made it non-executable.  Fixed now.

**Review by AenBleidd — APPROVED** [review]

**Comment by AenBleidd** [comment]
@lfield, would be nice if you could review this as well.

**Comment by lfield** [comment]
LGTM

**Pull request merged**
