### PR TITLE
Update code of conduct

### PR DESCRIPTION
**Pull request by adamradocz**
Response to the first item at #2819

### CODE REVIEW

**Comment by lfield** [comment]
This change requires general project consensus. Is this a PMC or Committers vote?

**Comment by adamradocz** [comment]
> This change requires general project consensus. Is this a PMC or Committers vote?

No, this change hasn't voted. I just proposed an idea, to move a more standardized, but very similar code of conduct that we have.

**Comment by TheAspens** [comment]
This would require a PMC vote for approval, but I would like to have a majority of committers indicate their support of this as well as a good discussion of it before taking it before the PMC.

**Comment by tristanolive** [comment]
I don't think we gain anything by using the github template. If I recall, that template (among others) was used as a starting point for the BOINC code of conduct and ideas from different resources were melded together into what we have.

If there are specific shortcomings, it makes sense to address them, but I'd view this move as unnecessary and maybe even a step backwards in terms of readability (I may just be missing the specifics in the diff).

**Comment by brevilo** [comment]
I had a brief look at the proposed changes. Before I dive any deeper I'd like to understand the motivation for those changes:
* why are these changes necessary?
* what problem do they address?
* how are they an improvement over the current doc?

**Comment by adamradocz** [comment]
> I had a brief look at the proposed changes. Before I dive any deeper I'd like to understand the motivation for those changes:
> 
> * why are these changes necessary?
> * what problem do they address?
> * how are they an improvement over the current doc?

I thought a standardized version of the COC is easier to understand, because of its standardized nature. That's it, nothing fancy.

**Comment by brevilo** [comment]
Thanks, I see your point Adam. I don't have a strong opinion on this: I'm neither sure the COC represents such a standard, nor do I think we stray far from any COC as they're all structured similarly, while still representing each project's specifics. Again, I'm neutral on this as I mostly care about the content and its clear communication and not so much about a perceived standardization. Up to the PMC...

**Comment by adamradocz** [comment]
I'm going to close this issue, because the trouble bigger with it, then the expected gain.

**Pull request closed without merging**
