### PR TITLE
BOINC GAHP condor input template

### PR DESCRIPTION
**Pull request by bema-ligo**
This is a _preliminary_ implementation of my feature request to allow submitting an arbitrary input/workunit template file from Condor.

If the name of an input file specified in condor submit ends in "_input_tempplate.xml", it is removed from the list of "normal" input files, uploaded separately to the server and used as an input template for the current batch.

I guess that augmenting the GAHP protocol as requested and implementing that change on the Condor side will take some time that I am not willing to wait. However with this patch, the functionality on the BOINC side then is already implemented, and once this change is made at the Condor end, only one function (process_local_input_template()) needs to be changed in BOINC GAHP to adapt to that.

### CODE REVIEW

**Comment by bema-ligo** [comment]
@davidpanderson thanks fo rignoring this PR for a year and now creating a conflict. Would you mind telling me what you don't like about this PR?

**Comment by lfield** [comment]
Please can you briefly describe how to use this feature and I will try to test it.

**Comment by bema-ligo** [comment]
The original problem this was trying to fix was that having only a single input template configured on the server per application is inflexible, as e.g. the number of input files is then fixed per application. This PR implements a way in remote submission to upload an arbitrary input template to be used for a "batch", and to make use of this when submitting from Condor. As I mentioned in the description: 
> If the name of an input file specified in condor submit ends in "_input_tempplate.xml", it is removed from the list of "normal" input files, uploaded separately to the server and used as an input template for the current batch.

However in his "TBD" talk on the BOINC workshop last week @davidpanderson mentioned that he implemented/uses per-job input templates already. If this development is going to be merged back into BOINC, this PR would be obsolete.

**Comment by bema-ligo** [comment]
A problem of this PR is that the "templates" directory on the server must be writable by the user of the "remote submission" system (i.e. PHP or apache or whatever). This is an additional security risk.

**Comment by lfield** [comment]
I would recommend closing this PR. There have been a quite a few changes to the remote submission RPC. It is now working well for us with the boinc_gahp at reasonable scale O(10K) submissions. Some changes are required to the HTCondor gridmanger but it is possible to get this done on a reasonable time scale. eg. 

https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=6669

I would recommend rebasing and contacting me directly for the HTCondor gridmanger changes. They will be pushed to the HTCondor repository soon.

**Comment by bema-ligo** [comment]
@lfield I'll take a look at current state of remote job submission and BOINC-Condor-GAHP as soon as time permits (i.e. after May 25.).

**Comment by lfield** [comment]
Here are the changes to the condor_gridmanger.

https://github.com/htcondor/htcondor/pull/22

**Pull request closed without merging**
