### PR TITLE
Manager: Change back 'Forgot your account info?' to 'Forgot your pass…

### LINKED ISSUE #1049: When adding a project, "Forgot your password?" link should say "Forgot your account info?"
**Reported by JacobKlein on 10 Mar 41246431 17:46 UTC**
Since the hyperlink takes you to a page called "Forgot your account info?", and the page can be used to determine more than just the password (i.e.: can determine email address)...

The link should say: "Forgot your account info?"

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1073

### PR DESCRIPTION
**Pull request by AenBleidd**
…word?'

This reverts #2197 pull request after the discussion on #1049.
Fixes #1049.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by Ageless93** [comment]
I veto this change, please do not merge for the time being. See ongoing discussion at #1049

**Comment by davidpanderson** [comment]
Veto it why?

**Comment by Ageless93** [comment]
Because  - like I said in #1049 - I don't feel the change back was done according to the rules. And furthermore, between what you said in the discussion over there (the account key info going away) and what I found in a search on older projects (the original text **was** "Forgot your account info?") it's getting confusing. 

Your code change with regards of removing the 'logging in with your account key' instructions may even require that you write a new PR for a code change of the page to "Forgot your password?"

**Comment by davidpanderson** [comment]
Um, yeah, I changed the title of the web page to "Reset Password" in PR 2254.
Now the link to it needs to say "Forgot your password?"

**Comment by CharlieFenton** [comment]
@Ageless93: 7 days have passed and no one has added any more comments. Does PR #2254 satisfy your other objections? Are you ready to remove your veto?

**Comment by Ageless93** [comment]
I'll unveto this issue to let things resume as normal.

**Comment by CharlieFenton** [comment]
closed

**Pull request merged**
