### PR TITLE
client: PVS Studio static code analyzer fixes

### PR DESCRIPTION
**Pull request by dimhotepus**
**Description of the Change**
client fixes by PVS Studio static code analyzer.

**Alternate Designs**
None

**Release Notes**
N/A

### CODE REVIEW

**Comment by AenBleidd** [comment]
This project is not a place for advertisement. Please remove links from the description.

**Comment by dimhotepus** [comment]
> This project is not a place for advertisement. Please remove links from the description.

Ok, done.

**Comment by davidpanderson** [comment]
There are lots of lint-type programs out there, and I see no need to take all their suggestions unless there are actual bugs.  Let's discuss sweeping changes like this in the future.

**Comment by AenBleidd** [comment]
I agree but most of these changes are to improve performance, remove some potential issues or doing smth more efficiently. I see no reason why we may ignore them. Especially when such atomic changes are not affect any functionality and thus could be considered as safe

**Pull request merged**
