### PR TITLE
[WIP]Issues template

### PR DESCRIPTION
**Pull request by Ageless93**
This is an example Issues template that I'd like to have added to Master. It'll then show for anyone who creates an issue. Are there any additions or retractions people want?

### CODE REVIEW

**Comment by Ageless93** [comment]
By the way, to test this template, you can use https://github.com/Ageless93/Testing-templates-for-boinc-issues-PRs and make an issue there, or check the test issue.

**Comment by Ageless93** [comment]
Since no one has any comments on the template, I'm taking WIP off the title and ask that someone add it to Master, so that all issue made from that point onwards have the template in place.

**Comment by davidpanderson** [comment]
The template is OK for issues involving the client, but not so much for other issues.

**Comment by Ageless93** [comment]
All right, you're right. Back to the drawing board.

**Comment by Ageless93** [comment]
I'm retracting this one for now, until I have more time to figure out how to make one unified Client/Manager/Server issues template.

**Pull request closed without merging**
