### PR TITLE
add remote submit from Condor parameter tuning capability

### PR DESCRIPTION
**Pull request by nikolasgianna**
This pull request is to make it possible to set the following parameters: 

`rsc_fpops_est, rsc_fpops_bound, rsc_memory_bound, rsc_disk_bound, delay_bound, app_version_num `

when submitting to BOINC through Condor.  

See: https://github.com/htcondor/htcondor/pull/19

### CODE REVIEW

**Comment by TheAspens** [comment]
@davidpanderson - can you review this?  If not, it is about time I learn how to use the remote submit capability and I'll test this later this week.

**Comment by davidpanderson** [comment]
We combine job parameters in a input template structure instead of passing them as separate args.
submit_batch() already lets you pass an input template for each job.  The RPC handler puts these in temp files.  We should use the same approach for batch-level templates.

**Comment by davidpanderson** [comment]
I'll submit something in a few days that provides the same functionality.

**Comment by TheAspens** [comment]
Closed in deference to #2416

**Pull request closed without merging**
