### PR TITLE
Manager: Fixed EventLog window GUI glitch with selected unfocused rows.

### PR DESCRIPTION
**Pull request by AenBleidd**
As requested in #1083: GUI Glitch - Actions on 2+ selected rows appear to leave every other row unselected

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by AenBleidd** [comment]
@JuhaSointusalo, could you please verify this? Thanks

**Comment by JuhaSointusalo** [comment]
Sorry for taking this long to review this PR.

I would have liked a bit more text explaining what caused the problem, why it leaves stripes blue and changes non stripes to grey, why similar lists work in project and task views, and how your change fixed the problem.

I played with the code a bit and I think this change is the one that fixes the colours for non focused rows:

```
 #if EVENT_LOG_STRIPES
      m_pMessageInfoGrayAttr = new wxListItemAttr(
          wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT),
 -        wxColour(240, 240, 240),
 +        wxColour(244, 244, 244),
          wxNullFont
      );
 -    m_pMessageErrorGrayAttr = new wxListItemAttr(*wxRED, wxColour(240, 240, 240), wxNullFont);
 +    m_pMessageErrorGrayAttr = new wxListItemAttr(*wxRED, wxColour(244, 244, 244), wxNullFont);
  #else
```

At least on my system `240,240,240` happens to be the same colour as non focused selection. I'm not going to go though the list control paint code to verify but I'm guessing there is some clever code that tries to avoid redrawing unchanged rows but not clever enough to take selections into account.

I think your first commit accidentally fixed the colours by changing the colours of selected stripes and made the rows look like they had changed. wxWidgets doesn't allow programmers to choose selection colours and because of that the attributes you added should actually do nothing.

So I think the correct way to fix this is to make the changes to stripe colours and remove all other changes. But before you do that wait a bit, lets get the colours exactly right.

**Comment by JuhaSointusalo** [comment]
Something like this:

```
#if EVENT_LOG_STRIPES
    m_pList->EnableAlternateRowColours();

#if wxCHECK_VERSION(3,1,0)
    wxColour stripe = m_pList->GetAlternateRowColour();
#else
    wxColour stripe = m_pList->wxListCtrl::OnGetItemAttr(1)->GetBackgroundColour();
#endif

    m_pMessageInfoGrayAttr = new wxListItemAttr(
        wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT),
        stripe,
        wxNullFont
    );
    m_pMessageErrorGrayAttr = new wxListItemAttr(
        *wxRED,
        stripe,
        wxNullFont
    );
#else
    m_pMessageInfoGrayAttr = new wxListItemAttr(*m_pMessageInfoAttr);
    m_pMessageErrorGrayAttr = new wxListItemAttr(*m_pMessageErrorAttr);
#endif
```

The thinking I have is that by using the same stripe colour as wxWidgets would have used has the best chances of working right. The wx < 3.1 code abuses implementation details a bit but it's not like there are going to be any changes now. [source](https://github.com/wxWidgets/wxWidgets/blob/WX_3_0_BRANCH/src/common/listctrlcmn.cpp#L218)

**Comment by AenBleidd** [comment]
Hello @JuhaSointusalo, thank you for testing.

> I would have liked a bit more text explaining what caused the problem

This happens because we use custom colours to draw the table. We use custom colours to draw the table because we use filtering.

> why it leaves stripes blue and changes non stripes to grey

Because we draw every second line to enable zebra-style colouring.

> why similar lists work in project and task views

Because there we don't use custom colours to draw the table

>  how your change fixed the problem.

I draw now not focused line too

> I played with the code a bit and I think this change is the one that fixes the colours for non focused rows:

No. Here I change the colour to be the same as on the other grids: now if you select some rows and change the focus to another control you will see different colours on selected lines and not selected lines. Before this change these lines were the same colour.

> I think your first commit accidentally fixed the colours by changing the colours of selected stripes and made the rows look like they had changed. 

My first commit actually fixes the problem. Last 2 commits just to adjust colours with other grids.

> wxWidgets doesn't allow programmers to choose selection colours and because of that the attributes you added should actually do nothing.

Ok you can test this. For me without those lines I have the same GUI glitch.

> So I think the correct way to fix this is to make the changes to stripe colours and remove all other changes. 

Unfortunately there are no unnecessary changes.

> But before you do that wait a bit, lets get the colours exactly right.

Yes, please check colours. I check them on Win10 with colour picker tool to identify the colour.

**Comment by AenBleidd** [comment]
`#if wxCHECK_VERSION(3,1,0)
    wxColour stripe = m_pList->GetAlternateRowColour();
#else
    wxColour stripe = m_pList->wxListCtrl::OnGetItemAttr(1)->GetBackgroundColour();
#endif`

If I remember correct we are not supporting wxWidgets 3.1 right now so I didn't check this on wxWidgets 3.1

**Comment by JuhaSointusalo** [comment]
> Before this change these lines were the same colour.

The colours used for stripes and non focused selection are indeed very similar. FWIW, wx 3.1 uses themed list control and there it's easier to see difference between stripes and selections.

> My first commit actually fixes the problem. Last 2 commits just to adjust colours with other grids.

Could you test only the colour changes?

> Ok you can test this. For me without those lines I have the same GUI glitch.

I did test it. I set SelectedNonFocused to yellow and green background colour but I didn't get yellow and green on screen.

> Yes, please check colours. I check them on Win10 with colour picker tool to identify the colour.

I used Snipping Tool + Paint's Colour picker to check the colours. Task list has stripes `247,247,247` and non focused selection `240,240,240`.

> If I remember correct we are not supporting wxWidgets 3.1 right now so I didn't check this on wxWidgets 3.1

Google takes me more often to wxWidgets development docs than it takes to 3.0 docs. I noticed `GetAlternateRowColour` there and though why not use it.

**Comment by AenBleidd** [comment]
Ok. I check this now.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, I am very sorry. You're completely right. I clean-up the code. Thank you.

**Comment by AenBleidd** [comment]
` wxColour stripe = m_pList->wxListCtrl::OnGetItemAttr(1)->GetBackgroundColour();`

This code fails with null-reference exception. So I need to think about the different method to get alternate row colour.

**Comment by AenBleidd** [comment]
@JuhaSointusalo,
I think you code is much better in this case.
Please create pull request with your changes and close this as outdated.
Thanks

**Comment by JuhaSointusalo** [comment]
I can make a new PR but I don't have the powers to close this one.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, Ok, I'll close this by myself. Thanks

**Comment by AenBleidd** [comment]
@JuhaSointusalo, do you plan to make a PR?

**Comment by JuhaSointusalo** [comment]
@AenBleidd It's on the to-do pile. I thought it might be better to check
that the stripe colour won't be one that causes problems and if it is then
slightly adjust it. And I think it would be responsible thing to do to
reduce the code to a simple test case and submit it to wxWidgets developers
so that they can fix the code.

I'm going to give the VBox PR yet another look first and this I think will
be in turn next week.

**Comment by AenBleidd** [comment]
@JuhaSointusalo, ok, great. I just want to be sure that it is not forgotten :-) Thank you

**Comment by AenBleidd** [comment]
I close this one pull request and open more clean #2187

**Pull request closed without merging**
