### PR TITLE
BOINC web: fix team file path

### PR DESCRIPTION
**Pull request by davidpanderson**

### CODE REVIEW

**Comment by davidpanderson** [comment]
?? I made a branch based on master, and got the same set of merges

**Comment by AenBleidd** [comment]
@davidpanderson,
Please do a cherry-pick of commit 'BOINC web: fix path of teams file' and
apply it on a new branch based on master. Also please verify that your
master branch (local) and remote one are up-to-date.
Thanks

Best regards,
Vitalii Koshura

2017-09-15 10:26 GMT+03:00 David Anderson <notifications@github.com>:

**Comment by ChristianBeer** [comment]
It seems your local copy of master has those merges on it. You need to reset your local branch to the remote branch so they are in sync again. On the command line you need to do this with:
```
git checkout master
git fetch
git reset --hard origin/master
```
That will bring your local master branch to the same commit as the remote master branch. You can now branch off new feature branches from here and cherry pick commits from the borked feature branches. Please be aware that `git reset` is a dangerous command to use and is not always the best solution.

To prevent such things in the future please make sure that when you pull the master branch from github to only perform fast-forward merges.

**Comment by AenBleidd** [comment]
In such cases I always make a new branch not from the local master but from
the remote/master

Best regards,
Vitalii

Sent via Android

15 сент. 2017 г. 11:11 пользователь "Christian Beer" <
notifications@github.com> написал:

**Comment by davidpanderson** [comment]
I did 
git reset --hard origin/master
and that seemed to work.

**Comment by davidpanderson** [comment]
Thanks.  What does "when you pull the master branch from github to only perform fast-forward merges." mean?

**Comment by AenBleidd** [comment]
@davidpanderson, this is quite good described here:
https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

Best regards,
Vitalii Koshura

2017-09-16 1:18 GMT+03:00 David Anderson <notifications@github.com>:

**Pull request closed without merging**
